remirror/remirror

azure-pipelines.yml
Add azure pipelines as a CI option. 
This will be very important when tests for react-native editor components are added.
=> ci: setup azure pipelines

azure-pipelines.yml, package.json, support/pipelines/jobs.yml, support/pipelines/yarn-install.yml
- Make the azure pipelines build parallel for faster builds
- Run tests on windows, macOS, and Linux
- Break tasks up into templates
Closes #40
=> ci: make azure pipelines parallel

.travis.yml
Adds support to Travis for PRs with secure variables (i.e. ignores all secure checks in PRs).
=> ci: add pr support for secure variables

readme.md
Add a notice on current work being done on Remirror.
=> docs: update readme with notice

@remirror/renderer-react/src/renderer.tsx
=> Fix: skipUnknownTypes check should be falsey

docs/index.mdx, readme.md
=> Docs update: fix links to contributing.md

@remirror/dev/jest.config.js, @remirror/dev/package.json, @remirror/dev/readme.md, @remirror/dev/src/__tests__/prosemirror-dev-tools.spec.tsx, @remirror/dev/src/index.ts, @remirror/dev/src/patches.d.ts, @remirror/dev/src/prosemirror-dev-tools.ts, @remirror/dev/tsconfig.json, @remirror/dev/tsconfig.lint.json, @remirror/dev/tsconfig.prod.json, @remirror/editor-twitter/src/components/twitter.editor.tsx, @remirror/editor-twitter/src/twitter-types.ts, @remirror/editor-wysiwyg/src/components/wysiwyg-editor.tsx, @remirror/showcase/package.json, @remirror/showcase/src/__stories__/twitter.stories.tsx, @remirror/showcase/src/__stories__/wysiwyg.stories.tsx, @remirror/showcase/src/patches.d.ts, changelog.md, support/rollup/rollup.config.js, support/storybook/.babelrc.js, support/tsconfig.paths.json, yarn.lock
Basically this implements the amazing [`prosemirror-dev-tools`](https://github.com/d4rkr00t/prosemirror-dev-tools) package. 
Massive thanks to @jashmenn for introducing it to me. 
To get started import the component and place it within a `RemirrorContext` as in the following example.
```tsx
import { ProsemirrorDevTools } from '@remirror/dev';
import { storiesOf } from '@storybook/react';
import React from 'react';
import { ExampleWysiwygEditor, WYSIWYG_SHOWCASE_CONTENT } from '../wysiwyg';
storiesOf('Wysiwyg Editor', module).add('Basic', () => (
<ExampleWysiwygEditor>
<ProsemirrorDevTools />
</ExampleWysiwygEditor>
));
```
=> feat: new package @remirror/dev

docs/pages/contributing.md, package.json, support/tsconfig.base.json
Whilst trying to find my way around the codebase, here's a few tweaks I made. Each change is in it's own commit so feel free to cherry-pick any you want if you don't want them all :+1: 
=> A few minor tweaks

docs/pages/guides/advanced-guide.mdx
=> Underline -> UnderlineExtension

docs/pages/guides/advanced-guide.mdx
I spotted a typo while going through the Advanced Guide and took it as an opportunity to go through the document to apply grammar changes and make some small revisions for clarity.
=> Advanced Guide Edits for Clarity and Grammar

@remirror/core-extensions/src/extensions/history-extension.ts, @remirror/extension-collaboration/src/collaboration-extension.ts
As I was reading through the source I spotted a few minor things I thought I'd clean up:
* Fixed a ts complaint about using before defining
* Fixed a typo in a comment
* Simplified a function's internal to return a bool
=> Minor Cleanup

docs/pages/guides/quickstart.mdx, docs/pages/introduction.mdx, examples/with-next/components/layout.tsx, examples/with-next/readme.md, examples/with-next/screenshots/home.png, examples/with-next/screenshots/social.png, examples/with-next/screenshots/wysiwyg.png, readme.md
It was hard to know where to look initially to get started, "read through the codebase and take a look at how existing editors have been structured" has no "starting point", and the repo is quite large.
To solve this, I've suggested people get started with the next example, and have added instructions on how to get that running.
=> docs: help people get started

.changeset/poor-lobsters-smoke.md, @remirror/editor-wysiwyg/src/components/wysiwyg-menu.tsx
=> feat(editor-wysiwyg): show current link value in LinkInput

@remirror/core/src/extension.ts, @remirror/react/src/react-helpers.tsx
=> chore: correct typos

.changeset/ninety-shirts-pump.md, .changeset/silly-rivers-smell.md, @remirror/extension-code-block/src/__tests__/code-block.spec.ts, @remirror/extension-code-block/src/code-block-extension.ts, packages/jest-remirror/src/jest-remirror-editor.tsx, packages/jest-remirror/src/jest-remirror-types.ts, yarn.lock
Fixed #231 
Before this PR:
After this PR:
=> fix(extension-code-block): backspace with content

docs/generated/gatsby.ts, docs/package.json, docs/src/gatsby-plugin-theme-ui/components.tsx, docs/src/gatsby/node.ts, yarn.lock
=> docs: resolve broken `build:docs`

.changeset/brave-dodos-sleep.md, package.json
=> fix: remove custom browserslist configuration

.changeset/blue-dodos-vanish.md, @remirror/core-types/package.json, @remirror/editor-social/package.json, @remirror/editor-social/readme.md, @remirror/editor-social/src/components/social-editor.tsx, @remirror/editor-social/src/social-types.ts, docs/package.json, packages/prosemirror-suggest/src/suggest-types.ts, yarn.lock
=> feat(social): allow options in the matchers

.changeset/fluffy-radios-deliver.md, .changeset/seven-cooks-pretend.md, @remirror/core-extensions/src/marks/__tests__/code-extension.spec.ts, @remirror/core-extensions/src/marks/code-extension.ts, @remirror/core-utils/src/command-utils.ts, @remirror/extension-code-block/src/__tests__/code-block.spec.ts, @remirror/extension-code-block/src/code-block-extension.ts, e2e/src/wysiwyg.e2e.test.ts, examples/with-next/pages/editor/rich-social/rich.tsx
=> fix: code block and code extension issues

.changeset/tricky-squids-run.md, @remirror/core-extensions/src/marks/link-extension.ts
=> fix: don't expand link selection if selected

.changeset/moody-cameras-flow.md, @remirror/dev/package.json, yarn.lock
upgrade prosemirror-dev-tools from v2 to v3
=> chore: upgrade `prosemirror-dev-tools` to 3.0.0

@remirror/core/src/editor-wrapper.ts, @remirror/playground/package.json, @remirror/playground/scripts/import-remirror.ts, @remirror/playground/src/_remirror.tsx, @remirror/playground/src/simple-panel.tsx
- Fixes import script
- Imports latest extensions
- Sorts extensions and presets alphabetically for easier reference
=> chore(playground): update sidebar

.changeset/nice-flowers-beg.md, packages/@remirror/playground/src/_remirror.tsx, packages/@remirror/preset-table/src/__tests__/table-preset.spec.tsx, packages/@remirror/preset-table/src/table-extensions.ts, packages/@remirror/preset-table/src/table-preset.ts, packages/@remirror/preset-table/src/table-utils.ts, packages/jest-prosemirror/src/jest-prosemirror-nodes.ts
=> refactor(table): unify the names of extensions

packages/@remirror/playground/src/index.tsx, packages/@remirror/playground/src/playground.tsx, support/website/src/pages/playground.tsx
Load prettier before loading the playground.
=> Playground prettier phase

packages/@remirror/playground/src/execute.tsx, packages/@remirror/playground/src/playground.tsx, packages/@remirror/playground/src/use-remirror-playground.tsx
Fixes an issue restoring state via the playground textarea; also fixes a layout issue in playground.
=> Playground fixes

.changeset/nasty-parents-bathe.md, packages/@remirror/playground/package.json, packages/@remirror/playground/scripts/import-remirror.ts, packages/@remirror/playground/src/_remirror.tsx, packages/@remirror/playground/src/compile.tsx, packages/@remirror/playground/src/execute.tsx, packages/remirror/extension/react-component/package.json, packages/remirror/extension/react-ssr/package.json, pnpm-lock.yaml
Support custom extensions in the playground.
=> Playground support custom extensions

.changeset/poor-owls-fetch.md, packages/jest-prosemirror/environment/package.json, packages/jest-prosemirror/serializer/package.json, packages/jest-prosemirror/src/environment.ts, packages/jest-prosemirror/src/serializer.ts, packages/jest-remirror/environment/package.json, packages/jest-remirror/src/environment.ts
- Enable `jest-prosemirror/environment`
- Enable `jest-remirror/environment`
- Enable `jest-prosemirror/serializer`
Closes #338
=> fix(jest-*): environment setup

.changeset/long-apricots-cross.md, packages/@remirror/react/package.json, packages/@remirror/react/readme.md, packages/@remirror/react/renderers/package.json, packages/@remirror/react/src/index.ts, packages/remirror/readme.md
=> Fix react renderer setup

.changeset/happy-pianos-cross.md, packages/jest-remirror/package.json, packages/jest-remirror/src/__tests__/jest-remirror-builder.spec.ts, packages/jest-remirror/src/__tests__/jest-remirror-editor.spec.ts, packages/jest-remirror/src/__tests__/jest-remirror-matchers.spec.ts, packages/jest-remirror/src/jest-remirror-builder.ts, packages/jest-remirror/src/jest-remirror-editor.ts, packages/jest-remirror/src/jest-remirror-environment.ts, packages/jest-remirror/src/jest-remirror-matchers.ts, packages/jest-remirror/src/jest-remirror-ssr.tsx, packages/jest-remirror/src/jest-remirror-types.ts, packages/jest-remirror/src/jest-remirror-utils.ts, packages/jest-remirror/src/jsdom-polyfills.ts, pnpm-lock.yaml
=> chore(jest-remirror): remove `remirror` from the dependencies

.changeset/good-flies-hope.md, .changeset/tiny-bees-listen.md, packages/@remirror/core-helpers/src/core-helpers.ts, packages/@remirror/core-utils/src/__tests__/prosemirror-utils.spec.ts, packages/@remirror/core-utils/src/prosemirror-utils.ts
=> fix(core-utils): `isNodeActive` now matches partial attributes

.changeset/strange-pens-clean.md, packages/@remirror/extension-epic-mode/src/epic-mode-extension.ts
=> Remove console.log statement

.changeset/big-coats-flow.md, packages/@remirror/core/src/manager/__tests__/remirror-manager.spec.tsx, packages/@remirror/extension-auto-link/src/auto-link-extension.ts, packages/@remirror/extension-base-keymap/src/base-keymap-extension.ts, packages/@remirror/extension-blockquote/src/blockquote-extension.ts, packages/@remirror/extension-bold/src/bold-extension.ts, packages/@remirror/extension-code-block/src/code-block-extension.ts, packages/@remirror/extension-code/src/code-extension.ts, packages/@remirror/extension-emoji/src/emoji-extension.ts, packages/@remirror/extension-hard-break/src/hard-break-extension.ts, packages/@remirror/extension-heading/src/heading-extension.ts, packages/@remirror/extension-history/src/history-extension.ts, packages/@remirror/extension-horizontal-rule/src/horizontal-rule-extension.ts, packages/@remirror/extension-italic/src/italic-extension.ts, packages/@remirror/extension-link/src/link-extension.ts, packages/@remirror/extension-mention/src/mention-extension.ts, packages/@remirror/extension-search/src/search-extension.ts, packages/@remirror/extension-strike/src/strike-extension.ts, packages/@remirror/extension-underline/src/underline-extension.ts, packages/@remirror/extension-yjs/src/yjs-extension.ts, packages/@remirror/preset-list/src/bullet-list-extension.ts, packages/@remirror/preset-list/src/list-item-extension.ts, packages/@remirror/preset-list/src/ordered-list-extension.ts
I missed some methods in the previous PR #377 . This PR fix them.
=> refactor: use method signature for class overloads (part 2)

.changeset/chilled-mails-build.md, packages/@remirror/react-social/src/components/social-editor-emoji.tsx, packages/@remirror/react-social/src/components/social-editor.tsx
Also add the character count to the `Indicator` component.
Closes #403
=> feat(react-social): immediate emoji suggestions

.changeset/config.json, .changeset/eight-dots-report.md, packages/@remirror/extension-annotation/package.json, packages/@remirror/extension-annotation/readme.md, packages/@remirror/extension-annotation/src/__tests__/annotation-extension.spec.ts, packages/@remirror/extension-annotation/src/actions.ts, packages/@remirror/extension-annotation/src/annotation-extension.ts, packages/@remirror/extension-annotation/src/index.ts, packages/@remirror/extension-annotation/src/types.ts, packages/@remirror/extension-annotation/src/utils.ts, packages/remirror/extension/annotation/package.json, packages/remirror/package.json, packages/remirror/src/extension/annotation.ts, pnpm-lock.yaml
This extension allows to annotate the content in your editor
=> Extension to annotate content in your editor

support/website/src/pages/playground.tsx
=> Ensure `RemirrorPlayground` appears in search results

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, .github/labeler.yml, support/root/.vscode/extensions.json
=> Add `codespaces` support

.github/actions/pnpm/action.yml, .github/labeler.yml, .github/workflows/ci.yml, .github/workflows/docs.yml
=> Create composite `pnpm install` action

.changeset/config.json, .github/ISSUE_TEMPLATE/custom.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/PULL_REQUEST_TEMPLATE.md, .github/workflows/ci.yml, .github/workflows/netlify-deploy.yml, package.json, readme.md, support/jest/jest.framework.ts, yarn.lock
=> Create `0.x` branch

packages/@remirror/core/src/builtins/plugins-extension.ts
Updated documentation based on reading code and better understanding of the programming model.
=> Update inline documentation for `createPlugin`

.changeset/config.json
Set the base branch to the current branch name, `next`.
=> Update changeset config to point to `next`

packages/@remirror/core-helpers/src/freeze.ts
=> Fix a typo in a documentation comment

docs/guide/installation.md, packages/@remirror/styles/src/utils.ts
This PR adds a note to the installation docs about including remirror styles.
@ifiokjr Are there any examples that need to be updated?
=> Add note about including remirror styles

docs/guide/installation.md
Improve documentation a bit for @remirror/styles
- [NA] My code follows the code style of this project and `pnpm fix` completed successfully.
- [NA] New code is unit tested and all current tests pass when running `pnpm test`.
=> Make @remirror/styles install more correct

docs/guide/hello-remirror.md
- Remove TS specific code
- Ensure labels are returned for mention logic
- Ensure all React methods are imported
- Rename  ```onChange``` to ```onMentionChange```
- Remove ```console.log```
- Rename "junk" to "example"
=> Update incorrect `Hello Remirror` docs

packages/@remirror/extension-annotation/src/segments.ts
This doesn't change behaviour, but I was using the code for segments to make things more performant in #721. 
I find `reduce` quite hard to read, so I've switched it out for `for` loops.
@ronnyroeller please take a quick look and let me know if it all looks okay. Tests are passing.
=> Small refactor to the segments file

docs/concepts/extra-attributes.md, packages/@remirror/core-utils/src/core-utils.ts, packages/@remirror/core-utils/src/index.ts, packages/@remirror/core/src/builtins/schema-extension.ts, packages/@remirror/extension-auto-link/src/auto-link-extension.ts, packages/@remirror/extension-callout/src/callout-extension.ts, packages/@remirror/extension-image/src/image-extension.ts, packages/@remirror/extension-link/src/link-extension.ts, packages/@remirror/extension-mention-atom/src/mention-atom-extension.ts, packages/@remirror/preset-embed/src/iframe-extension.ts
Reverts remirror/remirror#773 which was missing a changeset and contains a fixup commit
=> Revert "Prevent raw extra attributes being rendered to the DOM"

.changeset/real-carrots-guess.md, packages/@remirror/extension-codemirror/CHANGELOG.md, packages/@remirror/extension-codemirror/package.json, packages/@remirror/extension-codemirror/readme.md, packages/@remirror/extension-codemirror/src/__tests__/__snapshots__/codemirror-extension.spec.ts.snap, packages/@remirror/extension-codemirror/src/__tests__/codemirror-extension.spec.ts, packages/@remirror/extension-codemirror/src/codemirror-extension.ts, packages/@remirror/extension-codemirror/src/codemirror-node-view.ts, packages/@remirror/extension-codemirror/src/codemirror-plugin.ts, packages/@remirror/extension-codemirror/src/codemirror-types.ts, packages/@remirror/extension-codemirror/src/codemirror-utils.ts, packages/@remirror/extension-codemirror/src/index.ts, pnpm-lock.yaml, support/root/.size-limit.json
=> Add new `@remirror/extension-codemirror` package

.changeset-early-impalas-rush.md, packages/@remirror/extension-yjs/package.json, packages/@remirror/extension-yjs/src/yjs-extension.ts, pnpm-lock.yaml
Includes fixes for scrolling while remote clients are editing and incorrect remote selections
see: https://github.com/yjs/y-prosemirror/issues/31
see: https://github.com/yjs/y-prosemirror/issues/32
=> fix: upgrade y-prosemirror

packages/remirror__react-ssr/package.json
=> chore(react-ssr): remove private package.json

packages/remirror__react-components/package.json, packages/remirror__react-renderer/package.json
=> chore: remove private from react-renderer and react-components

support/scripts/src/mutatate-packages.ts
=> chore: mutate peerDependencies when publishing PRs

package.json, pnpm-lock.yaml, support/base.babel.js
Plugin was causing issues when building for production.
Closes #866
=> build(prod): remove babel plugin

.changeset/heavy-ads-double.md, examples/storybook-react/__e2e__/tsconfig.json, examples/storybook-react/package.json, examples/storybook-react/src/codemirror5.stories.tsx, examples/storybook-react/src/tsconfig.json, package.json, packages/remirror__extension-codemirror5/__tests__/codemirror-extension.spec.ts, packages/remirror__extension-codemirror5/__tests__/codemirror-ref.spec.ts, packages/remirror__extension-codemirror5/__tests__/codemirror-utils.spec.ts, packages/remirror__extension-codemirror5/src/codemirror-utils.ts, packages/testing/package.json, pnpm-lock.yaml, support/root/jest-playwright.config.cjs, support/root/jest.config.js
@ifiokjr Here is some test cases improvement for extension-codemirror5. I haven't made the test coverage of this package a great enhancement but I would like to keep each PR small. So I think it's ready for review.
=> test(extension-codemirror5): improve test cases

.changeset/dry-ties-report.md, packages/remirror__react-renderer/__tests__/callout.spec.tsx, packages/remirror__react-renderer/src/handlers/callout.tsx, packages/remirror__react-renderer/src/handlers/index.ts, packages/remirror__react-renderer/src/renderer.tsx
Support callout nodes in react-renderer
=> feat(react-renderer): support `callout` nodes

.changeset/nine-rings-compete.md, packages/remirror__extension-react-tables/package.json, packages/remirror__extension-react-tables/src/components/table-controller-cell.ts, packages/remirror__extension-react-tables/src/components/table-insert-button-trigger.ts, packages/remirror__extension-react-tables/src/components/table-insert-button.ts, packages/remirror__extension-react-tables/src/components/table-insert-mark.ts, packages/remirror__extension-react-tables/src/utils/dom.ts, packages/remirror__extension-react-tables/src/utils/jsx.ts, packages/remirror__extension-react-tables/src/views/table-controller-cell-view.tsx, packages/remirror__extension-react-tables/src/views/table-view.tsx, pnpm-lock.yaml
This PR replaces `jsx-dom` with a forked version. 
Fixes #918
=> fix(extension-react-tables): use an earlier version of `jsx-dom`

package.json, packages/remirror__extension-text-color/__tests__/tsconfig.json, packages/remirror__extension-text-color/src/tsconfig.json, packages/storybook-react/.babelrc.js, support/root/.size-limit.json
Fixes https://github.com/remirror/remirror/issues/924
Fixes https://github.com/remirror/remirror/issues/923
=> fix(storybook-react): make storybook work again

.github/workflows/ci.yml, .github/workflows/docs.yml, .github/workflows/e2e.yml, .github/workflows/publish-pr.yml, .github/workflows/publish.yml, .github/workflows/storybook.yml, .github/workflows/version.yml, package.json
The PR creates a new CI workflow that will deploy the storybook for every pull request as well as every push in the `beta` branch. 
PR commen screenshot:
Storybook screenshot:
=> ci: deploy storybook to vercel

.github/workflows/storybook.yml, packages/storybook-react/__stories__/introduction.stories.tsx, packages/storybook-react/__stories__/tsconfig.json, packages/storybook-react/package.json, packages/storybook-react/src/storybook-react-main.ts, pnpm-lock.yaml, support/root/tsconfig.json
Stop github action from posting deployment in pull request 706.
=> feat(storybook-react): add an introduction page

.github/workflows/storybook.yml
=> ci: don't run the storybook workflow from a fork

packages/remirror/src/index.ts
=> fix: bundle SemanticVersion from json.macro

website/package.json, website/plugins/monaco-editor.js
Website builds have been failing since #951 was merged [see here](https://github.com/remirror/remirror/runs/2612116903)
This PR aims to fix the build issues, but could do with validating the fix.
=> fix(website): build errors

.changeset/fast-elephants-listen.md, packages/remirror__extension-list/src/index.ts
This PR exports two commands in `extension-list`.
=> feat(extension-list): export two commands

.changeset/sharp-snakes-peel.md, packages/remirror__extension-callout/__stories__/callout.stories.tsx, packages/remirror__extension-callout/__tests__/callout-extension.spec.ts, packages/remirror__extension-callout/src/callout-extension.ts, packages/remirror__extension-callout/src/callout-types.ts, packages/remirror__extension-callout/src/callout-utils.ts, packages/remirror__styles/all.css, packages/remirror__styles/extension-callout.css, packages/remirror__styles/src/dom.tsx, packages/remirror__styles/src/emotion.tsx, packages/remirror__styles/src/styled-components.tsx, packages/remirror__theme/src/extension-callout-theme.ts
An improvement to the previous PR #980 , improving the behavior of setting emoji.
Fixes #871
=> fix(callout-extension): improve the behavior of setting emoji

.changeset/tidy-grapes-report.md
Don't try to publish `storybook-react` since it's a private package.
=> chore: remove `storybook-react` from the changeset

.github/workflows/publish.yml
Run the publish workflow on the `main` branch instead of the `next` branch.
=> ci: fix the publish workflow

docs/introduction.md, readme.md
Update the readme to be less wishy-washy.
=> docs: simplify readme

.github/workflows/pr-name-linter.yml
Fixes the following error when running `pr-name-linter`
```
Run JulienKode/pull-request-name-linter-action@v0.2.0
Error: RangeError: Found invalid rule names: subject-exclamation-mark. Supported rule names are: body-case, body-empty, body-leading-blank, body-max-length, body-max-line-length, body-min-length, footer-empty, footer-leading-blank, footer-max-length, footer-max-line-length, footer-min-length, header-case, header-full-stop, header-max-length, header-min-length, references-empty, scope-case, scope-empty, scope-enum, scope-max-length, scope-min-length, signed-off-by, subject-case, subject-empty, subject-full-stop, subject-max-length, subject-min-length, type-case, type-empty, type-enum, type-max-length, type-min-length
Error: Found invalid rule names: subject-exclamation-mark. …
```
=> ci: fix pr-name-linter

package.json
This could cause some workflow issues if we recreate the lockfile
=> ci: keep the lockfile in the changeset workflow

.github/workflows/version.yml
=> ci: make the changeset pr to run the workflow

package.json
=> ci: try not to update lockfile in a changeset pr

package.json
=> ci: update the lockfile correctly in a changeset pr

packages/remirror__extension-annotation/__stories__/tsconfig.json, packages/remirror__extension-callout/__stories__/tsconfig.json, packages/remirror__extension-codemirror5/__stories__/tsconfig.json, packages/remirror__extension-embed/__stories__/tsconfig.json, packages/remirror__extension-image/__stories__/tsconfig.json, packages/remirror__extension-link/__stories__/tsconfig.json, packages/remirror__extension-list/__stories__/tsconfig.json, packages/remirror__extension-positioner/__stories__/tsconfig.json, packages/remirror__extension-react-tables/__stories__/react-tables-extension.stories.tsx, packages/remirror__extension-react-tables/__stories__/tsconfig.json, packages/remirror__extension-tables/__stories__/tsconfig.json, packages/remirror__react-components/__stories__/tsconfig.json, packages/remirror__react/__stories__/tsconfig.json, packages/storybook-react/__stories__/tsconfig.json, pnpm-lock.yaml
=> chore: update types to reduce changeset errors

.changeset/violet-kangaroos-watch.md, packages/remirror__extension-list/src/list-item-extension.ts, packages/remirror__extension-list/src/list-item-node-view.ts, packages/remirror__extension-list/src/task-list-item-extension.ts
Fixes #1017
https://user-images.githubusercontent.com/24715727/126678591-eddd70db-d11a-4aed-9f24-611e399a98e2.mp4
=> fix(extension-list): fix CJK IME in the list

.github/workflows/version.yml
Fixes https://github.com/remirror/remirror/pull/1033/checks?check_run_id=3237593759#step:2:12
=> ci: don't run the version workflow in a forked repo

.github/funding.yml
Just to re-format this file so that GitHub will read this file again.
=> chore: update funding.yml

docs/extensions/annotation-extension.md
=> docs: add annotation extension

packages/remirror__extension-placeholder/__stories__/placeholder-extension.stories.tsx, packages/remirror__i18n/src/en/messages.po, packages/remirror__i18n/src/en/messages.ts
=> chore: run `pnpm fix`

.github/workflows/version.yml
Turn out that you can't use `secrets` in `if`.
=> ci: fix the workflow `version`

.changeset/tidy-deers-nail.md
=> chore: add changeset for remirror

support/scripts/src/helpers.ts
When using node12, `fs/promises` is not available.
https://github.com/remirror/remirror/blob/79a5cb55b2e9c3db10b137d1e2235df724291d52/support/actions/pr/action.yml#L14
Fix this [error](https://github.com/remirror/remirror/runs/3278473422?check_suite_focus=true):
```
Error: Cannot find module 'fs/promises'
Require stack:
- /home/runner/work/remirror/remirror/support/scripts/dist/helpers-cf8c0de6.cjs.dev.js
- /home/runner/work/remirror/remirror/support/scripts/dist/scripts.cjs.dev.js
- /home/runner/work/remirror/remirror/support/scripts/dist/scripts.cjs.js
- /home/runner/work/remirror/remirror/support/actions/pr/dist/actions-pr.cjs.dev.js
- /home/runner/work/remirror/remirror/support/actions/pr/dist/actions-pr.cjs.js
at Function.Module._resolveFilename …
```
=> ci: fix `publish_comment`

.changeset/calm-hairs-clap.md, packages/remirror__extension-file/src/index.ts
=> fix(extension-file): export `FileAttributes`

.changeset/bright-dodos-beg.md, packages/remirror__extension-file/src/file-extension.tsx
=> fix(extension-file): make `FileExtension` selectable by default

.changeset/two-mangos-pay.md, packages/remirror__extension-code-block/__stories__/code-block.stories.tsx, packages/remirror__extension-code-block/__stories__/tsconfig.json, packages/remirror__extension-code-block/src/code-block-utils.ts, support/root/tsconfig.json
Fix a crash when the code block node contains an invalid language name.
=> fix(extension-code-block): set fallback language

.changeset/nasty-mice-accept.md
Add changesets for https://github.com/remirror/remirror/pull/1055
=> chore: add changesets

packages/remirror__extension-annotation/__stories__/annotation-extension.stories.tsx
The story for annotation missed the standard design. Applying it makes it more beautiful.
=> docs: apply standard design to annotation storybook

packages/remirror__react-renderer/__stories__/react-renderer.stories.tsx, packages/remirror__react-renderer/__stories__/sample-doc.ts, packages/remirror__react-renderer/__stories__/tsconfig.json, support/root/tsconfig.json
Adding a sample for react-renderer to storybook.
=> docs: add storybook for react-renderer (static HTML)

docs/react/static-html.md, packages/remirror__react-renderer/__stories__/tsconfig.json, website/sidebar.js
=> docs: explain how to render document to static HTML

packages/remirror__extension-annotation/__stories__/tsconfig.json, packages/remirror__extension-callout/__stories__/tsconfig.json, packages/remirror__extension-code-block/__stories__/tsconfig.json, packages/remirror__extension-codemirror5/__stories__/tsconfig.json, packages/remirror__extension-embed/__stories__/tsconfig.json, packages/remirror__extension-file/__stories__/tsconfig.json, packages/remirror__extension-image/__stories__/tsconfig.json, packages/remirror__extension-link/__stories__/tsconfig.json, packages/remirror__extension-list/__stories__/tsconfig.json, packages/remirror__extension-placeholder/__stories__/tsconfig.json, packages/remirror__extension-positioner/__stories__/tsconfig.json, packages/remirror__extension-react-tables/__stories__/tsconfig.json, packages/remirror__extension-tables/__stories__/tsconfig.json, packages/remirror__react-components/__stories__/tsconfig.json, packages/remirror__react-renderer/__stories__/tsconfig.json, packages/remirror__react/__stories__/tsconfig.json, packages/storybook-react/__stories__/tsconfig.json, packages/storybook-react/manager-head.html, packages/storybook-react/manager.js, packages/storybook-react/package.json, packages/storybook-react/remirror-theme.js, packages/storybook-react/src/storybook-react-main.ts, pnpm-lock.yaml
- Show source code with stories
- Align storybook design with remirror design
=> docs: improve storybook

readme.md
=> docs: add a missing statement in the readme's code sample

docs/extensions/node-formatting-extension.md
=> docs: add explanation for node formatting extension

docs/extensions/embed-extension.md, packages/remirror__extension-embed/__stories__/iframe.stories.tsx
=> docs: explain usage of EmbedExtension

docs/extensions/link-extension.md, packages/remirror__extension-link/__stories__/floating-link-toolbar.tsx, packages/remirror__extension-link/__stories__/link-extension.stories.tsx
=> docs: explain usage of LinkExtension

.changeset/empty-wasps-guess.md
=> chore: release `@remirror/extension-node-formatting`

.github/workflows/publish.yml
Automatically create a github release after releasing `remirror`.
=> ci: create release

.changeset/itchy-rules-fix.md, packages/remirror__pm/package.json, pnpm-lock.yaml
=> fix(pm): update dependencies

.github/workflows/publish.yml
`softprops/action-gh-release@v1` will append the body when updating release https://github.com/softprops/action-gh-release/issues/57
=> ci: update release action

docs/extensions/bold-extension.md, docs/extensions/italic-extension.md, docs/extensions/strike-extension.md, docs/extensions/underline-extension.md, packages/remirror__extension-bold/__stories__/bold.stories.tsx, packages/remirror__extension-bold/__stories__/styles.css, packages/remirror__extension-bold/__stories__/tsconfig.json, packages/remirror__extension-italic/__stories__/italic.stories.tsx, packages/remirror__extension-italic/__stories__/styles.css, packages/remirror__extension-italic/__stories__/tsconfig.json, packages/remirror__extension-strike/__stories__/strike.stories.tsx, packages/remirror__extension-strike/__stories__/styles.css, packages/remirror__extension-strike/__stories__/tsconfig.json, packages/remirror__extension-underline/__stories__/styles.css, packages/remirror__extension-underline/__stories__/tsconfig.json, packages/remirror__extension-underline/__stories__/underline.stories.tsx, support/root/tsconfig.json
Docs for bold, italic, strike, and underline extension
=> docs: basic extensions

.github/workflows/docs.yml, .github/workflows/storybook.yml, docs/contributing.md, support/lfs-hooks/post-checkout, support/lfs-hooks/post-commit, support/lfs-hooks/post-merge, support/lfs-hooks/pre-push, support/root/.huskyrc
=> chore: remove git-lfs

docs/extensions/blockquote-extension.md, docs/extensions/bold-extension.md, docs/extensions/code-extension.md, docs/extensions/italic-extension.md, docs/extensions/placeholder-extension.md, docs/extensions/strike-extension.md, docs/extensions/text-color-extension.md, docs/extensions/underline-extension.md, packages/remirror__extension-blockquote/__stories__/blockquote.stories.tsx, packages/remirror__extension-blockquote/__stories__/styles.css, packages/remirror__extension-blockquote/__stories__/tsconfig.json, packages/remirror__extension-code/__stories__/code.stories.tsx, packages/remirror__extension-code/__stories__/styles.css, packages/remirror__extension-code/__stories__/tsconfig.json, packages/remirror__extension-text-color/__stories__/text-color.stories.tsx, packages/remirror__extension-text-color/__stories__/tsconfig.json, support/root/tsconfig.json
=> docs: explain further extensions

packages/remirror__react/__stories__/controlled.stories.tsx
=> docs: describe how to replace editor content

.changeset/friendly-spies-peel.md, packages/remirror/package.json, support/scripts/src/generate-configs.ts
=> fix(remirror): export `remirror/styles`

.changeset/fifty-weeks-visit.md
=> chore: improve changeset message

docs/hooks/use-mention.md, packages/remirror__react-hooks/__stories__/use-mention-atom-styles.css, packages/remirror__react-hooks/__stories__/use-mention.stories.tsx
=> docs: explain usage of use-mention hook

packages/remirror__extension-file/__stories__/file.stories.tsx, packages/remirror__extension-file/src/file-extension.tsx, packages/remirror__extension-file/src/file-uploaders/slow-file-uploader.ts
=> docs: improve file-extension code docs

packages/remirror__extension-text-case/src/text-case-utils.ts
=> docs: make documented default value match code

docs/extensions/font-family-extension.md, docs/extensions/font-size-extension.md, docs/extensions/sub-extension.md, docs/extensions/sup-extension.md, docs/extensions/text-case-extension.md, packages/remirror__extension-code-block/__stories__/code-block.stories.tsx, packages/remirror__extension-font-family/__stories__/font-family.stories.tsx, packages/remirror__extension-font-family/__stories__/tsconfig.json, packages/remirror__extension-font-family/src/font-family-extension.ts, packages/remirror__extension-font-size/__stories__/font-size.stories.tsx, packages/remirror__extension-font-size/__stories__/tsconfig.json, packages/remirror__extension-node-formatting/__stories__/node-formatting.stories.tsx, packages/remirror__extension-react-tables/__stories__/react-tables-extension.stories.tsx, packages/remirror__extension-sub/__stories__/sub.stories.tsx, packages/remirror__extension-sub/__stories__/tsconfig.json, packages/remirror__extension-sup/__stories__/sup.stories.tsx, packages/remirror__extension-sup/__stories__/tsconfig.json, packages/remirror__extension-text-case/__stories__/text-case.stories.tsx, packages/remirror__extension-text-case/__stories__/tsconfig.json, support/root/tsconfig.json
=> docs: explain extensions

docs/extensions/index.md, docs/getting-started/commands-and-helpers.md, docs/getting-started/create-editor.md, docs/getting-started/create-manager.md, docs/installation.md, docs/introduction.md, docs/react/controlled.md, packages/remirror__extension-embed/src/iframe-extension.ts, readme.md, support/root/.eslintrc.js, website/sidebar.js
Adds a basic "getting started" section to the Docusauras website.
=> docs: add getting started docs

pnpm-workspace.yaml, support/scripts/src/generate-configs.ts
=> chore: small config update

docs/concepts/extension.md, docs/extensions/file-extension.md, docs/extensions/index.md, docs/extensions/sub-extension.md, docs/extensions/sup-extension.md, packages/storybook-react/stories/extension-blockquote/blockquote.stories.tsx, packages/storybook-react/stories/extension-bold/bold.stories.tsx, packages/storybook-react/stories/extension-callout/callout.stories.tsx, packages/storybook-react/stories/extension-code/code.stories.tsx, packages/storybook-react/stories/extension-columns/columns.stories.tsx, packages/storybook-react/stories/extension-epic-mode/epic-mode.stories.tsx, packages/storybook-react/stories/extension-font-family/font-family.stories.tsx, packages/storybook-react/stories/extension-font-size/font-size.stories.tsx, packages/storybook-react/stories/extension-hard-break/hard-break.stories.tsx, packages/storybook-react/stories/extension-heading/heading.stories.tsx, packages/storybook-react/stories/extension-horizontal-rule/horizontal-rule.stories.tsx, packages/storybook-react/stories/extension-image/image.stories.tsx, packages/storybook-react/stories/extension-italic/italic.stories.tsx, packages/storybook-react/stories/extension-node-formatting/node-formatting.stories.tsx, packages/storybook-react/stories/extension-positioner/positioner-extension.stories.tsx, packages/storybook-react/stories/extension-strike/strike.stories.tsx, packages/storybook-react/stories/extension-sub/sub.stories.tsx, packages/storybook-react/stories/extension-sup/sup.stories.tsx, packages/storybook-react/stories/extension-text-case/text-case.stories.tsx, packages/storybook-react/stories/extension-text-color/text-color.stories.tsx, packages/storybook-react/stories/extension-text-highlight/text-highlight.stories.tsx, packages/storybook-react/stories/extension-underline/underline.stories.tsx, website/styles.css
Updates the Storybook examples to be uncontrolled editors, which is the recommended approach.
Highlights that the File extension is in beta,
=> docs: documentation updates

website/blog/2021-02-06-decouple-render.md, website/blog/2021-05-20-community-challenge.md, website/blog/2021-08-07-serverless-yjs.md
This simplifies finding these remirror articles.
=> docs: import existing blog articles

packages/remirror__extension-list/src/task-list-extension.ts, packages/remirror__i18n/src/en/messages.ts, packages/remirror__messages/src/extension-list-messages.ts
=> fix: set correct label and icon for task list

.github/funding.yml
github said `Some errors were encountered when parsing the FUNDING.yml`. Edit this file so that github will re-parse it.
=> chore: update github sponsor config

.changeset/great-frogs-move.md, .changeset/thirty-owls-pull.md, packages/remirror__extension-list/__tests__/list-commands.spec.ts, packages/remirror__extension-list/src/list-commands.ts, packages/remirror__styles/all.css, packages/remirror__styles/extension-list.css, packages/remirror__styles/src/dom.tsx, packages/remirror__styles/src/emotion.tsx, packages/remirror__styles/src/styled-components.tsx, packages/remirror__theme/src/extension-list-theme.ts, packages/storybook-react/stories/extension-list/list-extension.stories.tsx
=> fix(extension-list): toggle task lists to bullet lists and vice versa

.changeset/friendly-worms-sparkle.md, packages/remirror__core/package.json, packages/remirror__core/src/framework/framework.ts, pnpm-lock.yaml
=> fix(core): decouple core and theme

docs/introduction.md
By now, the document has the basic content. We can therefore put the "Improvement" section from the most prominent to a bit less prominent position.
=> docs: defocus improvement suggestions section

website/blog/2021-08-27-showcase-next.md
=> docs: add blog post about user showcase

website/src/pages/index.tsx
=> fix: typos on homepage

packages/remirror__preset-wysiwyg/__tests__/tsconfig.json, packages/remirror__preset-wysiwyg/package.json, packages/remirror__preset-wysiwyg/src/tsconfig.json, packages/remirror__preset-wysiwyg/src/wysiwyg-preset.ts, packages/remirror__react-editors/src/components/top-toolbar.tsx, packages/remirror__react-editors/src/social/social-editor.tsx, packages/remirror__react-editors/src/wysiwyg/wysiwyg-editor.tsx, pnpm-lock.yaml, support/root/.size-limit.json
Upgrade to react-tables and expose via toolbar
=> feat: use modern tables for pre-packaged editors

packages/storybook-react/stories/extension-react-tables/react-tables-extension.stories.tsx
=> fix: storybook exposed a non-functioning story

packages/remirror__extension-react-tables/src/components/table-cell-menu.tsx
Table components are now shown as part of the SocialEditor. It's therefore important that they fit better the remirror look & feel.
=> feat: improve design of default table components

.changeset/heavy-books-argue.md, packages/remirror__extension-list/src/task-list-item-extension.ts
https://user-images.githubusercontent.com/24715727/131687366-590e51e6-5267-41b8-af2a-da204b8f20d1.mov
=> fix(extension-list): fix click checkbox

.changeset/rare-starfishes-behave.md, packages/remirror__react-hooks/src/use-menu-navigation.ts
=> fix(react-hooks): fix an out of range error 

packages/jest-prosemirror/src/jest-prosemirror-events.ts, packages/jest-prosemirror/src/jest-prosemirror-matchers.ts, packages/remirror__core-utils/src/core-utils.ts, packages/remirror__extension-doc/src/doc-extension.ts, packages/remirror__extension-file/src/file-uploaders/bashupload-file-uploader.ts, pnpm-lock.yaml, support/actions/src/pr.ts, support/scripts/src/check-styles.ts, support/scripts/src/deprecate-version.ts, support/scripts/src/generate-api.ts, support/scripts/src/generate-configs.ts, support/scripts/src/read-config.ts, website/package.json
=> chore: prepare for the upcoming dependency upgrade

.github/workflows/label-sponsors.yml
=> chore: allow the label_sponsors workflow to fail

packages/remirror__styles/all.css, packages/remirror__styles/components.css, packages/remirror__styles/src/dom.tsx, packages/remirror__styles/src/emotion.tsx, packages/remirror__styles/src/styled-components.tsx, packages/remirror__theme/src/components-theme.ts, website/src/pages/index.tsx, website/src/pages/styles.module.css
This gives new users a first taste what remirror is about.
=> docs: add sample editor to homepage

packages/storybook-react/stories/react-hooks/use-mention.stories.tsx
This was asked from https://github.com/remirror/remirror/discussions/1218
https://user-images.githubusercontent.com/24715727/132313917-1de8b1e2-2c5f-4258-84ac-0bcbed23a679.mov
=> docs: add a story about how to use mention with Chinese characters

package.json, pnpm-lock.yaml, support/root/.eslintrc.js
=> chore: remove @kyleshevlin/eslint-plugin

packages/storybook-react/stories/extension-blockquote/blockquote.stories.tsx, packages/storybook-react/stories/extension-bold/bold.stories.tsx
=> docs: fix storybook

docs/extensions/image-extension.mdx, packages/storybook-react/stories/extension-blockquote/blockquote.stories.tsx, packages/storybook-react/stories/extension-bold/bold.stories.tsx
=> docs: add resizable image example

docs/extensions/embed-extension.mdx, packages/storybook-react/stories/extension-embed/iframe.stories.tsx, packages/storybook-react/stories/extension-embed/resizable.tsx, packages/storybook-react/stories/extension-embed/youtube.tsx, website/extension-examples/extension-embed/resizable.tsx, website/extension-examples/extension-embed/youtube.tsx
=> docs: embed resizable iframe and youtube example

.changeset/beige-cows-call.md, packages/remirror__extension-link/src/link-extension.ts, packages/remirror__extension-list/__tests__/list-commands.spec.ts, packages/remirror__extension-list/src/list-commands.ts
=> fix(extension-list): fix a RangeError when calling list commands 

.changeset/giant-hounds-watch.md, packages/remirror__core/src/builtins/schema-extension.ts
=> fix: improve performance for dynamic attributes

packages/remirror/readme.md
=> docs: fix typo in code example

docs/extensions/embed-extension.mdx
=> docs: fix embed-extension.mdx

docs/extensions/yjs-extension.mdx, packages/storybook-react/package.json, packages/storybook-react/stories/extension-yjs/basic.tsx, packages/storybook-react/stories/extension-yjs/yjs.stories.tsx, pnpm-lock.yaml, website/extension-examples/extension-yjs/basic.tsx
=> docs: add code sample for collaborative editing

packages/storybook-react/package.json, packages/storybook-react/stories/extension-positioner/positioner-extension.stories.tsx, packages/storybook-react/stories/extension-positioner/positioners.tsx, packages/storybook-react/stories/extension-positioner/styles.css, pnpm-lock.yaml, website/extension-examples/extension-positioner/positioners.tsx
Add demo for positioners
Code provided by @whawker
=> docs: add storybook for positioners

packages/storybook-react/stories/react/replace-content-and-clear-history.tsx
=> docs: standardize position of buttons

.github/workflows/docs.yml, packages/remirror__dev/src/dev.ts, support/scripts/src/generate-api.ts
=> docs: embed api documents for most packages

docs/extensions/code-block-extension.mdx, packages/storybook-react/stories/extension-code-block/basic.tsx
=> docs: improve docs for CodeBlockExtension

docs/extensions/code-block-extension.mdx
=> docs: format info block as such

.changeset/mean-fans-grin.md
Add missing changeset for #1157
=> chore: add changeset for #1157

.github/workflows/docs.yml
The build time of Docusaurus drop from ___14m31s___ to ___8m21s___ after adding cache.
=> chore: setup docusaurus caching

.changeset/three-poets-hunt.md, docs/errors.md, packages/remirror__core-constants/src/error-constants.ts, packages/remirror__core-helpers/__tests__/__snapshots__/core-errors.spec.ts.snap, packages/remirror__core-helpers/__tests__/core-errors.spec.ts, packages/remirror__core-helpers/src/core-errors.ts, packages/remirror__extension-embed/package.json, support/root/.size-limit.json
Deprecated RMR0000
Closed #1260
=> fix: stop hiding error details in production

docs/5-min-tutorial.md, website/sidebar.js
=> docs: explain how to embed SocialEditor in CRA

website/blog/2021-10-05-maintainers.md
=> docs: add blog post about new maintainers

.github/workflows/ci.yml
=> ci: use the latest 16.x Node.js

.changeset/neat-pots-design.md, packages/remirror__extension-react-component/src/node-view-types.ts, packages/remirror__extension-react-component/src/react-component-extension.ts, packages/remirror__extension-react-component/src/react-node-view.tsx
*Credit: This PR is heavily inspired by TipTap.*
=> feat(extension-react-component): implement the `stopEvent` method in `ReactNodeView`

.changeset/afraid-humans-smoke.md, packages/remirror__extension-list/src/list-command-indent.ts
=> fix(extension-list): fix an error when indenting the list

.changeset/new-roses-wait.md
Force create new releases after fixing the shortcuts-extension build.
=> fix: create new releases

.changeset/friendly-gorillas-roll.md, packages/remirror__core/src/builtins/upload-extension/file-placeholder-plugin.ts
=> fix(core): try to find the placeholder position by searching the document

.changeset/lovely-rabbits-smoke.md, packages/docusaurus-plugin-examples/package.json, packages/jest-prosemirror/package.json, packages/remirror/package.json, packages/remirror__extension-code-block/package.json, packages/remirror__i18n/package.json, packages/remirror__icons/package.json, packages/remirror__pm/package.json, packages/remirror__react-components/package.json, packages/remirror__react-editors/package.json, packages/remirror__react-hooks/package.json, packages/testing/package.json, support/scripts/src/generate-configs.ts
=> fix(scripts): fix browser exports paths

docs/react/controlled.md
- fix missing variable in code example
- fix error: cannot assign return value of `applyTransaction()` to `nextState`
=> docs: fix react controlled code example

.changeset/dry-worms-tan.md, packages/remirror__extension-image/src/image-extension.ts
=> fix(extension-image): restore image dimensions correctly

docs/extensions/positioner-extension.mdx, website/blog/2021-11-24-positioner-performance.md
Add blog post on performance issues with positioners
=> docs: add blog post on positioner performance

docs/extensions/annotation-extension.mdx
=> docs: explain better implementation of annotations

.github/workflows/pr-name-linter.yml
=> ci: fix the workflow pr-name-linter

docs/extensions/doc-extension.mdx, docs/extensions/font-size-extension.mdx
=> docs: add DocExtension documentation

.github/workflows/ci.yml, .github/workflows/version.yml
=> ci: increase timeout minutes

docs/faq.md, packages/remirror__core-utils/src/core-utils.ts
=> docs: correct examples for `htmlToProsemirrorNode` and `prosemirrorNodeToHtml`

docs/react/refs.md
=> docs: correct a duplicate import

.changeset/polite-spoons-stare.md, packages/remirror__extension-shortcuts/src/shortcuts-extension.ts
Allow to replace `<->` with a more pretty left/right arrow
=> feat: support shortcut for left/right arrows

packages/remirror__react-core/src/react-types.ts
Fix typo in example code.
- ~[ ] My code follows the code style of this project and `pnpm fix` completed successfully.~ (typo)
=> docs: fix the example code to actually "make sense"

tsconfig.docs.json, typedoc.json
Remove two symbolic links that point to bad locations. 
Thank @ankon for pointing it out.
=> chore: remove two useless symbolic links

.changeset/seven-steaks-obey.md, packages/remirror__extension-codemirror6/src/codemirror-extension.ts
=> fix(extension-codemirror6): fix an input rule error

packages/storybook-react/stories/extension-codemirror6/basic.tsx, packages/storybook-react/stories/extension-codemirror6/codemirror6.stories.tsx, packages/storybook-react/stories/extension-codemirror6/styles.css
=> docs: fix the css style of CodeMirrorExtension docs

.changeset/nice-coats-learn.md, packages/remirror__extension-list/src/list-item-node-view.ts
https://user-images.githubusercontent.com/24715727/149660712-8dff0039-e814-4227-9b16-c9c88880802b.mp4
=> fix(extension-list): increase the clickable area of checkboxes

packages/remirror__extension-markdown/readme.md
Import should be from `remirror/extensions` - not `remirror/extension`
=> docs: correct typo in code block

packages/remirror__react-components/src/components/emoji-popup-component.tsx
* Display EmojiPopupComponent in front of editor
* Fix styling of EmojiPopupComponent
Closes: #1467
_Couldn't get the rest to work._
Before:
After:
=> fix(react-components): fix styling of EmojiPopupComponent

packages/remirror__extension-yjs/src/yjs-extension.ts
Found while reading the code: The `onView` handler should return a `Dispose` function to undo added handlers etc, but the yjs extension didn't do that. This is probably a fairly theoretical case, but it could lead to the extension getting notified about changes in the document happening after the view of the extension was removed.
=> fix: remove the `update` handler from the doc in a "Dispose" step

packages/remirror__extension-annotation/src/annotation-plugin.ts
When an action is given we anyways refresh the cached annotations from the
backing store, so there is no point to first map all of them through the transform.
Note that actions are actually rare, so in absolute numbers this likely doesn't "speed up" things.
=> fix: avoid double processing of annotations

.changeset/serious-baboons-hear.md, packages/remirror__extension-annotation/src/annotation-store.ts
=> fix: replace "assert" with defensive "if"

docs/getting-started/commands-and-helpers.md, docs/getting-started/custom-extension.md, website/sidebar.js
This was asked a couple of times in Discord.
=> docs: add tutorial to create custom extension

.changeset/sweet-teachers-serve.md, packages/remirror__extension-markdown/package.json, packages/remirror__extension-markdown/src/markdown-to-html.ts, pnpm-lock.yaml
Supersedes #1508 
Updates `marked` to resolve the security alert.
=> chore(deps): update dependency marked to v4 [security]

.changeset/brave-wasps-knock.md, packages/remirror__core-utils/src/core-utils.ts, packages/remirror__extension-link/src/link-extension.ts
=> fix(extension-link): fix auto links and undo

.changeset/honest-oranges-end.md, .changeset/proud-boats-walk.md, packages/prosemirror-paste-rules/__tests__/paste-rules-plugin.spec.ts, packages/prosemirror-paste-rules/src/paste-rules-plugin.ts
- Close #1531 
- Close #1533
https://user-images.githubusercontent.com/24715727/155730264-8093fb06-9b1e-441b-9b22-020dce5ddd2e.mp4
https://user-images.githubusercontent.com/24715727/155754695-ea4871e1-47b9-46d8-bbef-b1b1df194ee1.mp4
=> fix(prosemirror-paste-rules): remove duplicate marks

.changeset/chilled-feet-agree.md, packages/remirror__extension-list/src/bullet-list-extension.ts
https://user-images.githubusercontent.com/24715727/156362771-34bb111b-a351-4628-be06-3c8484afde29.mp4
=> fix(extension-list): fix an error when clicking the list spine

.changeset/shy-fireants-argue.md, packages/remirror__core/src/framework/base-framework.ts, packages/remirror__dom/src/dom-framework.ts, packages/remirror__react-core/src/react-framework.tsx
=> fix: fix canceled transaction

.changeset/green-worms-tease.md, packages/prosemirror-suggest/src/suggest-state.ts
Check the changeset file for details.
=> fix(prosemirror-suggest): update reasons after appended transaction

packages/storybook-react/stories/react-components/emoji-popup.stories.tsx
Storybook fix only. Fix emoji popup rendering underneath editor
=> fix(storybook): fix emoji popup rendering underneath editor

packages/storybook-react/stories/extension-link/edit-dialog.tsx
`autoFocus` within a floating wrapper appears to cause a page scroll, add workaround
=> docs: fix the edit link example jumping page scroll. Fixes #1571

.changeset/thin-impalas-yell.md, packages/remirror__dev/__tests__/dev.spec.tsx, packages/remirror__dev/package.json, packages/remirror__dev/readme.md, packages/remirror__dev/src/dev.ts, pnpm-lock.yaml
Replace [prosemirror-dev-tools](https://github.com/d4rkr00t/prosemirror-dev-tools) with [prosemirror-dev-toolkit](https://github.com/TeemuKoivisto/prosemirror-dev-toolkit), which is a fork of the former but has fewer dependencies and better support for positions
Thank @TeemuKoivisto for maintaining prosemirror-dev-toolkit.
=> feat(dev): replace the underlying component with prosemirror-dev-toolkit

.changeset/polite-tips-double.md, packages/remirror__extension-emoji/__tests__/emoji-extension.spec.ts, packages/remirror__extension-emoji/src/emoji-extension.ts
=> fix(emoji): insert emoticons on Enter keypress

docs/getting-started/create-manager.md
=> chore(docs): fix some typos

readme.md
Update README to remove mentions of "multi framework" and update examples.
=> chore(docs): update README

.github/workflows/ci.yml, .github/workflows/publish.yml, .github/workflows/version.yml
=> chore: prepare ci pipelines for v2 beta

.changeset/hungry-rabbits-repair.md
Try to resolve the "body is too long" error when Changeset try to create a
pull request via GitHub API.
=> chore: reduce changeset text

website/blog/2022-05-13-annotation-issues.md
=> docs: publish best practice blog post on annotations

.github/workflows/docs.yml
**N.B.** Merges to `v1-hotfix` **_NOT_** `main`
=> chore: publish docs from v1

.github/workflows/publish.yml
**N.B.** merges to `v1-hotfix` **_NOT_** `main`
Enable publishing of v1 releases from `v1-hotfix` branch
=> chore: enable publishing from v1-hotfix branch

.changeset/odd-hotels-drop.md
Previous release didn't work. Retrying
=> chore: retry changeset

.changeset/config.json, .github/workflows/publish.yml, .github/workflows/version.yml
=> chore(ci): run the publish workflow for v1

.github/workflows/publish-v1.yml
=> chore(ci): set a seperate publish workflow for v1

.gitignore
Push some code to `v1-hotfix` to tigger the CI workflow.
=> chore: trigger ci workflows

.changeset/config.json
=> chore: change the changeset base branch for v1-hotfix

.github/workflows/publish-v1.yml
=> chore(ci): skip if-publishable in publish-v1

.github/workflows/docs.yml
=> chore(ci): use branch name as netlify alias

.changeset/clean-ghosts-retire.md, .changeset/proud-shrimps-collect.md, packages/jest-prosemirror/package.json, packages/remirror__pm/package.json, pnpm-lock.yaml
V1 Hotfix
Related to #1706 and #1677
=> fix(jest-prosemirror): fix version of prosemirror-test-builder

.github/workflows/docs.yml, .github/workflows/publish-v1.yml, .github/workflows/storybook.yml, .github/workflows/version.yml
=> chore(ci): rename v1-hotfix to v1

.changeset/few-numbers-remain.md, packages/jest-remirror/__tests__/jest-remirror-matchers.spec.ts, packages/jest-remirror/src/jest-remirror-editor.ts, packages/jest-remirror/src/jest-remirror-matchers.ts, packages/jest-remirror/src/jest-remirror-utils.ts
check the Changset file in this pr for details
=> feat(jest-remirror): add new matcher `toEqualRemirrorState`

.changeset/clever-penguins-attend.md, packages/jest-remirror/src/jest-remirror-matchers.ts
=> fix(jest-remirror): correct diff message

.changeset/fair-apes-search.md, packages/remirror__extension-codemirror6/package.json, packages/remirror__extension-codemirror6/src/index.ts, packages/storybook-react/package.json, pnpm-lock.yaml
=> chore(deps): update codemirror to v6

.changeset/tough-cherries-battle.md, packages/remirror__core-utils/__tests__/core-utils.ssr.spec.ts, packages/remirror__core-utils/src/core-utils.ts
=> fix(core): try to require JSDOM implicitly in node environment

docs/extensions/gap-cursor-extension.mdx, packages/storybook-react/stories/extension-gap-cursor/basic.tsx, packages/storybook-react/stories/extension-gap-cursor/gap-cursor.stories.tsx, packages/storybook-react/stories/extension-gap-cursor/styles.css, website/extension-examples/extension-gap-cursor/basic.tsx
Adds a storybook and explain better how the gap cursor works.
=> docs: improve documentation for the gap cursor

.github/workflows/docs.yml, packages/remirror__extension-file/src/file-extension.tsx
=> docs: debug docs

.changeset/selfish-pigs-complain.md, packages/remirror__extension-link/__tests__/link-extension.spec.ts, packages/remirror__extension-link/src/link-extension.ts
=> fix(link): delay trigger of onUpdateLink event to prevent stale state updates

.github/workflows/docs.yml, docs/extensions/search-extension.mdx, packages/storybook-react/stories/extension-search/basic.tsx, packages/storybook-react/stories/extension-search/search.stories.tsx, packages/storybook-react/stories/extension-search/styles.css, website/extension-examples/extension-search/basic.tsx
Add an example for `SearchExtension`. 
https://user-images.githubusercontent.com/24715727/177929855-b9416756-71dd-4e45-b718-6255270a9871.mp4
=> docs(extension-search): add a live example for SearchExtension

.changeset/fast-lions-sing.md, packages/jest-prosemirror/package.json, packages/prosemirror-paste-rules/package.json, packages/prosemirror-resizable-view/package.json, packages/prosemirror-suggest/package.json, packages/prosemirror-trailing-node/package.json, packages/remirror__dev/package.json, packages/remirror__pm/package.json, packages/remirror__pm/src/tables.ts, pnpm-lock.yaml
=> chore(deps): update prosemirror packages

packages/remirror__cli/src/logger.ts, packages/remirror__cli/src/utils/colors.ts, support/actions/pr/pr-utils.mjs
=> chore: add colors to remirror-cli's output

docs/contributing.md, support/actions/pnpm/action.yml
use [`corepack`](https://github.com/nodejs/corepack) to manage the `pnpm` so that we can use a fixed version of pnpm.
=> chore: use corepack to install pnpm

website/docusaurus.config.cjs
=> docs: setup algolia

.changeset/shaggy-feet-fix.md, packages/remirror__core-utils/src/core-utils.ts
=> fix(core-utils): improve changed ranges by utilising mapping

docs/contributing.md
=> docs: update contributing.md

packages/storybook-react/package.json, packages/storybook-react/stories/extension-link/link-extension.stories.tsx, packages/storybook-react/stories/extension-link/linkify-js.tsx, packages/storybook-react/stories/extension-link/linkify.tsx, pnpm-lock.yaml, website/extension-examples/extension-link/linkify.tsx
Adding a link ext example using linkify
=> docs: add linkify example

.github/workflows/docs.yml, .github/workflows/storybook.yml
Migrate the production website source from `v1` branch to `main` branch.
See also https://github.com/remirror/remirror/pull/1855
=> chore: stop deploy production sites from v1 branch

.github/workflows/docs.yml, .github/workflows/storybook.yml
Migrate the production website source from `v1` branch to `main` branch.
See also https://github.com/remirror/remirror/pull/1854
=> chore: deploy production sites from main branch

.changeset/pre.json
=> chore: exit prerelease mode and prepare to release v2 stable

packages/jest-prosemirror/package.json, packages/prosemirror-paste-rules/package.json, packages/prosemirror-resizable-view/package.json, packages/prosemirror-suggest/package.json, packages/prosemirror-trailing-node/package.json, packages/remirror__dev/package.json, packages/remirror__pm/package.json, pnpm-lock.yaml
=> chore(deps): update remirror packages

docs/migration-v2.md, website/blog/2022-09-15-announcement-v2.md, website/sidebar.cjs
Explain what v2 is about and how to migrate to it.
=> docs: add v2 announcement and migration guide

.changeset/hungry-singers-jump.md, packages/remirror__core-utils/src/command-utils.ts
=> fix(react-component): fix the regex in `isSafari`

website/blog/2022-09-15-create-nodeview-with-content.md
Publish a blog about creating a NodeView with content using a react component
=> docs: publish blog on creating nodeview with content as react component

docs/extensions/mention-atom-extension.mdx
Update mention atom extension documentation
=> docs: update mention atom extension documentation

.changeset/thick-badgers-allow.md, packages/remirror__extension-react-tables/src/components/table-cell-menu.tsx, packages/remirror__styles/all.css, packages/remirror__styles/components.css, packages/remirror__styles/src/dom.tsx, packages/remirror__styles/src/emotion.tsx, packages/remirror__styles/src/styled-components.tsx, packages/remirror__theme/src/components-theme.ts
Expose the ability to split and merge cells
=> feat(react-tables): expose split and merge in the dropdown menu

packages/remirror__core-utils/src/core-utils.ts
Make the error message more detailed when Remirror is used on the server environment 
Close https://github.com/remirror/remirror/issues/1894
=> docs: clarify the error message from `getDocument`

docs/extensions/index.md
Add documentation for community extensions.
=> docs: add link to community extension

.changeset/rich-zebras-promise.md, packages/jest-prosemirror/src/jest-prosemirror-editor.ts, packages/prosemirror-paste-rules/package.json, packages/prosemirror-resizable-view/package.json, packages/prosemirror-suggest/package.json, packages/prosemirror-trailing-node/package.json, packages/remirror__core-utils/__tests__/core-utils.node.spec.ts, packages/remirror__core-utils/package.json, packages/remirror__dev/package.json, packages/remirror__extension-annotation/src/annotation-extension.ts, packages/remirror__extension-code-block/__tests__/code-block-extension.node.spec.ts, packages/remirror__pm/package.json, pnpm-lock.yaml
=> chore(deps): update dependencies

.changeset/shaggy-shrimps-punch.md, packages/remirror__extension-tables/src/index.ts, packages/remirror__extension-tables/src/table-positioners.ts, packages/storybook-react/stories/extension-positioner/positioner-extension.stories.tsx, packages/storybook-react/stories/extension-positioner/table-positioners.tsx
Adds a new positioner for table cell selections
=> feat(tables): add a new positioner for cell selections

packages/remirror__core/src/builtins/builtin-decorators.ts
=> docs: correct the comment for command decorator

.changeset/kind-paws-mix.md, packages/jest-prosemirror/package.json, packages/remirror__extension-react-tables/src/views/table-view.tsx, packages/remirror__extension-tables/src/table-extensions.ts, packages/remirror__pm/package.json, pnpm-lock.yaml
`prosemirror-tables` is a native TypeScript project now. This PR updates `prosemirror-tables` to the latest beta version and fixes some typing.
=> chore(extension-tables): update prosemirror-tables to v1.3.0-beta.0

.changeset/kind-paws-mix.md, .changeset/plenty-ads-attend.md, packages/jest-prosemirror/package.json, packages/prosemirror-paste-rules/package.json, packages/prosemirror-resizable-view/package.json, packages/prosemirror-suggest/package.json, packages/prosemirror-trailing-node/package.json, packages/remirror__dev/package.json, packages/remirror__pm/package.json, pnpm-lock.yaml
=> chore: update prosemirror dependencies

.changeset/gorgeous-carrots-hammer.md, packages/remirror__styles/all.css, packages/remirror__styles/extension-gap-cursor.css, packages/remirror__styles/extension-image.css, packages/remirror__styles/src/dom.tsx, packages/remirror__styles/src/emotion.tsx, packages/remirror__styles/src/styled-components.tsx, pnpm-lock.yaml
=> chore(deps): update caniuse

.changeset/clean-pianos-fly.md, packages/multishift/package.json, packages/multishift/src/multishift-hooks.ts, packages/multishift/src/use-id.ts, pnpm-lock.yaml
=> fix(multishift): remove `@reach/auto-id`

.changeset/nasty-paws-study.md, packages/remirror__extension-yjs/package.json, pnpm-lock.yaml
=> fix(extension-yjs): fix missing peer warning

.changeset/blue-crabs-knock.md, packages/remirror__react-components/src/find-replace/use-find-replace.tsx, packages/storybook-react/stories/extension-find/basic.tsx, packages/storybook-react/stories/react-components/find-replace.stories.tsx
Closes https://github.com/remirror/remirror/issues/2016
=> fix(react-components): increase active index after replace

.eslintignore, .github/workflows/ci.yml, .github/workflows/docs.yml, .github/workflows/e2e.yml, .github/workflows/publish-pr.yml, .github/workflows/publish-v1.yml, .github/workflows/publish.yml, .github/workflows/storybook.yml, .github/workflows/version.yml, .gitignore, support/actions/pnpm/action.yml
=> chore: simplify ci cache

.github/workflows/storybook.yml, package.json, packages/remirror__core-helpers/src/core-helpers.ts, packages/remirror__core-utils/src/core-utils.ts, packages/storybook-react/.storybook/main.js, packages/storybook-react/package.json, packages/storybook-react/stories/extension-positioner/basic.tsx, packages/storybook-react/stories/extension-positioner/table-positioners.tsx, pnpm-lock.yaml
=> chore: update typescript to v5, storybook to v7

.eslintrc.js
React version. "detect" automatically picks the version you have installed.
You can also use `16.0`, `16.3`, etc, if you want to override the detected value.
It will default to "latest" and warn if missing, and to "detect" in the future
https://github.com/jsx-eslint/eslint-plugin-react/blob/f56851b433e7171991eb7e726f00596f14563c25/README.md?plain=1#L43
=> chore(eslint): fix react version  setting

.github/workflows/ci.yml, .github/workflows/e2e.yml, .github/workflows/publish-v1.yml, .github/workflows/publish.yml, .github/workflows/version.yml
=> chore: increase ci timeout

.changeset/eighty-dodos-promise.md, packages/remirror__messages/package.json, packages/remirror__messages/public/remirror-messages.d.ts
=> fix(messages): fix typing file

.changeset/smart-seahorses-sort.md, packages/remirror__core-helpers/src/core-helpers.ts, packages/remirror__core/src/builtins/attributes-extension.ts, packages/remirror__core/src/framework/base-framework.ts
=> fix(core): export type `ClassName`

package.json
=> chore: fix renovate warning about internal package

package.json, packages/remirror__types/package.json, packages/remirror__types/src/index.ts, pnpm-lock.yaml, support/scripts/package.json, support/scripts/src/generate-configs.ts, support/scripts/src/helpers.ts, support/scripts/src/mutatate-packages.ts
=> chore(deps): update type-fest to v3

package.json
=> chore: ignore some pure ESM dependencies for renovate

.changeset/orange-moles-joke.md, packages/create-context-state/src/create-context-hook.tsx
A workaround for https://github.com/remirror/remirror/issues/2070
=> fix(create-context-hook): fix bundled dts

.changeset/pink-hornets-share.md, packages/remirror__extension-link/__tests__/link-extension.spec.ts, packages/remirror__extension-link/src/link-extension.ts
=> fix(link-extension): remove duplicate click handler

packages/prosemirror-paste-rules/src/index.ts
=> chore: fix duplicated export

.changeset/quick-fireants-search.md, docs/getting-started/create-manager.md, packages/remirror__core/src/builtins/upload-extension/file-placeholder-plugin.ts, packages/remirror__extension-file/src/file-uploaders/slow-file-uploader.ts, packages/remirror__react-components/package.json, pnpm-lock.yaml
Close https://github.com/remirror/remirror/issues/2105
=> fix(react): add @floating-ui/react into dependencies

.changeset/curvy-jobs-jam.md, packages/remirror__react-components/src/floating-menu.tsx
Close https://github.com/remirror/remirror/issues/2115
=> fix(react): respect floating-ui placement prop

.changeset/angry-lies-bathe.md, .size-limit.json, packages/remirror__extension-react-language-select/package.json, packages/remirror__extension-react-language-select/readme.md, packages/remirror__extension-react-language-select/src/language-select.tsx, packages/remirror__extension-react-language-select/src/tsconfig.json, packages/remirror__styles/src/styled-components.tsx, packages/storybook-react/package.json, packages/storybook-react/src/tsconfig.json, packages/storybook-react/stories/tsconfig.json, pnpm-lock.yaml, tsconfig.json, website/extension-examples/extension-code-block/with-language-select.tsx
Tweaks some files for the previous PR.
=> chore: tweak some files for new package

.changeset/smooth-ravens-look.md, packages/jest-prosemirror/package.json, packages/prosemirror-paste-rules/package.json, packages/prosemirror-resizable-view/package.json, packages/prosemirror-suggest/package.json, packages/prosemirror-trailing-node/package.json, packages/remirror__dev/package.json, packages/remirror__extension-embed/package.json, packages/remirror__extension-image/package.json, packages/remirror__extension-yjs/package.json, packages/remirror__pm/package.json, pnpm-lock.yaml
=> chore(deps): update prosemirorr dependencies

.changeset/wicked-cooks-sell.md, packages/remirror__extension-react-tables/src/utils/dom.ts
=> fix(extensions-react-table): handle object style

packages/remirror__extension-react-component/package.json, packages/remirror__extension-react-tables/package.json, packages/remirror__react-components/package.json, packages/remirror__react-core/package.json, packages/remirror__react-hooks/package.json, pnpm-lock.yaml
=> chore: fix cyclic dependency

.github/workflows/ci.yml, .github/workflows/docs.yml, .github/workflows/e2e.yml, .github/workflows/label-pull-requests.yml, .github/workflows/publish-pr.yml, .github/workflows/publish-v1.yml, .github/workflows/publish-v3.yml, .github/workflows/publish.yml, .github/workflows/storybook.yml, .github/workflows/version.yml, .gitignore, .size-limit.json, packages/remirror__extension-react-tables/__tests__/tsconfig.json, packages/remirror__extension-react-tables/src/tsconfig.json, packages/remirror__react-editors/__e2e__/tsconfig.json, packages/remirror__react-editors/src/tsconfig.json, packages/storybook-react/src/tsconfig.json, packages/storybook-react/stories/tsconfig.json
=> chore(ci): enable turbo remote cache

.github/workflows/ci.yml
=> chore: run ci for branch v3

.github/workflows/publish-v1.yml, .github/workflows/publish-v3.yml, .github/workflows/publish.yml, .github/workflows/version.yml
=> chore(ci): add publish-v3 workflow

.github/workflows/ci.yml, .github/workflows/docs.yml, .github/workflows/e2e.yml, .github/workflows/label-pull-requests.yml, .github/workflows/publish-pr.yml, .github/workflows/publish-v1.yml, .github/workflows/publish-v3.yml, .github/workflows/publish.yml, .github/workflows/storybook.yml, .github/workflows/version.yml
=> chore(ci): add turborepo environment variables

docs/extensions/file-extension.mdx, docs/extensions/index.md, packages/remirror__extension-file/readme.md, packages/remirror__react-components/package.json, packages/remirror__react-ui/package.json, packages/remirror__react-ui/readme.md, packages/remirror__react-ui/src/providers/ui-theme-provider.tsx, packages/storybook-react/package.json, packages/storybook-react/stories/react-ui/custom-mui-theme.stories.tsx, pnpm-lock.yaml
Repeat of #2195 which I accidentally opened against the wrong base branch.
Remove "beta" flag from `file-extension`.
Link some orphaned extensions docs to the parent index file.
=> docs: tidy up

.changeset/quick-trainers-decide.md, packages/remirror__cli/package.json, packages/remirror__cli/src/utils/build-package.ts, pnpm-lock.yaml
Downgrade build target to node 14.
**Before:**
**After:**
**Before:**
**After:**
=> chore: downgrade build target

.changeset/chilled-teachers-promise.md, .size-limit.json, packages/create-context-state/package.json, packages/remirror__cli/src/utils/build-package.ts, packages/remirror__extension-code-block/package.json, packages/remirror__extension-find/package.json
This ensures we transform class properties etc
=> chore: downgrade build target to support browsers since 2017

docs/getting-started/custom-extension.md
Adding/fixing imports on the custom extension docs
=> fix(docs): custom extension docs fix

docs/migration-v3-beta.md, website/blog/2023-11-20-announcement-v3-beta.md
Creating blog post and migration guide
=> docs: create Remirror v3 beta announcement

.changeset/twenty-yaks-brake.md, packages/remirror__extension-markdown/src/markdown-to-html.ts
=> chore: update changeset file level

.changeset/spotty-carpets-lick.md
This is to prevent all packages being major bumped
See: https://github.com/changesets/changesets/issues/1011
=> fix: downgrade @remirror/pm update from minor to patch

.changeset/spotty-carpets-lick.md
=> chore: correct typo

docs/advanced/updating-editor-externally.md, docs/migration-v3.md, website/blog/2024-07-31-announcement-v3.md
Update the V3 beta announcement and migration guide now v3 has launched
=> docs: add V3 announcement and migration guide

package.json
=> chore(deps): update pnpm to v8.15.9
