remirror/remirror

@remirror/core-extensions/package.json, @remirror/core/package.json, @remirror/core/src/helpers/__tests__/base.spec.ts, @remirror/core/src/helpers/__tests__/utils.spec.ts, @remirror/core/src/helpers/base.ts, @remirror/extension-emoji/package.json, @remirror/extension-enhanced-link/package.json, @remirror/extension-epic-mode/package.json, @remirror/extension-mention/package.json, @remirror/react-ssr/package.json, @remirror/react/package.json, @remirror/renderer-react/package.json, @remirror/ui-twitter/package.json, package.json, packages/jest-prosemirror/package.json, packages/jest-remirror/package.json, packages/remirror/package.json, support/babel/base.babel.js, support/dependencies/package.json, support/rollup/factory.js, yarn.lock
- Removes `node: 8` from `@babel/preset-env` config
- Add `@babel/transform-runtime` to the build
- Add `"@babel/runtime-corejs2": ">=7"`  as a direct dependency of `@remirror/core` and a peer dependency of all other projects
- Fixes broken test and deprecates `isClass` utility which no longer makes sense since classes are compiled down to functions.
- Removes [`lolex`](https://github.com/sinonjs/lolex) as a test dependency which stopped working after changes made.
Fixes #59
=> fix: make build compatible with next.js

@remirror/react/src/components/__tests__/remirror-manager.spec.tsx, @remirror/react/src/components/remirror-manager.tsx
This patch allows for better composition within `RemirrorManager` by
allowing loading extensions via child Fragments.
This lets (immediate) child components of RemirrorManager load extensions.
```jsx
<RemirrorManager>
<Component />
<>
<RemirrorExtension Constructor={NewExtension} />
</>
<RemirrorExtension Constructor={PlaceholderExtension} emptyNodeClass='empty' />
</RemirrorManager>,
```
=> feat: remirror-manager supports child fragments

readme.md
Fix imports of core-extensions in readme.md. 
Renames `Bold` to `BoldExtension`, `Underline` to `UnderlineExtension`, and `Italic` to `ItalicExtension`.
=> Fix imports of core-extensions in readme.md. 

@remirror/react-utils/src/helpers.ts, docs/index.mdx, docs/install.mdx, packages/remirror/readme.md, readme.md
Rename EMPTY_OBJECT_NODE to EMPTY_PARAGRAPH_NODE in docs.
```
=============================== Coverage summary ===============================
Statements   : 69.03% ( 1995/2890 )
Branches     : 55.12% ( 813/1475 )
Functions    : 62.58% ( 612/978 )
Lines        : 69.38% ( 1928/2779 )
================================================================================
Test Suites: 42 passed, 42 total
Tests:       1 skipped, 409 passed, 410 total
Snapshots:   26 passed, 26 total
Time:        56.046s
Ran all test suites in 11 projects.```
=> Docs update: rename EMPTY_OBJECT_NODE to EMPTY_PARAGRAPH_NODE

docs/guides/quickstart.mdx
Rename WysiwygUI to WysiwygEditor in quickstart.mdx
Relevant changelog.md ref:
```
- 💥 **BREAKING `@remirror/editor-wysiwyg`:** Rename `UIWysiwyg` and `WysiwygUI` to `WysiwygEditor`.
```
=> Rename WysiwygUI to WysiwygEditor in quickstart.mdx

@remirror/core/src/extension.ts, @remirror/core/src/helpers/__tests__/utils.spec.ts, @remirror/core/src/helpers/nodes.ts, @remirror/core/src/helpers/utils.ts, @remirror/core/src/nodes/__tests__/paragraph.spec.ts, @remirror/core/src/nodes/paragraph.ts, @remirror/core/src/types/builders.ts, @remirror/core/src/types/index.ts, @remirror/editor-wysiwyg/src/components/editor.tsx, @remirror/extension-code-block/src/__tests__/code-block.spec.ts, @remirror/extension-code-block/src/code-block-extension.ts, @remirror/extension-code-block/src/code-block-plugin.ts, @remirror/extension-code-block/src/code-block-types.ts, @remirror/extension-code-block/src/code-block-utils.ts, @remirror/react/src/components/__tests__/remirror-manager.spec.tsx, @remirror/react/src/components/remirror-manager.tsx, changelog.md, packages/jest-remirror/src/render-editor.tsx, support/fixtures/schema-helpers.ts
- `@remirror/core`: Allow extensions to override `baseExtension` in the `RemirrorManager` component.
- `@remirror/core`: Add `ensureTrailingParagraph` as a configuration option for the paragraph node. In some scenarios it is difficult to place a cursor after the last element. This ensures there's always space to select the position afterward and fixes a whole range of issues. It defaults to false otherwise it breaks a lot of tests. Similar to https://github.com/scrumpy/tiptap/issues/143
- 🚀 `@remirror/extension-code-block`: Add backspace support for more easily deleting an empty code block.
=> feat: ensure trailing paragraph

@remirror/core-extensions/src/marks/__tests__/link.spec.ts, @remirror/core-extensions/src/marks/link.ts, @remirror/core-extensions/src/nodes/__tests__/heading.spec.ts, @remirror/core-extensions/src/nodes/heading.ts, @remirror/core/src/__tests__/node-extension.spec.ts, @remirror/core/src/extension.ts, @remirror/core/src/nodes/__tests__/paragraph.spec.ts, @remirror/core/src/nodes/paragraph.ts, @remirror/core/src/types/base.ts, changelog.md
- `@remirror/core`: Add `getExtraAttrs` method to the extension which can be used in the `(Mark/Node)Extension`.
- `@remirror/core`: Update `extraAttrs` configuration to enable parsing the dom.
- `@remirror/core-extensions`: Add `extraAttrs` to the following extensions:
`LinkExtension`, `ParagraphExtension`, `HeadingExtension`.
Closes #113
=> feat: add the ability to parse the dom for extra attributes

@remirror/core/src/__tests__/extension-manager.helpers.spec.ts, @remirror/core/src/extension-manager.helpers.ts, @remirror/core/src/helpers/__tests__/base.spec.ts, @remirror/core/src/helpers/base.ts, @remirror/renderer-react/src/__tests__/serializer.spec.tsx
Closes #125 
Fixes a bug with using unstable `Array.prototyp.sort` by creating a new sort helper that ensures sorts are stable.
=> fix: unstable extension order after sort

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/custom.md, .github/ISSUE_TEMPLATE/feature_request.md, readme.md
The contributing link references `master` but that's out of date with `canary` (the link doesn't work). This PR fixes the link in the README to be relative (which should work on any branch) and fixes the links referenced in the issue templates.
=> Fix contributing links

e2e/wysiwyg.e2e.test.ts
See #146 - three E2E tests were failing on linux; these changes make everything green.
Note [the puppeteer 'keyboard.press' docs](https://pptr.dev/#?product=Puppeteer&version=v1.19.0&show=api-keyboardpresskey-options) reference [the US keyboard layout](https://github.com/GoogleChrome/puppeteer/blob/master/lib/USKeyboardLayout.js) which is where `KeyF` originates. Though `f` is also defined in that file, for some reason it does not seem to work on linux :man_shrugging: 
=> Fix E2E tests on Linux

e2e/helpers/index.ts, e2e/helpers/serializers/html-serializer.js, e2e/jest.config.js, e2e/social.e2e.test.ts, support/jest/jest.framework.ts, yarn.lock
I've added an HTML serializer for the Jest tests to make it easier to update the tests without having to go through and edit each one (in future). I've used prettier to format the HTML so it's easier to read, but I'm not yet sure that my indentation code is correct. I've also added `const FIRST_PARAGRAPH_SELECTOR = EDITOR_CLASS_SELECTOR + ' > p:first-child';` so that we get the content of the first paragraph since we don't care about the `<p>` tag itself in our tests; I'm not sure if this should be moved to a more central location like `@remirror/core` or not?
The test looks very similar to before, but it factors in more of the content and it can auto-update, so I'm calling that a win :grin: 
```diff
it('should have a social editor', async () => {
await $editor.focus();
await …
```
=> test: add HTML snapshot tests

.artifactignore, .gitpod.yml, .vscode/settings.json, package.json, support/azure/azure-pipelines.yml, support/azure/pipeline-jobs.yml, support/azure/pipeline-restore-build.yml, support/azure/pipeline-yarn-install.yml, support/scripts/helpers/read-config.js, support/scripts/run-if-config.js, support/scripts/run-if-not-ci.js
- Add caching for yarn to the pipelines ❌[issue](https://github.com/microsoft/azure-pipelines-tasks/issues/11259#issuecomment-535304299)
- Save build artifact for reuse across pipelines
<a href="https://gitpod.io/#https://github.com/ifiokjr/remirror/pull/161"><img src="https://gitpod.io/api/apps/github/pbs/github.com/ifiokjr/remirror.git/f21331dd3335b7aa63028dfaa13e4c5c6f2ca64a.svg" /></a>
=> ci: cache yarn and preserve the build across jobs

docs/pages/guides/quickstart.mdx
Removed an `r` which appears to have been typed by mistake along with the `e` in `taste`.
Note: I originally sought to update the published documentation to change extension references from `Bold` to `BoldExtension` (for example); however, I saw they were already updated in the canary branch and need to be published.
N/A
=> typo correction

@remirror/editor-social/src/components/social-editor.tsx, @remirror/editor-social/src/components/social-wrapper-component.tsx, @remirror/editor-social/src/social-types.ts, examples/with-next/pages/editor/social/content.tsx
There was previously no way to override the social character limit, and the `hideCharacterIndicator` prop did nothing. This PR fixes both issues.
=> feat(social): allow overriding character limit in Social UI

examples/with-next/readme.md
Without this, the showcase modules could not be found.
Following the example's instruction, I got the following errors.
```console
$ git clone git@github.com:ifiokjr/remirror.git
$ cd remirror
$ yarn
$ cd examples/with-next
$ yarn dev
```
Browsing localhost:3000 works, but when clicking on the WYSIWYG example I get the following error.
```
Failed to compile
./pages/editor/wysiwyg/index.tsx
Module not found: Can't resolve '@remirror/showcase/lib/wysiwyg' in '~/dev/remirror/examples/with-next/pages/editor/wysiwyg'
```
=> Fix with-next instructions

packages/multishift/src/multishift-utils.ts
`useId()` from `@react/auto-id` returns a number. Rather than casting this to a String in `useElementIds` I figured it made more sense to make the `getElementIds` call more liberal.
=> Fix TypeScript error with useId() from @reach/auto-id

.changeset/spotty-bananas-remain.md, @remirror/core-extensions/src/extensions/history-extension.ts, @remirror/core-extensions/src/marks/bold-extension.ts, @remirror/core-extensions/src/marks/code-extension.ts, @remirror/core-extensions/src/marks/italic-extension.ts, @remirror/core-extensions/src/marks/strike-extension.ts, @remirror/core-extensions/src/marks/underline-extension.ts, @remirror/core-extensions/src/nodes/blockquote-extension.ts, @remirror/core-extensions/src/nodes/bullet-list-extension.ts, @remirror/core-extensions/src/nodes/hard-break-extension.ts, @remirror/core-extensions/src/nodes/heading-extension.ts, @remirror/core-extensions/src/nodes/list-item-extension.ts, @remirror/core-extensions/src/nodes/ordered-list-extension.ts, @remirror/core-extensions/src/nodes/simple-code-block-extension.ts
First of all, excellent project. I really appreciate the idea of `Extension`, where I can put ALL my logic of one node/mark into a single class. Greet improvement for the readability.  When I using remirror in my project, I found a TypeScript issue as described below:
----
I want to extend those exist extensions in remirror but only change the key method, like something below:
```typescript
class MyCodeBlockExtension extends CodeBlockExtension {
public keys(): KeyboardBindings {
return {
somekey: something
}
}
}
```
However, TS stop me from do this, beacuse `CodeBlockExtension.keys` return `{'Shift-Ctrl-\\': CommandFunction<any>}`. `MyCodeBlockExtension` must follow this type since it's a subcalss of `CodeBlockExtension`. 
I can prevent this error by 1) copy code from `@remirror` instead …
=> fix(core-extensions): make `keys()` return `KeyboardBindings`

.changeset/angry-books-shop.md, .changeset/tricky-cheetahs-provide.md, @remirror/cli/CHANGELOG.md, @remirror/editor-social/src/components/social-editor.tsx, @remirror/editor-social/src/social-types.ts, @remirror/showcase/src/data/fake-users.ts, @remirror/showcase/src/social.tsx
Currently the code uses the username as the id; but users may edit their username over time so this could lead to broken content. A user's `id` never changes, so this PR allows you to store the ID you specify.
Similarly not every website users `/${username}` as the URL for a user; e.g. reddit uses `/u/${username}`. This PR allows overriding and storing custom id and href with mentions and tags.
=> feat(social): enable overriding mention and tag ids and hrefs

@remirror/cli/CHANGELOG.md, examples/with-next/pages/editor/rich-social/rich.tsx
It's often useful when experimenting to see what's going on under the covers. This adds a checkbox to start rendering the prosemirror JSON out.
To make things easier I've persisted this setting to localStorage so it can store your preference.
I've only applied this to the rich social editor so far, but it could easily be extended to other editors. It could easily be extracted into a shared hook.
**WARNING**: onStateChange states "If this exists the editor becomes a controlled component. Nothing will be updated unless you explicitly set the value prop to the updated state. Without a deep understanding of Prosemirror this is not recommended." but I've used that API since I don't know what else to use?
=> chore: add option to output JSON in Next example

@remirror/core-helpers/src/core-helpers.ts
Rollup doesn't recognize all being output by deepmerge. This solves that problem so that I can use prosemirror in a rollup environment.
=> fix: compat across build systems

.changeset/silver-impalas-provide.md, @remirror/core-extensions/src/extensions/history-extension.ts, @remirror/core-extensions/src/marks/link-extension.ts, @remirror/core-types/src/core-types.ts, @remirror/core/src/extension-manager.helpers.ts, @remirror/core/src/extension-manager.ts, @remirror/core/src/extension.ts, @remirror/core/src/mark-extension.ts, @remirror/core/src/node-extension.ts, @remirror/editor-wysiwyg/src/components/wysiwyg-menu.tsx, @remirror/extension-code-block/src/code-block-extension.ts, docs/CHANGELOG.md, e2e/CHANGELOG.md
This PR changes code related to Extension.isActive() and Extension.isEnabled(). 
The action.isActive() and action.isEnabled() behaviour remains the same so this should not break code that doesn't access extensions directly.
Before this PR extensions by default would return true when calling Extension.isEnabled() and most extensions never implemented a custom Extension.isEnabled(). This resulted in issues such as #226 where action.isEnabled() would be true but command could not be run successfully. 
Extensions no longer need to implement isEnabled. It is provided by extension manager by calling commands with dispatch=undefined [as Prosemirror intended](https://prosemirror.net/docs/guide/#commands). It's now much more difficult to have action.isEnabled() return true unless a command can be …
=> feat(core): isEnabled via commands with dispatch=undefined

.changeset/eighty-lies-judge.md, @remirror/core-utils/src/__tests__/command-utils.spec.ts, @remirror/core-utils/src/__tests__/prosemirror-utils.spec.ts, @remirror/core-utils/src/command-utils.ts, @remirror/core-utils/src/prosemirror-utils.ts
toggleList() from command-utils is now able to convert between list types. The implementation has been taken [from tiptap](https://github.com/scrumpy/tiptap/blob/3102d00a626be03c036122128d79b995a9d67f77/packages/tiptap-commands/src/commands/toggleList.js). Also, more units tests for toggleLists() have been added.
Tiptatp's toggleList implementation required findParentNode() to return a depth value, hence this parameter was implemented and tests were updated to include it. To be consistent, this also has been implemented for findPositionOfNodeBefore/findPositionOfNodeAfter. While doing so I noticed some missing tests and (I think) incorrect start position being returned by  findPositionOfNodeBefore/findPositionOfNodeAfter.
=> feat(core-utils): allow toggling between bullet and ordered list

.changeset/loud-schools-breathe.md, .github/workflows/ci.yml, @remirror/core/src/__tests__/node-extension.spec.ts, @remirror/core/src/extension.ts
`ExtraAttrsObject.default` should be a `sting`, `null` or `undefined` value. Based on the [definition](https://github.com/remirror/remirror/blob/c4645570d3e128d1decf3b9e904684263df7bf0c/%40remirror/core-types/src/base-types.ts#L224-L229), an attr is a required only if its `default` is  `undefined`. 
However, when `default` is an empty string (or `null`), this attr becomes a required unexpectedly. 
This PR fixs it.
=> fix(core): Allow empty string default value for extraAttrs

.changeset/bright-foxes-report.md, @remirror/react/src/components/__tests__/remirror.spec.tsx, @remirror/react/src/components/remirror.tsx, @remirror/react/src/hooks/context-hooks.ts, @remirror/react/src/react-types.ts
Add a `focus` method to the remirror editor context object. It allows focusing at a provided position which can be `start`, `end`, a specific position or a range using the `{from: number; to: number}` type signature.
To use this run the following.
```tsx
import { useRemirrorContext } from '@remirror/react';
const MyEditor = () => {
const { focus, getRootProps } = useRemirrorContext();
useEffect(() => {
focus('end'); // Autofocus to the end of the editor text when this component loads.
}, []);
};
return <div {...getRootProps()} />;
```
Resolves the initial issue raised in #229.
=> feat: add `focus()` method to `RemirrorContext`

.changeset/curvy-fireants-destroy.md, @remirror/react/src/components/__tests__/remirror.spec.tsx, @remirror/react/src/components/remirror.tsx, @remirror/react/src/react-types.ts, docs/generated/gatsby.ts, docs/showcase/social.mdx, docs/showcase/wysiwyg.mdx, docs/src/components/layout.tsx
- Enable `autoFocus` in docs.
- Extends `autoFocus` to accept the same types as `focus()` context method.
Closes #261
*Tested in a simulator*
=> feat(react): enable custom `autoFocus`

.changeset/big-pans-kneel.md, @remirror/extension-mention/src/__tests__/mention.spec.ts, @remirror/extension-mention/src/mention-extension.ts
First swing at this after reading over the documentation. Let me know if it needs any adjustments! 🙏 
- Fixes #263.
- Adds `this.getExtraAttrs(node)` to the `parseDOM` attribute results when parsing mention elements.
=> fix(extension-mention): parse extraAttrs when parsing DOM

support/tsconfig.base.json
When developing, it's common to comment out lines of code. When doing so, you shouldn't have to remove the import just for the development bundle to build. Similarly you may add arguments to a method that you're not using _yet_ but will be, or declaring variables again which you don't use right this second but will need. Detecting these issues are a job for ESLint; preventing a CI pass when these issues makes sense, but preventing you from even using your new code because it doesn't pass lint rules is a huge barrier to productivity.
This PR removes these lint-y rules from the base tsconfig, delegating them to ESLint.
=> TypeScript should not perform ESLint's tasks

.changeset/chatty-deers-guess.md, .changeset/selfish-suits-look.md, .changeset/sixty-colts-wave.md, @remirror/extension-code-block/src/__tests__/code-block.spec.ts, @remirror/extension-code-block/src/code-block-extension.ts, @remirror/extension-code-block/src/code-block-utils.ts, packages/jest-prosemirror/package.json
This simple PR add syntax highlight support for language name who has different case then the definition from Refractor. 
For example, Remirror support `yml` and `yaml` currently. With this PR, `YAML` and `YML` will also been supported.
As a proof of the necessity, GitHub website provides syntax highlight for all four language names below:
```yaml
language: "yaml"
```
```yml
language: "yml"
```
```YAML
language: "YAML"
```
```YML
language: "YML"
```
Removed  `isSupportedLanguage` and `getSupportedLanguagesMap`.
For `isSupportedLanguage`, I removed it just because it's unused in this repository. If you think we shouldn't break the backward compatibility easily, I can add this function back.
For `getSupportedLanguagesMap`, one reason is that it's never used in the repository, but the more …
=> feat(code-extension): support syntax highlight for upper language name

.all-contributorsrc, .changeset/four-bikes-unite.md, @remirror/extension-image/src/image-extension.ts, readme.md
image-extenison's `toDOM` is defined as object method, which couldn't pick up the extension's `this`, which would be a problem if `toDOM` needs to access `options` passed to the extension when it is setup.
This fix simply converts `toDOM` to arrow function to pick up `this` of extension.
=> fix: image-extension `toDOM` can now safely access `this`

.changeset/eighty-trainers-change.md, @remirror/extension-collaboration/src/collaboration-extension.ts
There doesn't seem to be any `.step` sub-structure in collaboration steps passed to e.g. [`onSendableReceived`](https://github.com/remirror/remirror/blob/000fdfb0d5e8da63e7ab8241ac4e6b8ccdc4ace0/%40remirror/extension-collaboration/src/collaboration-extension.ts#L120). Looking into the history of both Remirror and ProseMirror, I see that [Branch items can have a `.step`](https://github.com/ProseMirror/prosemirror-history/blob/master/src/history.js#L52), which might be where the confusion came from
(but on the other hand, neither was the old one.)
=> fix: remove `.step` property from collaboration steps

docs/install.mdx
link to examples leads to Page not found. Changed the link to the examples directory.
=> docs: fix link to examples on install page

@remirror/playground/src/make-code.tsx
Since a Remirror schema is not expected to change dynamically, we can (and should?) hoist the extensions to the root scope to prevent dynamically re-creating them on every render. This will reduce the load on the garbage collector, on React comparisons, and is also a better way of demoing to the user.
```ts
import { useRemirrorPlayground } from "@remirror/playground";
import React, { FC } from "react";
import { BoldExtension } from "remirror/extension/bold";
import { ItalicExtension } from "remirror/extension/italic";
import { RemirrorProvider, useManager, useRemirror } from "remirror/react";
const EXTENSIONS = [new BoldExtension(), new ItalicExtension()];
/**
* This component contains the editor and any toolbars/chrome it requires.
*/
const SmallEditor: FC = () => {
const { getRootProps, …
```
=> chore(playground): hoist extensions to root scope

@remirror/playground/src/make-code.tsx, @remirror/playground/src/use-remirror-playground.tsx
Makes the playground into a correctly controlled component using the new API.
=> feat(playground): Controlled playground

packages/@remirror/playground/src/code-editor.tsx, packages/@remirror/playground/src/compile.tsx, packages/@remirror/playground/src/execute.tsx, packages/@remirror/playground/src/index.tsx, packages/@remirror/playground/src/playground.tsx, packages/@remirror/playground/src/primitives.tsx, packages/@remirror/playground/src/simple-panel.tsx, packages/@remirror/playground/src/viewer.tsx, support/root/.huskyrc, support/website/src/pages/playground.module.css, support/website/src/pages/playground.tsx
Tidies various things in the playground to make it more suitable for presenting via the website
I gave the playground a loading screen, normally it shows:
But on slower connection:
And here's what the editor looks like a bit updated:
Advanced mode removes the sidebar:
=> Playground tidyup

packages/@remirror/playground/src/simple-panel.tsx, support/website/docusaurus.config.js
This PR adds a notice to the playground so that we can feel more comfortable enabling it on the public website.
This is built on #333 and #334.
=> Enable the Playground on the website

package.json
Node 12 doesn't support `??`, and to be honest developing on Node 14 is fine, it doesn't affect what versions the actual project supports.
```
$ yarn docs
yarn run v1.22.4
warning root@: The engine "pnpm" appears to be invalid.
$ cd support/website && pnpm start
> @remirror/website@0.0.0 start /home/benjie/Dev/Sprout/remirror/support/website
> docusaurus start
Starting the development server...
/home/benjie/Dev/Sprout/remirror/support/website/plugins/monaco-editor.js:28
for (const item of rule.use ?? []) {
^
SyntaxError: Unexpected token '?'
at wrapSafe (internal/modules/cjs/loader.js:1070:16)
at Module._compile (internal/modules/cjs/loader.js:1120:27)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
at Module.load (internal/modules/cjs/loader.js:1000:32)
at …
```
=> Require Node 14 for development

packages/@remirror/extension-trailing-node/src/trailing-node-extension.ts, packages/@remirror/playground/scripts/import-remirror.ts, packages/@remirror/playground/src/_remirror.tsx, packages/@remirror/playground/src/context.tsx, packages/@remirror/playground/src/execute.tsx, packages/@remirror/playground/src/playground.tsx, packages/@remirror/playground/src/use-remirror-playground.tsx
Adds a textarea to the bottom of the playground showing the full state of the playground, including the document itself. This textarea is editable, so you can save reproduction cases and share them with others (e.g. to demonstrate configs, or to help reproduce bugs).
- note
- note
- note
- note
=> Playground serialization/deserialization

docs/guide/installation.mdx
The "Installation" doc originally mentioned useExtensionCreator, which does not exist anymore.
Closes #341
=> docs: remove useExtensionCreator from installation

.changeset/olive-rockets-shout.md, packages/@remirror/core/src/editor-wrapper.ts, packages/@remirror/react/src/components/__tests__/__snapshots__/react-editor-controlled.spec.tsx.snap, packages/@remirror/react/src/components/__tests__/react-editor-controlled.spec.tsx, packages/@remirror/react/src/components/__tests__/remirror-provider.spec.tsx, packages/@remirror/react/src/components/react-editor.tsx, packages/@remirror/react/src/hooks/editor-hooks.ts, support/e2e/server.config.js, support/e2e/src/__snapshots__/positioner.e2e.test.ts.snap, support/e2e/src/helpers/test-environment.ts, support/e2e/src/positioner.e2e.test.ts, support/examples/with-next/src/pages/editor/positioner.tsx, support/examples/with-next/src/pages/editor/social/content.tsx, support/examples/with-next/src/pages/editor/social/index.tsx
=> fix(react): correct `previousState` for controlled editors

.changeset/warm-sloths-admire.md, docs/showcase/social.mdx, packages/@remirror/core-utils/src/command-utils.ts, packages/@remirror/extension-auto-link/src/auto-link-extension.ts, packages/@remirror/extension-mention/src/mention-extension.ts, packages/@remirror/preset-social/src/social-preset.ts, packages/@remirror/react-social/src/hooks/__tests__/use-social-mention.spec.tsx, packages/prosemirror-suggest/src/suggest-predicates.ts, pnpm-lock.yaml, support/e2e/src/__snapshots__/social.e2e.test.ts.snap, support/e2e/src/social.e2e.test.ts, support/website/package.json
Mentions trap the cursor when arrowing left and right through the mention.
Also fixed another bug where mentions were being blocked by the `@remirror/extension-auto-link`. This was fixed by giving the `AutoLinkExtension` a lower priority.
Closes #352
=> fix(react-social): trapped cursor in mentions

.changeset/fast-owls-happen.md, .changeset/four-dryers-clap.md, .github/workflows/ci.yml, docs/errors.mdx, docs/guide/create-editor.mdx, packages/@remirror/core/src/builtins/helpers-extension.ts, packages/@remirror/core/src/editor-wrapper.ts, packages/@remirror/core/src/manager/remirror-manager.ts, packages/@remirror/dom/src/__tests__/dom.spec.ts, packages/@remirror/react/src/components/__tests__/react-editor-server.spec.tsx, packages/@remirror/react/src/components/react-editor.tsx, packages/@remirror/react/src/hooks/__tests__/editor-hooks.spec.tsx, packages/@remirror/react/src/hooks/editor-hooks.ts, readme.md, support/e2e/src/helpers/index.ts, support/e2e/src/positioner.e2e.test.ts, support/examples/with-next/src/pages/editor/positioner.tsx
- Rename `change` event to `updated`. `updated` is called with the `EventListenerParameter`.
- Add new manager `stateUpdate` to the `editorWrapper`
- Add `autoUpdate` option to `useRemirror` hook from `@remirror/react` which means that the context object returned by the hook is always up to date with the latest editor state. It will also cause the component to rerender so be careful to only use it when necessary.
```tsx
const { active, commands } = useRemirror({ autoUpdate: true });
return (
<button
onClick={() => commands.toggleBold}
style={{ fontWeight: active.bold() ? 'bold' : undefined }}
>
B
</button>
);
```
- Fix broken `onChangeHandler` parameter for the use `useRemirror` hook.
Closes #372
Closes #371
No more delayed update of editor state
=> Improve use remirror hook

.changeset/quiet-years-brake.md, .changeset/stupid-crabs-wait.md, packages/@remirror/extension-react-component/src/index.ts, packages/@remirror/extension-react-component/src/node-view-types.ts, packages/@remirror/extension-react-component/src/react-component-extension.ts, packages/@remirror/extension-react-component/src/react-node-view.tsx, packages/@remirror/extension-react-ssr/package.json, packages/@remirror/extension-react-ssr/src/react-ssr-extension.ts, packages/@remirror/react/package.json, packages/@remirror/react/renderers/package.json, packages/@remirror/react/src/renderers/react-serializer.tsx, packages/remirror/react/renderers/package.json, packages/remirror/src/react/renderers.ts, pnpm-lock.yaml
Some changes that came up while working through other changes.
- Use `ReactComponent` for SSR.
- Add `environment to`NodeViewComponentProps`.
- Export `NodeViewComponentProps` from `@remirror/extension-react-component`.
- Refactor `manager.store.components` to use `ManagerStoreReactComponent` interface.
- Add new entrypoint for `@remirror/react/renderers`.
=> Small improvements

.changeset/fuzzy-pandas-tan.md, .changeset/lazy-shrimps-promise.md, .changeset/purple-pants-yell.md, .changeset/violet-doors-pull.md, packages/@remirror/core-helpers/src/core-helpers.ts, packages/@remirror/core/src/manager/remirror-manager.ts, packages/@remirror/preset-core/src/core-preset-methods.ts, packages/@remirror/react-social/src/components/__tests__/social-editor.spec.tsx, packages/@remirror/react-social/src/hooks/__tests__/use-social-emoji.spec.tsx, packages/@remirror/react-social/src/hooks/__tests__/use-social-mention.spec.tsx, packages/@remirror/react-social/src/hooks/__tests__/use-social.spec.tsx, packages/@remirror/react-social/src/hooks/use-social.ts, packages/@remirror/react-social/src/social-utils.ts, packages/@remirror/react/src/components/providers.tsx, packages/@remirror/react/src/components/react-editor.tsx, packages/@remirror/react/src/hooks/__tests__/editor-hooks.spec.tsx, packages/@remirror/react/src/hooks/editor-hooks.ts, packages/@remirror/react/src/react-helpers.tsx, packages/@remirror/testing/src/react.tsx
- `RemirrorManager.create` can now accept a function to which returns an array of extensions and presets. This lazy creation allows for optimizations to be made elsewhere in the codebase.
- Prevent `createReactManager` being called on every render.
- Accept a `manager` as a parameter for `createReactManager`.
- Improve internal performance of components by caching the `ReactEditorWrapper` after the first render.
Remove requirement for `readonly` arrays when passing a list of extensions / presets to manager creators.
- **`@remirror/react`** - Add support for a function as the first parameter to the `useManager` hook and `createReactManager` function.
- **`@remirror/preset-core`** - Add support for a function as the first parameter to the `createCoreManager` function.
Reduce the number of …
=> perf: prevent creating extensions on every render

packages/@remirror/extension-auto-link/readme.md, packages/@remirror/extension-bold/readme.md, packages/@remirror/extension-paragraph/readme.md
Various points of the documentation refer to a preset "formatting", which doesn't exists.
Fixes https://github.com/remirror/remirror/issues/393
=> fix: Readme refers to non-existant preset-formatting

.changeset/healthy-pugs-itch.md, .changeset/moody-geckos-obey.md, packages/@remirror/extension-drop-cursor/src/drop-cursor-extension.ts, packages/@remirror/preset-core/package.json, packages/@remirror/preset-core/src/core-preset.ts, packages/@remirror/preset-wysiwyg/src/wysiwyg-preset.ts, pnpm-lock.yaml
- Use the default `prosemirror-dropcursor` plugin instead of the broken custom implentation. Everything is different.
- Add `GapCursorExtension` and `DropCursorExtension` to the `CorePreset`
Closes #381
=> fix(extension-drop-cursor): simplify the implementation with the `prosemirror-dropcursor` plugin

.changeset/nasty-pears-lie.md, packages/@remirror/preset-social/src/__tests__/social-preset.spec.ts, packages/@remirror/preset-social/src/social-preset.ts
- reduce `AutoLinkExtension` priority so that it can be overridden
- Remove priority override for the mention and emoji extensions
- Add test to verify
Raised by @emilschutte on [discord channel](https://discord.gg/C4cfrMK).
=> fix(preset-social): reduce `AutoLinkExtension` priority

.changeset/config.json, .changeset/neat-gorillas-deny.md, .changeset/witty-beds-change.md, packages/@remirror/core/src/decorators.ts, packages/@remirror/core/src/extension/__tests__/plain-extension.spec.ts, packages/@remirror/core/src/extension/base-class.ts, packages/@remirror/core/src/index.ts, packages/@remirror/extension-events/package.json, packages/@remirror/extension-events/readme.md, packages/@remirror/extension-events/src/__tests__/events-extension.spec.ts, packages/@remirror/extension-events/src/events-extension.ts, packages/@remirror/extension-events/src/index.ts, packages/@remirror/preset-core/package.json, packages/@remirror/preset-core/src/core-preset.ts, packages/jest-prosemirror/package.json, packages/jest-remirror/package.json, packages/remirror/extension/events/package.json, packages/remirror/package.json, packages/remirror/src/extension/events.ts, pnpm-lock.yaml
Add support for `Handler` options with custom return values and early returns.
Previously handlers would ignore any return values. Now a handler will honour the return value. The earlyReturn value can be specified in the static options using the `extensionDecorator`. Currently it only supports primitives. Support for a function to check the return value will be added later.
🎉 New extension `@remirror/extension-events`.
This extension adds handlers for the events happening within the remirror editor. The extension is part of the `CorePreset` but it doesn't make it's handlers available to the preset. In order to use the handlers you will need direct access to the `EventsExtension`.
```ts
import { EventsExtension } from 'remirror/extension-events';
import { useExtension } from …
```
=> feat: new package `@remirror/extension-events` 🎉

.changeset/clever-ears-hang.md, packages/@remirror/extension-emoji/src/__tests__/emoji-extension.spec.ts, packages/@remirror/extension-emoji/src/emoji-extension.ts
- Prevent mid word emoji matches on colon press.
=> fix(extension-emoji): prevent mid word emoji popup

.changeset/nice-files-explode.md, packages/@remirror/preset-core/src/core-preset.ts
Closes #408 
This PR has two modification for the constructor of `CorePreset`:
1. Add a new option call `excludeExtensions`, which is an array of names.
2. Remove option `excludeHistory `
=> feat(core): add option `excludeExtensions` to `CorePreset`

.changeset/big-apples-unite.md, packages/@remirror/core-utils/src/__tests__/core-utils.spec.ts, packages/@remirror/core-utils/src/core-utils.ts, packages/jest-prosemirror/src/jest-prosemirror-editor.ts
Add three new helpers to `@remirror/core-utils` / `@remirror/core`: `isStateEqual`, `areSchemaCompatible` and `getRemirrorJSON`. Requested by @benjie 
BREAKING: 💥 Rename `getObjectNode` to `getRemirrorJSON`.
=> feat(core): add new helper methods

.changeset/early-shoes-bathe.md, .changeset/wet-islands-jam.md, packages/@remirror/core/src/styles.ts, packages/@remirror/extension-hard-break/src/__tests__/hard-break-extension.spec.ts, packages/@remirror/extension-hard-break/src/hard-break-extension.ts, packages/@remirror/extension-horizontal-rule/src/__tests__/horizontal-rule-extension.spec.ts, packages/@remirror/extension-horizontal-rule/src/horizontal-rule-extension.ts, packages/@remirror/styles/all.css, packages/@remirror/styles/core.css
- Default to inserting a new paragraph node after the `HorizontalRuleExtension`.
- BREAKING: 💥 Rename `horizonalRule` command to `insertHorizontalRule`.
- Add a new option `insertionNode` to the `HorizontalRuleExtension` which sets the default node to automatically append after insertion.
- Update the css styles for the default `hr` tag.
Closes #417
- Add `insertHardBreak` command.
- Add inline documentation instructing developers to use the `TrailingNodeExtension` when using `hardBreak` to exit a `codeBlock`.
=> feat(extension-horizontal-rule): auto append node

.changeset/beige-birds-develop.md, .changeset/modern-pens-judge.md, .changeset/tame-points-build.md, packages/@remirror/core-utils/src/command-utils.ts, packages/@remirror/core-utils/src/prosemirror-utils.ts, packages/@remirror/core/src/builtins/__tests__/commands-extension.spec.ts, packages/@remirror/extension-code-block/src/code-block-extension.ts, packages/@remirror/extension-code/src/code-extension.ts, packages/@remirror/extension-heading/src/heading-extension.ts, packages/@remirror/extension-history/src/history-extension.ts, packages/@remirror/extension-italic/src/italic-extension.ts, packages/@remirror/extension-paragraph/src/paragraph-extension.ts, packages/@remirror/extension-strike/src/strike-extension.ts, packages/@remirror/extension-underline/src/underline-extension.ts, packages/@remirror/extension-yjs/src/yjs-extension.ts, packages/@remirror/react/src/components/__tests__/react-editor-controlled.spec.tsx, packages/@remirror/react/src/components/__tests__/remirror-provider.spec.tsx, packages/jest-remirror/src/jest-remirror-editor.ts
- Add `chain` method to `RemirrorTestChain` and update select text to receive `all` for selecting all text.
- Support `chained` commands and multiple command updates in controlled editors.
Fixes #418
- Use `NonChainableCommandFunction` annotation to indicate commands are not chainable.
=> fix: multiple commands issue

.changeset/proud-goats-draw.md, .changeset/small-timers-smoke.md, packages/@remirror/core/src/builtins/commands-extension.ts, packages/@remirror/extension-bold/src/bold-extension.ts
- Support chaining for `setBold` and `removeBold` commands.
- Make sure the `transaction` has all the latest updates if changed between `onStateUpdate` events. This allows chaining to be supported properly.
=> Hot fix chained command support

.changeset/giant-cameras-repair.md, packages/jest-remirror/package.json, packages/jest-remirror/src/jest-remirror-types.ts, pnpm-lock.yaml
This PR fixes two small issues for `jest-remirror`:
1. `CreateCoreManagerOptions` should be imported from `@remirror/preset-core` instead of `@remirror/testing`
2. add dependency `@remirror/preset-core`
=> fix(jest-remirror): add missing dependency `@remirror/preset-core`

.changeset/hot-schools-appear.md, packages/prosemirror-suggest/src/__tests__/suggest-plugin.spec.ts, packages/prosemirror-suggest/src/suggest-plugin.ts, packages/prosemirror-suggest/src/suggest-state.ts
Allow runtime additions to the `prosemirror-suggest` plugin.
You can now add suggester configurations to active suggest plugin instances. The name is used as an identifier and identical names will automatically be replaced.
=> feat(prosemirror-suggest): add and remove suggester

.changeset/violet-eagles-carry.md, packages/@remirror/extension-placeholder/src/__tests__/placeholder-extension.spec.ts, packages/@remirror/extension-placeholder/src/placeholder-extension.ts, packages/@remirror/preset-react/src/react-preset.ts
- Allow runtime updates of `PlaceholderExtension` `emptyNodeClass` option.
=> feat(extension-placeholder): support `emptyNodeClass` updates

.github/workflows/ci.yml
CI is always set to true according GitHub docs
https://docs.github.com/en/actions/configuring-and-managing-workflows/using-environment-variables#default-environment-variables
=> chore: remove CI env variable

.changeset/long-swans-fry.md, packages/@remirror/extension-annotation/src/__tests__/annotation-extension.spec.ts, packages/@remirror/extension-annotation/src/actions.ts, packages/@remirror/extension-annotation/src/annotation-extension.ts
Users could change annotations only by removing and then re-adding them with the changed value.
This is inconvenient when using extended annotations, e.g. an annotation with tags. In those cases, it would be better to simply update the tags of the existing annotation.
=> Allow updating existing annotations

packages/@remirror/core/src/builtins/suggest-extension.ts
createSuggestion was renamed by https://github.com/remirror/remirror/commit/982a6b15b8e5b435f3ad7c5bc39d1c163bc67fd8
This commit adjusts the docu accordingly.
=> Adjust docu after renaming createSuggestion to createSuggesters

.changeset/dull-crews-tickle.md, packages/prosemirror-suggest/src/suggest-types.ts
The matchOffset field isn't defaulted to zero for MentionExtension: https://github.com/remirror/remirror/blob/4b4307bfd039a83dca885640704654d0b23f9747/packages/%40remirror/extension-mention/src/mention-utils.ts#L19
The documentation is therefore misleading when configuring the MentionExtension.
Fixes https://github.com/remirror/remirror/issues/485
=> docs: remove `defaultValue` from code comment

.changeset/silver-pandas-cheer.md, packages/@remirror/core-utils/src/prosemirror-rules.ts, packages/@remirror/extension-italic/src/__tests__/italic-extension.spec.ts
Ensure the `markInputRule` doesn't reactivate previous marks when rules are nested and activated consecutively.
Created for #505
=> fix: bold and italic input rule composition

.changeset/hot-seals-stare.md, packages/@remirror/core-types/src/core-types.ts, packages/@remirror/core-utils/src/core-utils.ts, packages/@remirror/dom/readme.md, packages/@remirror/react/src/components/__tests__/react-editor.spec.tsx
Enable `all` selection when setting initial content and focusing on the editor.
```tsx
import { useRemirror } from 'remirror/react';
const { focus } = useRemirror();
focus('all');
```
=> feat(core-utils): select `all` text in editor

.changeset/brave-rules-switch.md, .github/labeler.yml, docs/concepts/react-controlled-editor.mdx, packages/@remirror/react/src/components/__tests__/react-editor-controlled.spec.tsx, packages/@remirror/react/src/components/react-editor.tsx
Fix the controlled editor when used in `StrictMode`.
This is mentioned in #482.
=> fix(react): controlled editor in `StrictMode`

.changeset/famous-trains-crash.md, packages/@remirror/core-utils/src/__tests__/core-utils.spec.ts, packages/@remirror/core-utils/src/core-utils.ts, packages/@remirror/core-utils/src/index.ts
Rename `areSchemaCompatible` to `areSchemasCompatible`.
Issue: #500
=> feat(core-utils): rename `areSchemaCompatible`

.changeset/brave-ducks-turn.md, .changeset/six-eggs-peel.md, packages/@remirror/core-utils/src/__tests__/prosemirror-rules.spec.ts, packages/@remirror/core-utils/src/command-utils.ts, packages/@remirror/core-utils/src/index.ts, packages/@remirror/core-utils/src/prosemirror-rules.ts, packages/@remirror/extension-code-block/src/code-block-extension.ts, packages/@remirror/extension-horizontal-rule/src/__tests__/horizontal-rule-extension.spec.ts, packages/@remirror/extension-horizontal-rule/src/horizontal-rule-extension.ts
💥 Remove property `updateSelection` from the `nodeInputRule`, `markInputRule` and `plainInputRule` functions. You should use the new `beforeDispatch` method instead.
Add new `beforeDispatch` method to the `nodeInputRule`, `markInputRule` and `plainInputRule` parameter. This method allows users to add extra steps to the transaction after a matching input rule has been run and just before it is dispatched.
```ts
import { nodeInputRule } from 'remirror/core';
nodeInputRule({
type,
regexp: /abc/,
beforeDispatch: ({ tr }) => tr.insertText('hello'),
});
```
- Fix uneccessary lines being added to the editor when creating a new horizontal line with the commands or input rules. 
Issue: #451.
Please note that although the direct issue has been fixed, it's possible I uncovered another one. Since …
=> feat(core): add `beforeDispatch` method to input rules

.changeset/thin-jokes-fold.md, packages/@remirror/core-utils/src/prosemirror-rules.ts, packages/@remirror/extension-bold/src/__tests__/bold-extension.spec.ts, packages/@remirror/extension-bold/src/bold-extension.ts, packages/@remirror/extension-code/src/__tests__/code-extension.spec.ts, packages/@remirror/extension-code/src/code-extension.ts, packages/@remirror/extension-italic/src/__tests__/italic-extension.spec.ts, packages/@remirror/extension-italic/src/italic-extension.ts, packages/@remirror/extension-strike/src/__tests__/strike-extension.spec.ts, packages/@remirror/extension-strike/src/strike-extension.ts
Add `ignoreWhitespace` option to `markInputRule` for ignoring a matching input rule if the capture groups is only whitespace. Apply to all wrapping input rules for `MarkExtension`'s in the `project`.
- #506 `ItalicExtension` issue with input rule being greedy and capturing one extra preceding character when activated within a text block.
=> fix(extension-italic): paste and input rules

.changeset/silver-pots-shake.md, packages/@remirror/extension-positioner/src/index.ts, packages/@remirror/extension-positioner/src/positioner-extension.ts, packages/@remirror/extension-positioner/src/positioner.ts, packages/@remirror/extension-positioner/src/positioners.ts, packages/@remirror/react-social/src/components/social-editor-emoji.tsx, packages/@remirror/react/src/__tests__/editor-hooks.spec.tsx, packages/@remirror/react/src/hooks/editor-hooks.ts, support/e2e/src/positioner.e2e.test.ts
- #516 with social emoji popup when scroll bars are visible.
- Export `emptyCoords` object from `@remirror/extension-positioner`.
- Add second parameter to `usePositioner` hook which can override when a positioner should be set to active.
=> feat(react): add `usePositioner` active param

.changeset/config.json, .changeset/witty-houses-repeat.md
Required temporary fix to resolve issue with unlinked packages in prerelease mode. See the [issue](https://github.com/atlassian/changesets/issues/442) for more details.
=> fix(release): link unscoped packages

.changeset/smooth-dryers-impress.md, packages/@remirror/react/src/components/__tests__/react-editor-controlled.spec.tsx, packages/@remirror/react/src/components/__tests__/react-editor.spec.tsx, packages/@remirror/react/src/components/react-editor.tsx
Fixes `onChange` callback not being updated when using a controlled editor in `StrictMode`.
Issues: #555
=> fix(react): `onChange` callback in `StrictMode`

.changeset/tender-beers-breathe.md, packages/@remirror/extension-annotation/package.json, packages/@remirror/extension-annotation/src/index.ts, packages/@remirror/extension-annotation/src/positioners.ts, pnpm-lock.yaml
When working with annotations (extention-annotation), it's handy to have a positioner that places a popup in the middle of the selected annotation. This allows e.g. to add a popup to remove/change the annotation when the user clicks on it.
@see https://discord.com/channels/726035064831344711/745695557976195072/745697774355480606
=> Add positioner to center on a selected annotation

.changeset/rotten-foxes-judge.md, packages/@remirror/core/src/builtins/__tests__/commands-extension.spec.ts, packages/@remirror/core/src/builtins/commands-extension.ts
Add command to clear current range selection
See https://discord.com/channels/726035064831344711/726035065338986528/745695215104557126
=> Add command to clear current range selection

docs/contributing.md
I spent today - for the second time - a considerable amount of time to find out how to limit the tests to a specific package. Google pointed me consistently to the non-working `pnpm test --filter @remirror/...`.
I could imagine this to be helpful for others working their way into remirror development. Feel free to reject if you find this too obvious.
=> Document how to limit tests to a specific package

.changeset/grumpy-dolls-drop.md, packages/@remirror/core-types/src/base-types.ts, packages/@remirror/core-types/src/index.ts, packages/@remirror/core-utils/src/__tests__/prosemirror-node-utils.spec.ts, packages/@remirror/core-utils/src/core-utils.ts, packages/@remirror/core-utils/src/prosemirror-node-utils.ts, packages/@remirror/core-utils/src/prosemirror-utils.ts, packages/@remirror/core/src/builtins/__tests__/__snapshots__/schema-extension.spec.ts.snap, packages/@remirror/core/src/builtins/__tests__/schema-extension.spec.ts, packages/@remirror/core/src/builtins/keymap-extension.ts, packages/@remirror/core/src/builtins/schema-extension.ts, packages/@remirror/core/src/editor-wrapper.ts, packages/jest-remirror/src/jest-remirror-editor.ts, support/root/.eslintrc.js, support/tsconfig.main.json
🚀 Now featuring support for `DynamicExtraAttributes` which fixes #387.
- Also add support for `action` method being passed to `findChildren`, `findTextNodes`, `findInlineNodes`, `findBlockNodes`, `findChildrenByAttribute`, `findChildrenByNode`, `findChildrenByMark` and `containsNodesOfType`.
- Deprecate `flattenNodeDescendants`. `findChildren` is now the preferred method and automatically flattens the returned output.
=> Support dynamic attributes for nodes and marks

.changeset/silly-bears-hammer.md, packages/@remirror/core/src/builtins/commands-extension.ts, packages/@remirror/dom/src/__tests__/dom.spec.ts, packages/@remirror/extension-bidi/src/__tests__/__snapshots__/bidi-extension.spec.ts.snap, packages/@remirror/extension-diff/src/__tests__/__snapshots__/diff-extension.spec.ts.snap, packages/@remirror/extension-search/src/__tests__/__snapshots__/search-extension.spec.ts.snap
Fix issue with focusing the editor after every command.
Fixes #592
=> Fix focus issue when dispatching a command

.changeset/rude-brooms-refuse.md, packages/@remirror/extension-annotation/src/__tests__/annotation-extension.spec.ts, packages/@remirror/react/src/react-helpers.tsx
Remove requirement for `CorePreset` and `ReactPreset` when using the `React` framework.
Fixes #602
=> Remove error in custom react manager without core or react preset

docs/index.mdx, docs/introduction.mdx
Fixes https://github.com/remirror/remirror/issues/613
Added a note on the homepage and the first page that opens when you click "Documentation" to inform people that they should only be here if they want to be here.
=> Add link to current remirror homepage

packages/@remirror/core/src/editor-wrapper.ts
Use the result from the previous call rather than calling the same function again.
=> Avoid calling `getForcedUpdates` twice

docs/concepts/react-controlled-editor.md, docs/guide/create-editor.md
* Actually assign to the `nextState` in the controlled editor example
* Provide the required configurations to the extensions and presets
in the editor example
=> Fix issues in documentation

package.json, support/storybook/main.ts
* Explicitly switch ts-node into commonjs mode, which seems to be required by
the specific configuration of storybook here
* Disable an eslint issue about not having default exports on the main
storybook module
=> Make the storybook package start up

.changeset/three-snakes-design.md, packages/@remirror/extension-code-block/src/__tests__/__snapshots__/code-block-extension.spec.ts.snap, packages/@remirror/extension-code-block/src/__tests__/code-block-extension.spec.ts, packages/@remirror/extension-code-block/src/code-block-extension.ts, packages/@remirror/extension-code-block/src/code-block-plugin.ts, packages/@remirror/extension-code-block/src/code-block-types.ts, packages/@remirror/extension-code-block/src/code-block-utils.ts
The refractor highlighting produces two types of nodes:
* 'element' nodes indicate the type of the code snippet with the class
("token", as well as the specific thing such as "operator")
* 'text' nodes as children of the 'element' nodes that then contain the
actual text of the snippet.
Depending on the language there can also be 'text' nodes outside of the context
of an 'element' node, for example in the TypeScript language a global variable
references would simply appear as a top-level 'text' node. As there are no classes
known for these nodes they should not get a decoration.
This commit introduces an option for the code-block extension to control this
behavior:
- { plainTextClassName: undefined } (the default): top-level 'text' nodes do not get decorated
- { plainTextClassName: …
=> Prevent generating decorations without a class

.changeset/unlucky-pets-melt.md, packages/@remirror/core/src/builtins/__tests__/__snapshots__/persistent-selection-extension.spec.ts.snap, packages/@remirror/core/src/builtins/__tests__/persistent-selection-extension.spec.ts, packages/@remirror/core/src/builtins/builtin-preset.ts, packages/@remirror/core/src/builtins/index.ts, packages/@remirror/core/src/builtins/persistent-selection-extension.ts, packages/@remirror/extension-annotation/src/__tests__/annotation-extension.spec.ts, packages/@remirror/extension-bold/src/__tests__/bold-extension.spec.ts, packages/@remirror/extension-code/src/__tests__/code-extension.spec.ts, packages/@remirror/extension-strike/src/__tests__/strike-extension.spec.ts, packages/jest-remirror/src/__tests__/jest-remirror-editor.spec.ts, support/e2e/src/__snapshots__/positioner.e2e.test.ts.snap
Fixes #601 by adding a default extension to decorate the current selection, IFF the `persistentSelectionClass` builtin configuration is provided.
=> Add the persistent-selection extension

.changeset/eight-snails-hope.md, .changeset/new-apricots-travel.md, .changeset/silver-lizards-know.md, packages/@remirror/core-helpers/src/core-helpers.ts, packages/@remirror/core/src/editor-wrapper.ts, packages/@remirror/core/src/manager/remirror-manager.ts, packages/@remirror/react/src/components/__tests__/react-editor.spec.tsx, packages/@remirror/testing/package.json, packages/@remirror/testing/src/index.ts, pnpm-lock.yaml
Focus can now be used in controlled editors without overriding any previous commands.
Fixes #627
- Fix missing version bump from last release of `@remirror/core-constants`.
- Make `focus` command chainable and add `manager.tr` property for creating chainable commands. This means that the `focus` method returned by `useRemirror()` can now be safely used within a controlled editor. It uses the shared chainable transaction so that the state update does not override other state updates.
**Also**
Fix a bunch of incorrect tests `focus` tests using a mock `raf` library.
=> Make `focus` context method chainable

.changeset/big-buses-pay.md, packages/@remirror/extension-mention-atom/src/mention-atom-extension.ts
Make `mentionAtom` `selectable`.
=> Make `mentionAtom` selectable

.changeset/little-walls-drive.md, packages/@remirror/core-utils/src/core-utils.ts, packages/@remirror/core-utils/src/index.ts, packages/@remirror/core/src/editor-wrapper.ts, packages/@remirror/core/src/manager/remirror-manager.ts
Add `onError` and `stringHandler` methods to the `Remirror.ManagerSettings`.
Fixes #626
=> Add `onError` method to `Remirror.ManagerSettings`

.changeset/good-bulldogs-call.md, .changeset/happy-news-repeat.md, package.json, packages/@remirror/core-utils/src/__tests__/core-utils.spec.ts, packages/@remirror/core-utils/src/command-utils.ts, packages/@remirror/core-utils/src/core-utils.ts, packages/@remirror/core-utils/src/index.ts, packages/@remirror/extension-horizontal-rule/src/__tests__/horizontal-rule-extension.spec.ts, packages/@remirror/extension-horizontal-rule/src/horizontal-rule-extension.ts, packages/@remirror/extension-positioner/src/positioner-utils.ts
- Move `isEmptyBlockNode` function from `@remirror/extension-positioner` to `@remirror/core-utils`. Re-export to prevent breaking change.
- Fix `commands.insertHorizontalRule` inserting the line in the wrong position.
Fixes #620
=> Fix `commands.insertHorizontalRule` positioning

.changeset/cyan-beds-whisper.md, .changeset/kind-mugs-mate.md, packages/@remirror/react-hooks/src/__tests__/use-emoji.spec.tsx, packages/@remirror/react-hooks/src/use-events.ts, packages/@remirror/react-hooks/src/use-history.ts, packages/@remirror/react-hooks/src/use-keymap.ts, packages/@remirror/react-hooks/src/use-suggest.ts, packages/@remirror/react/src/hooks/__tests__/core-hooks.spec.tsx, packages/@remirror/react/src/hooks/__tests__/editor-hooks.spec.tsx, packages/@remirror/react/src/hooks/core-hooks.ts, packages/@remirror/react/src/hooks/editor-hooks.ts
- Add new signature return for `useExtension` and `usePreset`. If only provided the constructor they return a the extension or preset instance from within the manager.
- Fix issue with `useEmoji`, `useKeymap` and `useEvents` when used together with `useRemirror({ autoUpdate: true })` causing an infinite loop.
Fixes #625
=> Fix `useEmoji` with `autoUpdate` (#642

.changeset/forty-donuts-knock.md, .changeset/tall-singers-admire.md, .changeset/wise-cougars-behave.md, docs/contributing.md, packages/@remirror/core/src/builtins/keymap-extension.ts, packages/@remirror/core/src/manager/remirror-manager-helpers.ts, packages/@remirror/core/src/styles.ts, packages/@remirror/react-hooks/src/__tests__/use-keymap.spec.tsx, packages/@remirror/react-hooks/src/use-emoji.ts, packages/@remirror/react-hooks/src/use-keymap.ts, packages/@remirror/react-hooks/src/use-mention-atom.ts, packages/@remirror/react-hooks/src/use-mention.ts, packages/@remirror/react/src/hooks/editor-hooks.ts, packages/@remirror/styles/all.css, packages/@remirror/styles/core.css, packages/@remirror/styles/src/dom.tsx, packages/@remirror/styles/src/emotion.tsx, packages/@remirror/styles/src/styled-components.tsx
Add support for prioritized keymap handlers. It's now possible to make sure that a hook which consumes `useKeymap` runs before the extension keybindings.
```ts
import React from 'react';
import { ExtensionPriority } from 'remirror/core';
import { useKeymap } from 'remirror/react/hooks';
const KeymapHook = () => {
// Make sure this keybinding group is run first!
useKeymap({ Enter: () => doSomething() }, ExtensionPriority.Highest);
// This one we don't care about 🤷‍♀️
useKeymap({ 'Shift-Delete': () => notImportant() }, ExtensionPriority.Lowest);
return <div />;
};
```
- By default hooks the hooks from `remirror/react/hooks` which consume `useKeymap are given a priority of`ExtensionPriority.High`.
- `useKeymap` is given a priority of `ExtensionPriority.Medium`.
- The `createKeymap` method on …
=> Add prioritization to `useKeymap` hook

.changeset/forty-donuts-knock.md, .changeset/odd-ants-wait.md, packages/@remirror/core/src/index.ts, packages/@remirror/extension-annotation/readme.md, support/base.babel.js
TypeScript 4.0.2 is now the minimum supported version.
=> Add minimum supported TypeScript version

.changeset/moody-ants-drive.md, docs/concepts/extension.md, packages/@remirror/core-types/src/annotation-types.ts, packages/@remirror/core-types/src/base-types.ts, packages/@remirror/core-types/src/index.ts, packages/@remirror/core/src/builtins/persistent-selection-extension.ts, packages/@remirror/core/src/decorators.ts, packages/@remirror/core/src/extension/base-class.ts, packages/@remirror/extension-history/src/history-extension.ts
Add `AcceptUndefined` annotation which allows options to accept undefined as their default value.
Fixes #624
=> New `AcceptUndefined` annotation for `Options`

.changeset/thick-pianos-wink.md, docs/concepts/error-handling.md, docs/concepts/extra-attributes.md, packages/@remirror/core/src/builtins/__tests__/schema-extension.spec.ts, packages/@remirror/core/src/builtins/commands-extension.ts, packages/@remirror/core/src/builtins/schema-extension.ts, packages/@remirror/core/src/manager/remirror-manager-helpers.ts, packages/@remirror/extension-paragraph/src/paragraph-extension.ts, packages/@remirror/i18n/src/__tests__/plurals.spec.ts, support/website/sidebars.js
🎉 Brings support for adding extra attributes to the `RemirrorManager` via extension tags. Attributes can now be added to all nodes and marks with a specific tag like `ExtensionTag.Alignment` or `ExtensionTag.NodeBlock`. Every matching tag in the `Schema` receives the extra attributes defined.
With tags, you can select a specific sub selection of marks and nodes. This will be the basis for adding advanced formatting to remirror.
```ts
import { ExtensionTag } from 'remirror/core';
import { createCoreManager, CorePreset } from 'remirror/preset/core';
import { WysiwygPreset } from 'remirror/preset/wysiwyg';
const manager = createCoreManager(() => [new WysiwygPreset(), new CorePreset()], {
extraAttributes: [
{
identifiers: {
tags: [ExtensionTag.NodeBlock],
// Can be limited by type to `node | …
```
=> Support adding extra attributes by `tags`

.changeset/early-points-grab.md, .changeset/fresh-singers-march.md, .changeset/smooth-readers-collect.md, .changeset/weak-dodos-fry.md, packages/@remirror/core-types/src/core-types.ts, packages/@remirror/core-types/src/index.ts, packages/@remirror/core-utils/src/__tests__/command-utils.spec.ts, packages/@remirror/core-utils/src/command-utils.ts, packages/@remirror/core-utils/src/core-utils.ts, packages/@remirror/react-hooks/src/use-suggest.ts, packages/@remirror/react/src/components/__tests__/react-editor.spec.tsx, packages/@remirror/react/src/hooks/core-hooks.ts, packages/@remirror/react/src/index.ts, packages/jest-prosemirror/src/jest-prosemirror-editor.ts, packages/jest-prosemirror/src/jest-prosemirror-nodes.ts, packages/jest-remirror/src/jest-remirror-editor.ts, support/e2e/src/social.e2e.test.ts
- **BREAKING**: 💥 Remove export of `useSetState` and use default `useState` instead.
- Fix editable mentions support for exiting when text is selected. Also update `getSelection` to support `anchor` and `head` selections.
- Add new `AnchorHeadParameter` export and make it a part of `PrimitiveSelection` type.
- Add support for `anchor` and `head` cursors when writing tests. Also fix `selectText` when position is `0`.
Fixes #640
=> Support exiting mentions with text selected

.changeset/chilled-rats-join.md, .changeset/great-pans-do.md, .changeset/honest-kids-search.md, .changeset/neat-worms-applaud.md, packages/@remirror/core-constants/src/core-constants.ts, packages/@remirror/core/src/builtins/__tests__/keymap-extension.spec.ts, packages/@remirror/core/src/builtins/builtin-preset.ts, packages/@remirror/core/src/builtins/input-rules-extension.ts, packages/@remirror/core/src/builtins/keymap-extension.ts, packages/@remirror/core/src/builtins/tags-extension.ts, packages/@remirror/core/src/extension/extension-base.ts, packages/@remirror/dom/src/dom.ts, packages/@remirror/extension-code/src/code-extension.ts, packages/jest-prosemirror/src/jest-prosemirror-editor.ts, packages/jest-prosemirror/src/jest-prosemirror-nodes.ts, packages/jest-remirror/src/__tests__/jest-remirror-editor.spec.ts, packages/jest-remirror/src/jest-remirror-editor.ts
Add `MarkSupportsExit` tag to `ExtensionTag` constant export.
Add `KeymapExtension` option `exitMarksOnArrowPress` which allows the user to exit marks with the `MarkSupportExit` tag from the beginning or the end of the document.
Store tags as `markTags`, `nodeTags`, `plainTags` and deprecate the helper methods which were previously doing this.
Add `extraTags` option to the extension and `RemirrorManager` now extra can be added as part of the configuration.
- Support lazy functions which return an extension list in the `createDomManager`.
- Fix `node` cursor selection. Now it selects the right node position in `jest-remirror`.
- Add support for exiting code mark at the end of a block node.
Fixes #636
=> Support exiting inline marks in block nodes

.changeset/honest-beans-poke.md, .changeset/nice-dolphins-teach.md, packages/@remirror/dom/src/dom-framework.ts, packages/@remirror/preset-table/src/__tests__/table-preset.spec.ts, packages/@remirror/preset-table/src/table-extensions.ts
- Add `tr` and `transactions` property to `onStateUpdate` for DOM framework implementation.
- Fix broken `TableExtension` lifecycle method for `onStateUpdate`. Fixes #677.
Fixes #677
=> Fix `onStateUpdate` method for `TablePreset`

.changeset/lemon-ducks-breathe.md, packages/@remirror/extension-annotation/src/__tests__/annotation-extension.spec.ts, packages/@remirror/extension-annotation/src/__tests__/segments.spec.ts, packages/@remirror/extension-annotation/src/actions.ts, packages/@remirror/extension-annotation/src/annotation-extension.ts, packages/@remirror/extension-annotation/src/annotation-plugin.ts, packages/@remirror/extension-annotation/src/segments.ts, packages/@remirror/extension-annotation/src/types.ts, packages/@remirror/extension-annotation/src/utils.ts, support/storybook/stories/annotation.stories.tsx
The annotation-extension would allow to style individual annotations via a CSS class. This led to issues with overlapping annotations. For example, if an annotation with a red background and another with a green background were overlapping, the editor would show (more or less) randomly one of the two colors.
Now, the annotation-extension allows users to style decorations based on all overlapping annotations within a given decoration. The default implementation visualizes overlapping annotations by showing a darker shade the more annotations are overlapping.
The approach was confirmed by Marijn: https://discuss.prosemirror.net/t/how-to-style-overlapping-inline-decorations/3162
=> Style overlapping annotations

.changeset/rare-chefs-eat.md, packages/@remirror/extension-annotation/src/__tests__/annotation-extension.spec.ts, packages/@remirror/extension-annotation/src/annotation-extension.ts
The styling method `getStyle` could already handle custom annotations, e.g. annotations that contain a custom `color` property. Yet, the Typescript declaration didn't expose this.
This PR exposes the functionality via Typescript and adds a test case, demonstrating how to use it.
=> Support custom annotations for custom styling

.changeset/nice-mugs-smash.md, .changeset/popular-frogs-count.md, .changeset/quick-rings-jump.md, .changeset/young-schools-remain.md, docs/concepts/error-handling.md, packages/@remirror/core/src/builtins/builtin-preset.ts, packages/@remirror/core/src/builtins/commands-extension.ts, packages/@remirror/core/src/builtins/helpers-extension.ts, packages/@remirror/core/src/extension/extension-base.ts, packages/@remirror/react/src/hooks/editor-hooks.ts, packages/multishift/src/index.ts, packages/multishift/src/multishift-action-creators.ts, packages/multishift/src/multishift-types.ts, packages/multishift/src/multishift.ts
- **BREAKING:** 💥 Rename `Remirror.All` to `Remirror.AllExtensionUnion`.
- 🎉 Add `findPositionerTracker`, `findAllPositionTrackers` and `isSelectionEmpty` to builtin helpers.
- Add `Remirror.AllExtensionUnion` to the `useRemirror` hook. Now the commands and helpers for all extensions should automatically discover their API's.
- Fix global type not being imported automatically.
=> Various small changes

.changeset/cyan-lizards-reflect.md, packages/@remirror/extension-annotation/src/__tests__/annotation-extension.spec.ts, packages/@remirror/extension-annotation/src/annotation-plugin.ts
Users can create annotations on pieces of content. The annotations are automatically updated as the content is moved around, e.g. if a new word is inserted before the annotation.
Yet, the extension missed the case that all annotated content is deleted. Before, this would lead to an empty annotation (to and from parameter are equal). With this commit, annotations are automatically removed when the content is completed deleted.
=> Remove annotations when their content is deleted

.changeset/little-crabs-beam.md, packages/@remirror/extension-annotation/src/__tests__/annotation-extension.spec.ts, packages/@remirror/extension-annotation/src/annotation-extension.ts
Annotations are loaded separately from the content into the editor (`helpers.setAnnotations` vs `setContent`). This can lead to situations where annotations are pointing to positions that are outside the content. For example, the editor shows content with annotations. Then, the user requests to change the content to an empty document. At this point, until `helpers.setAnnotations()` is called, the editor will have an empty document but still a list of annotations.
At that point, `helpers.getAnnotations()` would throw the following error because it couldn't find the matching text for the from/to positions:
```
TypeError: Cannot read property 'nodeSize' of undefined
```
=> Gracefully handle annotations with positions outside the content

.changeset/loud-pandas-happen.md, .changeset/slow-lobsters-tickle.md, packages/@remirror/core-utils/src/__tests__/core-utils.spec.ts, packages/@remirror/core-utils/src/__tests__/prosemirror-node-utils.spec.ts, packages/@remirror/core-utils/src/core-utils.ts, packages/@remirror/core-utils/src/index.ts, packages/@remirror/core-utils/src/prosemirror-node-utils.ts, packages/@remirror/core-utils/src/prosemirror-utils.ts, packages/@remirror/extension-code-block/src/code-block-extension.ts, packages/@remirror/extension-code-block/src/code-block-plugin.ts, packages/@remirror/extension-code-block/src/code-block-utils.ts
- Improve performance of the `CodeBlockExtension` by only updating syntax highlighting for the changed code block(s).
- Add new helpers `getChangedRanges`, `getChangedNodeRanges` and `getChangedNodes` which take a transaction and return a list of changed ranges, node ranges or nodes with positions.
This is useful for increasing the performance and only checking the parts of the document that have changed between updates.
=> Improve performance of `CodeBlockExtension`

.changeset/itchy-colts-tap.md, packages/@remirror/extension-annotation/src/positioners.ts, support/storybook/stories/annotation.stories.tsx
The annotation positioner placed the bottom on the bottom of the first line. This meant that a popup placed on the bottom would overlay the rest of a multi-line annotation. Now, the positioner returns the bottom of the last line, allowing to place the popup below all content.
This commit contains also an addition to the storybook to actually see the problem (as there aren't any unit tests for positioners today).
=> Fix bottom value for multi-line annotations in positioner

.changeset/orange-stingrays-occur.md, packages/@remirror/extension-annotation/src/__tests__/annotation-extension.spec.ts, packages/@remirror/extension-annotation/src/annotation-plugin.ts
Annotations auto-adjust as users enter content, e.g. an annotation grows if the user types in the middle of the annotation.
Incorrectly, the annotation also grew when the user added content directly after the annotation. Now, this leads to new, non-annotated content.
=> Fix: Don't extend annotation when typing at end of annotation

.changeset/stupid-glasses-end.md, packages/@remirror/core-utils/src/__tests__/core-utils.spec.ts, packages/@remirror/core-utils/src/core-utils.ts
Add `text` property to the return value from `getMarkRange`. It's a common use case when getting the range of the mark to also extract the text content.
=> Extract text from mark range

.changeset/dull-chicken-decide.md, .changeset/hungry-suits-agree.md, .changeset/khaki-cups-pretend.md, packages/@remirror/extension-annotation/src/__tests__/annotation-extension.spec.ts, packages/@remirror/extension-annotation/src/annotation-extension.ts, packages/@remirror/extension-code-block/src/code-block-utils.ts, packages/@remirror/extension-image/src/__tests__/image-extension.spec.ts, packages/@remirror/extension-image/src/image-extension.ts
- Make `insertImage` command chainable.
- Make `formatCodeBlock` command chainable.
- Make annotation commands chainable.
Fixes #724
Fixes #726
=> Make `insertImage` command chainable

.changeset/forty-numbers-jam.md, packages/@remirror/extension-annotation/src/__tests__/annotation-extension.spec.ts, packages/@remirror/extension-annotation/src/actions.ts, packages/@remirror/extension-annotation/src/annotation-extension.ts, packages/@remirror/extension-annotation/src/annotation-plugin.ts
Annotations can be styled with a custom getStyle function. Yet, changes to outcome of the function (e.g. color schema is dynamically adjusted) won't be automatically reflected in the editor.
To handle such cases, one can now force to redraw the annotations by calling the `redrawAnnotations` command.
=> Support forcefully redrawing annotations

.changeset/fifty-deers-ring.md, packages/jest-remirror/src/jest-remirror-validator.ts
=> Remove `endsWith` from `ValidityTest`s

.changeset/dry-chairs-decide.md, packages/@remirror/extension-events/src/__tests__/events-extension.spec.ts, packages/@remirror/extension-events/src/events-extension.ts
Adds support for `mousedown` and `mouseup` events in @remirror/extension-events
```jsx
import { EventsExtension } from 'remirror/extension/events';
import { useExtension } from 'remirror/react';
const Editor = () => {
useExtension(
EventsExtension,
({ addHandler }) => {
addHandler('mousedown', () => log('Mouse down!'));
},
[],
);
};
```
=> Add `mousedown` and `mouseup` handlers to `EventsExtension`

.changeset/famous-tips-march.md, packages/@remirror/core/src/builtins/__tests__/schema-extension.spec.ts, packages/jest-prosemirror/src/__tests__/__snapshots__/jest-prosemirror.spec.ts.snap, packages/jest-prosemirror/src/jest-prosemirror-schema.ts
The schema provided by `jest-prosemirror` does not include the strike mark. This PR adds it.
=> Add strike mark to the jest-prosemirror schema

.changeset/swift-ears-draw.md, packages/@remirror/extension-annotation/src/__tests__/annotation-extension.spec.ts, packages/@remirror/extension-annotation/src/annotation-extension.ts, packages/@remirror/extension-annotation/src/types.ts
`getAnnotations()` returns all currently set annotations and enriches them with the text of the annotation. This can be used e.g. to show a list of all annotations outside the editor context.
Before, text from multiple blocks (in a multi-block annotation) was concatenated without any separated. Now, one can define via the `blockseparator` option which string to use as separator. For example, one could use a newline character to separate text from different blocks.
=> Add `blockSeparator` option for multi-block annotations

.changeset/large-ligers-begin.md, .changeset/pretty-rice-sneeze.md, .changeset/tame-shirts-wonder.md, .github/workflows/label-sponsors.yml, packages/@remirror/extension-positioner/src/positioner.ts, packages/@remirror/extension-yjs/package.json, packages/@remirror/extension-yjs/readme.md, packages/@remirror/extension-yjs/src/__tests__/yjs-extension.spec.ts, packages/@remirror/extension-yjs/src/yjs-extension.ts, packages/@remirror/react-hooks/src/__tests__/use-mention-atom.spec.tsx, packages/@remirror/react-hooks/src/use-mention-atom.ts, packages/remirror/package.json, pnpm-lock.yaml, support/website/src/pages/playground.tsx
Support scroll updates by default for all positioners.
Add new options to the `YjsExtension` to support full configuration of the `y-prosemirror` plugins.
- Fixes #742
**BREAKING:** 💥 Remove `WebrtcProvider`. It was always required via TypeScript but now the default implementation throws an error if you don't install and provide the [provider](https://github.com/yjs/yjs#providers) you want to use. The `readme` has been updated to reflect this change.
**BREAKING:** 💥 `yjs` is now a `peerDependency` and you will need to install it in your codebase in order to consume the `YjsExtension`. This change follows from the above breaking change. For example, to configure any provider will need to provide your desired `Doc` from the `yjs` package.
Fix bug in `useMentionAtom` where asynchronous …
=> Allow sync options to be passed to yjs extension

.changeset/empty-hats-teach.md, .changeset/selfish-drinks-design.md, packages/@remirror/core-utils/src/environment.ts, packages/@remirror/core/src/framework/framework.ts
Fixes #261
Add better **iOS** focus support. Now using `focus` on iOS will actually focus the editor.
- Fixes #261
- Add `isIos` environment flag.
`iOS` still won't support focus when the user hasn't interacted with the browser yet.
=> Add better support for `autoFocus: true` on iOS support

.changeset/lemon-berries-pretend.md, packages/@remirror/extension-link/src/__tests__/link-extension.spec.ts, packages/@remirror/extension-link/src/link-extension.ts, packages/@remirror/preset-wysiwyg/src/wysiwyg-preset.ts
Adds an event to the link extension to detect when links are added/updated.
I decided not to change the `onLinkActivated` event as that seems to have auto selection behaviour that I didn't want to break.
=> Add an `onUpdateLink` event handler to the `LinkExtension`

.changeset/rotten-maps-clean.md, .changeset/soft-boxes-mate.md, .changeset/tasty-drinks-camp.md, packages/@remirror/core-utils/src/prosemirror-utils.ts, packages/@remirror/extension-mention/src/mention-extension.ts, packages/@remirror/extension-positioner/src/positioners.ts, packages/@remirror/react-hooks/src/__tests__/use-mention.spec.tsx, packages/@remirror/react-hooks/src/use-mention.ts, packages/@remirror/react-social/src/social-utils.ts, packages/prosemirror-suggest/src/__tests__/suggest-plugin.spec.ts, packages/prosemirror-suggest/src/suggest-types.ts, packages/prosemirror-suggest/src/suggest-utils.ts, support/root/.eslintrc.js, support/website/package.json
- Support `EditorState | Selection | ResolvedPos` for the `findParentNodeOfType` function.
- Pass through `defaultAppendTextValue` property to `onChange` handler of `MentionExtension`.
- Don't append text to `useMention` hook command when content after starts with whitespaces.
Fixes #752
=> Prevent extra space when reselecting mentions 

packages/jest-remirror/readme.md
As per the deprecation notice, and the fact that https://github.com/remirror/remirror/blob/7a52b28f4137f1ed11e6473ac5701dd1d081a9aa/packages/jest-remirror/src/jsdom-polyfills.ts#L39-L47 is empty anyways.
=> Remove references to the deprecated `jsdomExtras()`

.changeset/green-frogs-know.md, packages/@remirror/extension-link/src/__tests__/link-extension.spec.ts, packages/@remirror/extension-link/src/link-extension.ts
This fixes some inconsistent behaviour when using the `LinkExtension` with `autoLink: true`.
Pasting a link *without* `www.` prefix - `updateLink` command called, and `onUpdateLink` event fired
Pasting a link *with* `www.` prefix - `updateLink` command **not** called, and `onUpdateLink` event not fired
This is because the link created via the [paste rule](https://github.com/remirror/remirror/blob/next/packages/@remirror/extension-link/src/link-extension.ts#L245) was deemed to have [no changes](https://github.com/remirror/remirror/blob/next/packages/@remirror/extension-link/src/link-extension.ts#L438-L446) and would bail out before calling `updateLink`.
This change prevents the paste rule from being applied, if `autoLink` is enabled, as auto linking will create the link regardless.
I have …
=> Avoid `LinkExtension` `pasteRules` when `autoLink` enabled

.changeset/honest-birds-do.md, packages/@remirror/extension-link/src/__tests__/link-extension.spec.ts, packages/@remirror/extension-link/src/link-extension.ts, support/storybook/stories/link-extension.stories.tsx
Anchor tags in contenteditable are not clickable by default. To allow users nonetheless to open them, this commit adds an optional clickhandler to open the link.
=> Allow links to be clickable

.changeset/warm-pugs-unite.md, packages/@remirror/extension-callout/src/__tests__/callout-extension.spec.ts, packages/@remirror/extension-callout/src/callout-extension.ts, packages/@remirror/playground/src/_remirror.tsx
Given this scenario, pressing `backspace` would merge two callout nodes
**Before**: 
**After**:
=> Prevent merging callouts, when deleting content in between callout nodes

docs/concepts/extra-attributes.md, packages/@remirror/core-utils/src/core-utils.ts, packages/@remirror/core-utils/src/index.ts, packages/@remirror/core/src/builtins/schema-extension.ts, packages/@remirror/extension-auto-link/src/auto-link-extension.ts, packages/@remirror/extension-callout/src/callout-extension.ts, packages/@remirror/extension-image/src/image-extension.ts, packages/@remirror/extension-link/src/link-extension.ts, packages/@remirror/extension-mention-atom/src/mention-atom-extension.ts, packages/@remirror/preset-embed/src/iframe-extension.ts
This fixes `NodeExtension`s that have attributes and were spreading the `node.attrs` without omitting extra attributes. 
This results in extra attributes being render to the DOM twice, firstly using their `toDOM` handler, and secondly using their raw name/value
Example
```ts
const linkExtension = new LinkExtension({
extraAttributes: {
custom: {
default: 'my default',
parseDOM: (dom) => dom.getAttribute('data-custom'),
toDOM: (attrs) => (['data-custom', attrs.custom]),
},
},
});
```
Resulted in
```html
<a
data-custom="my default"
custom="my default"                   <-- extra attribute rendered in raw form
href="https://remirror.io"
rel="noopener noreferrer nofollow">
```
This PR also correct some documentation/comments regarding extra attributes
=> Prevent raw extra attributes being rendered to the DOM

.changeset/real-dancers-search.md, packages/@remirror/core-utils/src/__tests__/command-utils.spec.ts, packages/@remirror/core-utils/src/command-utils.ts, packages/@remirror/extension-link/src/__tests__/link-extension.spec.ts
Fix `updateMark` so it returns `false` if the mark cannot be applied to the selection or range
=> Fix `updateMark` to return `false` when not applicable

.changeset/long-phones-enjoy.md, .changeset/tall-countries-wait.md, .github/workflows/ci.yml, package.json, packages/@remirror/core-utils/src/core-utils.ts, packages/@remirror/core/src/index.ts, packages/@remirror/dev/readme.md, packages/@remirror/extension-annotation/src/annotation-extension.ts, packages/@remirror/extension-annotation/src/annotation-plugin.ts, packages/@remirror/extension-callout/src/callout-types.ts, packages/@remirror/extension-codemirror/src/codemirror-node-view.ts, packages/@remirror/extension-history/src/history-extension.ts, packages/@remirror/extension-link/src/__tests__/link-extension.spec.ts, packages/@remirror/extension-yjs/src/__tests__/__snapshots__/yjs-extension.spec.ts.snap, packages/@remirror/extension-yjs/src/__tests__/yjs-extension.spec.ts, packages/@remirror/extension-yjs/src/index.ts, packages/@remirror/extension-yjs/src/yjs-extension.ts, packages/@remirror/react/src/hooks/__tests__/editor-hooks.spec.tsx, packages/@remirror/react/src/react-providers.tsx, packages/jest-prosemirror/src/jest-prosemirror-schema.ts, support/root/jest.config.js
- Export `PrioritizedKeyBindings` from '@remirror/core`and`remirror/core` entrypoints.
- Fix problems around destroying the `YjsExtension` provider and the `CMD+SHIFT+Z` keymap not registering as mentioned in [#772](https://github.com/remirror/remirror/issues/772).
Closes #772
=> Fix `YjsExtension` redo keybinding

.changeset/tidy-files-guess.md, packages/@remirror/extension-mention-atom/src/mention-atom-extension.ts
- Make `draggability` configurable for `MentionAtomExtension` as mentioned in [#777](https://github.com/remirror/remirror/issues/777).
Closes #777
=> Make `draggability` configurable for atom mentions

.changeset/hot-olives-obey.md, packages/@remirror/core-utils/src/__tests__/command-utils.spec.ts, packages/@remirror/core-utils/src/command-utils.ts
Fix `removeMark` when called with `dispatch = undefined`. This means that `command.<NAME>.isEnabled()` checks should all be fixed if they are using `removeMark` as mentioned in [#784](https://github.com/remirror/remirror/issues/784).
Closes #784
=> Fix `removeMark` when `dispatch=undefined`

.changeset/happy-olives-care.md, .changeset/silly-hairs-live.md, .changeset/sour-oranges-agree.md, packages/@remirror/core-utils/src/command-utils.ts, packages/@remirror/core-utils/src/core-utils.ts, packages/@remirror/core/src/builtins/commands-extension.ts, packages/@remirror/extension-code-block/src/__tests__/code-block-extension.spec.ts
Improve type signatures of command utility functions to also include an optional range.
Add new primitive commands to `CommandsExtension`.
- `setBlockNodeType`
- `toggleWrappingNode`
- `toggleBlockNodeItem`
- `wrapInNode`
- `removeMark`
Fix `getChangedNodeRanges` when resolving content that may no longer be within the range of the full document. This addresses the issues raised in [#797](https://github.com/remirror/remirror/issues/797) and [#764](https://github.com/remirror/remirror/issues/764).
- Closes #797
- Closes #764
=> fix: input rules combined with codeblock

packages/@remirror/playground/package.json, packages/@remirror/playground/scripts/import-remirror.ts, packages/@remirror/playground/src/_remirror.tsx
To emulate SSR, we need `renderToString` (or similar) from `react-dom/server`; this PR adds that to the imports. It also fixes the broken `import-remirror` script in the playground.
Remirror SSR isn't working right now, this PR does not attempt to fix that.
Here's an example of SSR code you can run in the browser (which shows Remirror not SSR-ing):
```ts
import { useRemirrorPlayground } from "@remirror/playground";
import React, { FC } from "react";
import { renderToString } from "react-dom/server";
import { BoldExtension } from "remirror/extension/bold";
import { RemirrorProvider, useManager, useRemirror } from "remirror/react";
const EXTENSIONS = () => [new BoldExtension()];
/**
* This component contains the editor and any toolbars/chrome it requires.
*/
const SmallEditor: FC = () => { …
```
=> fix(playground): enable importing react-dom/server

.changeset/fast-feet-pretend.md, .changeset/four-gorillas-allow.md, .changeset/modern-panthers-float.md, .changeset/six-kiwis-double.md, .changeset/violet-dolphins-tickle.md, packages/@remirror/core-utils/src/core-utils.ts, packages/@remirror/core-utils/src/index.ts, packages/@remirror/core/src/builtins/commands-extension.ts, packages/@remirror/extension-events/src/__tests__/events-extension.spec.ts, packages/@remirror/extension-events/src/events-extension.ts, packages/@remirror/extension-events/src/index.ts, packages/@remirror/extension-link/package.json, packages/@remirror/extension-link/src/__tests__/link-extension.spec.ts, packages/@remirror/extension-link/src/index.ts, packages/@remirror/extension-link/src/link-extension.ts, packages/@remirror/extension-mention-atom/package.json, packages/@remirror/extension-mention-atom/src/__tests__/mention-atom-extension.spec.ts, packages/@remirror/extension-mention-atom/src/mention-atom-extension.ts, packages/@remirror/extension-mention/package.json, packages/@remirror/extension-mention/src/__tests__/mention-extension.spec.ts, packages/@remirror/extension-mention/src/mention-extension.ts, pnpm-lock.yaml
Add `click` and `clickMark` handlers to the `EventsExtension`. These new events are available to hooks created with `useExtension(EventsExtension)` and also exposed via the new `createEventHandlers` extension method. These methods provides utilities for determining whether the position clicked was within a specific node or mark.
- Closes #796
Add `onClick` handler to `LinkExtension` which is called with the `event: MouseEvent` and `data: LinkClickData` which includes the `href` and all the `GetMarkRange` properties.
Export extra types from the `@remirror/extension-link` package.
- `LinkAttributes`
- `LinkClickData`
- `DefaultProtocol`
Add `onClick` handler to `MentionAtomExtension` which is called with the `event: MouseEvent` and `nodeWithPosition: NodeWithPosition`.
Add `onClick` handler …
=> feat(core-utils): export `GetMarkRange` interface

package.json, pnpm-lock.yaml
This PR include `cross-env` into dependencies to fix `cross-env-shell: command not found` issue. I found this issue when I developed the previous PR. 
```
$ git checkout next
Switched to branch 'next'
Your branch is up to date with 'origin/next'.
husky > post-checkout (node v15.2.1)
sh: cross-env-shell: command not found
sh: cross-env-shell: command not found
```
=> chore: add `cross-env` into dependencies

.changeset/thick-mails-jump.md, packages/@remirror/extension-positioner/src/__tests__/positioner-extension.spec.ts, packages/@remirror/extension-positioner/src/positioner-extension.ts
Positioners previously required a state change to take place, before they were displayed. This PR adds a force update so that positioners can be displayed immediately (if applicable)
=> fix(extension-positioner): display positioners immediately

.changeset/hip-hairs-mix.md, packages/@remirror/extension-link/src/__tests__/link-extension.spec.ts, packages/@remirror/extension-link/src/link-extension.ts
Fix rendered HTML when selecting or applying marks to part of a link.
Given the use case of
Behaviour before fix.
```html
<p>
<a href="/">My partially</a>
<a href="/"><span class="selection">selected</span></a>
<a href="/">link</a>
</p>
```
Behaviour after fix.
```html
<p>
<a href="/">
My partially
<span class="selection">selected</span>
link
</a>
</p>
```
=> fix(extension-link): improve rendered html

.changeset/brave-nails-switch.md, packages/@remirror/core/src/manager/remirror-manager.ts, packages/@remirror/extension-events/src/__tests__/events-extension.spec.ts
Allow access to `extension.store.currentState` before the first state update.
Closes #814
=> fix(core): allow `currentState` before first update

.changeset/two-tables-end.md, packages/@remirror/core-utils/src/__tests__/core-utils.spec.ts, packages/@remirror/core-utils/src/core-utils.ts
If marks are mixed then `getMarkRange` does not return the entire mark length, instead stopping at the first change in mark (see included test). Fixing this should resolve the infinite loop I described seeing here https://github.com/remirror/remirror/issues/823
=> fix: `getMarkRange` usage with mixed marks

.changeset/few-olives-walk.md, .changeset/good-queens-tan.md, .changeset/smart-pots-thank.md, .changeset/tame-items-turn.md, docs/errors.md, packages/@remirror/core-constants/src/error-constants.ts, packages/@remirror/core-helpers/src/core-errors.ts, packages/@remirror/core-utils/src/__tests__/core-utils.spec.ts, packages/@remirror/core-utils/src/command-utils.ts, packages/@remirror/core-utils/src/core-utils.ts, packages/@remirror/core-utils/src/index.ts, packages/@remirror/core-utils/src/prosemirror-utils.ts
Add `getActiveNode` function which returns the information for an active node of the provided type.
Rename deprecated error constant from `COMMANDS_CALLED_IN_OUTER_SCOPE` to `SCHEMA`.
Add `getMarkRanges` which supports retrieving all the mark ranges from within the provided selection.
Preserve attributes when toggling a block node. This allows for better support when using `extraAttributes` and fixes [#819](https://github.com/remirror/remirror/issues/819).
Fixes #819
=> fix: preserve attributes for `toggleBlockItem` and `setBlockType`

.changeset/late-days-tease.md, packages/@remirror/extension-image/src/image-extension.ts
Without the anchoring, the regexp would unintentionally match things like `application/vnd.fastcopy-disk-image` and `application/vnd.oasis.opendocument.image`.
=> fix(extension-image): fix regexp for image filetype

support/storybook/stories/annotation.stories.tsx
Annotations are stored in a separate data structure from the editor content. It's helpful to see them not only visualized in the editor but see also the expected JSON. Showing the internal state transports a clearer idea how annotations work and eases testing/debugging of annotation corner cases.
=> chore: visualize internal state in annotation storybook

packages/@remirror/react-hooks/src/use-emoji.ts
I noticed while using the `useEmoji` hook with the `SocialEmojiComponent`  that when I click an emoji, the `state` persisted and the `SocialEmojiComponent` was left open even after selecting an emoji. As I started to look at the code, I noticed that `command` never sets the state to `null` for the `useEmojiChangeHandler`, and found that `setState` was called after the `return` in the `command`. 
This PR rearranges the `return` and call to `setState` so that the `state` is set to `null`.
in the source code, `setState` was being called after `return` in the `useEmojiChangeHandler` `command` handler. 
That meant `setState` was unreachable and was stripped in the distributed files.
Not calling `setState` led to a situation where using the `SocialEmojiComponent` would remain open even after …
=> fix: call setState in command in useEmoji

.changeset/loud-mirrors-peel.md, packages/@remirror/preset-embed/package.json, packages/@remirror/preset-embed/src/iframe-extension.ts, pnpm-lock.yaml
The "type" attribute for the iframe-extension indicates the kind of embed. Before, the attribute would allow only for values "youtube" and "custom" (youtube being supported natively by the iframe-extension).
This commit allows to set the "type" to any string. With this, one can distinglish between different kinds of custom embeds like "google-drive" vs. "vimeo".
This change is backwards-compatible.
Discussed here: https://discord.com/channels/726035064831344711/745695521305526302/80403347018298163
=> feat(embed): set custom value for "type" of iframe embeds

package.json, pnpm-lock.yaml
I found that in Github Codespace, the git hooks don't work well because of `cross-env-shell: not found`. 
```bash 
node ➜ ~/workspace/remirror (beta) $ git checkout -b fix_deps
Switched to a new branch 'fix_deps'
husky > post-checkout (node v14.15.4)
sh: 1: sh: 1: cross-env-shell: not foundcross-env-shell: not found
husky > post-checkout hook failed (cannot be bypassed with --no-verify due to Git specs)
```
*BTW, when I wrote this PR, I just found out that `cross-env` was in [maintenance mode](https://github.com/kentcdodds/cross-env/issues/257). `cross-env` will continue to support the latest Node.js version as we as to fix security/critical bugs, so it should be ok to continue to use it. I just post this as a small piece of news.*
=> chore(deps): add missing dependency cross-env

.changeset/tiny-buttons-repair.md, package.json, packages/remirror__core/__tests__/__snapshots__/remirror-manager.spec.tsx.snap, packages/remirror__core/__tests__/remirror-manager.spec.tsx, packages/remirror__core/src/manager/remirror-manager.ts, packages/testing/src/tsconfig.json
Initialize the `Extension#store` property with a `previousState` of `undefined` to prevent a crash in certain conditions. 
Closes #863
=> fix(core): initialize `previousState` for `store`

.changeset/neat-snakes-sell.md, .changeset/thirty-poems-rescue.md, packages/remirror__extension-yjs/package.json, pnpm-lock.yaml
Add missing `y-protocols` dependency for `remirror` package.
=> fix(extension-yjs): add required `y-protocols`

.changeset/kind-houses-protect.md, packages/remirror__extension-annotation/src/annotation-plugin.ts
Fixes https://github.com/remirror/remirror/issues/874
Deleting text kept enclosed annotations with a negative length (`to=0`). This PR deletes the annotations for good.
=> fix(extension-annotation): delete text and annotations

.changeset/clean-rings-flash.md, packages/remirror__react-renderer/__tests__/code-block.spec.tsx, packages/remirror__react-renderer/__tests__/renderer.spec.tsx, packages/remirror__react-renderer/__tests__/text.spec.tsx, packages/remirror__react-renderer/__tests__/tsconfig.json, packages/remirror__react-renderer/src/handlers/code-block.tsx, packages/remirror__react-renderer/src/handlers/index.ts, packages/remirror__react-renderer/src/handlers/text.tsx, packages/remirror__react-renderer/src/index.ts, packages/remirror__react-renderer/src/renderer.tsx, packages/remirror__react-renderer/src/types.ts, support/root/tsconfig.json
Before, it was hard to add further node renderer to RemirrorRenderer. Users couldn't use the existing node renderer like TextHandler and CodeBlock because they weren't exported.
This PR simplifies composing a static renderer for the user's needs by exporting the renderers and the interface required to write custom node renderers.
I tried to preserve the different steps as separate commits. They are intended to be squashed before merge.
=> feat(react-renderer): make composable

.changeset/twelve-berries-greet.md, packages/remirror__react-renderer/__tests__/heading.spec.tsx, packages/remirror__react-renderer/__tests__/iframe.spec.tsx, packages/remirror__react-renderer/__tests__/link.spec.tsx, packages/remirror__react-renderer/src/handlers/heading.tsx, packages/remirror__react-renderer/src/handlers/iframe.tsx, packages/remirror__react-renderer/src/handlers/link.tsx, packages/remirror__react-renderer/src/renderer.tsx
Added support for some common node types and marks.
The iframe and link handler can be parameterized to change the visualization vs the node attributes in RemirrorJSON. For example, it allows to open links in a new tab or set the iframe to a specific width/height (independently of how this was entered in the editor).
=> feat(react-renderer): support static heading, iframe & link

.changeset/funny-schools-swim.md, packages/remirror__react-renderer/__tests__/heading.spec.tsx, packages/remirror__react-renderer/__tests__/iframe.spec.tsx, packages/remirror__react-renderer/__tests__/link.spec.tsx, packages/remirror__react-renderer/src/handlers/index.ts
This was missed in PR https://github.com/remirror/remirror/pull/882.
=> fix(react-renderer): export heading, link, and iframe

.changeset/brown-otters-juggle.md, packages/remirror__react-renderer/src/renderer.tsx
Renders horizontalRule when setting up an out-of-the-box react-renderer.
=> feat(react-renderer): add default `horizontalRule`

.github/workflows/publish-pr.yml
This PR includes three updates for the PR-based release workflow:
1. allow not only COLLABORATOR but also OWNER and MEMBER to release a PR-based version.
2. only allow users to submit exact "/publish" in the comment to avoid [this situation](https://github.com/remirror/remirror/pull/885#issuecomment-792465373).
3. Return an error when running this workflow on a forked repository.
---
In my view, one of the biggest challenges to write a CI workflow for an open-source project is preventing attacks. For this workflow as an example, an attacker may be able to override the `pnpm publish` command and upload the `NPM_TOKEN` to their own server.
We now have three layers to prevent this kind of attacks:
1. we limit the people who can trigger this workflow.
2. we don't allow people to run this …
=> ci: limit releases to owner, members and contributors

@remirror/react-node-view/src/react-node-view.tsx
According to the prosemirror-view code, there is no third arg for this function.
And recently prosemirror updated the update function signature  to 3 args, but the 3rd arg is innerNode, not this validate function, which lead to error for apps use remirror 0.x
see https://github.com/ProseMirror/prosemirror-view/commit/e2c6315191cdd6f331737eac8482458ff5925a6c#diff-5b144bea3a5aaf7a0121242551abe1890b112bb3cbd9fbf3d5cd2022ed44bc4bR868
=> fix(react-node-view): `update` method signature

.changeset/real-humans-guess.md, packages/remirror__core-utils/__tests__/core-utils.spec.ts, packages/remirror__core-utils/__tests__/core-utils.ssr.spec.ts, packages/remirror__core-utils/package.json, packages/remirror__core-utils/readme.md, packages/remirror__core-utils/src/core-utils.ts, pnpm-lock.yaml, support/root/.size-limit.json
Add support for either `jsdom@^16` or `domino@^2` when parsing HTML content in a node environment.
Both of these are added as peer dependencies and you should install the library you prefer.
=> feat(core-utils): support parsing html in node

.changeset/selfish-laws-tease.md, packages/prosemirror-paste-rules/__tests__/paste-rules-plugin.spec.ts, packages/prosemirror-paste-rules/src/paste-rules-plugin.ts
- Fix #897
- Fix #900
- Fix #883
[**Watch Video**](https://www.loom.com/share/dba6f631cb7a4160ba8a542e7d65fe94)
https://user-images.githubusercontent.com/1160934/112470878-1c3d7300-8d63-11eb-935f-e9589c80c5f3.mp4
=> fix(prosemirror-paste-rules): maximum call stack

.changeset/hip-bears-whisper.md, .changeset/modern-snails-camp.md, .changeset/sweet-pets-visit.md, packages/remirror__extension-image/src/image-extension.ts, packages/remirror__extension-image/src/index.ts, packages/remirror__react-hooks/src/index.ts, packages/remirror__styles/all.css, packages/remirror__styles/extension-yjs.css, packages/remirror__styles/src/dom.tsx, packages/remirror__styles/src/emotion.tsx, packages/remirror__styles/src/styled-components.tsx, packages/remirror__theme/src/extension-yjs-theme.ts
This PR removes the `margin-top: 16px` style from the yjs extension, which will affect the style when using `all.css` event the users don't want to use the yjs extension.
This PR also exports some values.
=> fix: update exports and `YjsExtension` style

.changeset/quiet-cups-learn.md, .changeset/warm-pans-march.md, packages/remirror__extension-react-tables/src/components/table-cell-menu.tsx, packages/remirror__extension-react-tables/src/index.ts, packages/remirror__react/package.json, packages/remirror__react/src/index.ts, packages/remirror__react/src/tsconfig.json, pnpm-lock.yaml
This PR merges two table menu components (`ButtonComponent` and `PopupComponent`) into one big component. This provides more flexibility for the end-users.
This PR also exports `@remirror/extension-react-tables` from `@remirror/react`. This means that users don't need to install `@remirror/extension-react-tables` manually. (cc @ronnyroeller )
=> feat(extension-react-tables): merge two menu components into one

.changeset/witty-impalas-deny.md, packages/remirror__core-utils/src/prosemirror-rules.ts
When creating a node in a inputRule, use `createAndFill` instead of `create`.
=> fix(core-utils): use createAndFill instead of create in inputRule

.changeset/three-toes-wait.md, packages/remirror__core-types/__tests__/core-types.spec.ts, packages/remirror__core-types/src/core-types.ts
This PR updates the type definition of DOMOutputSpec, thanks to the power from the new version TypeScript.
=> fix(core-types): update `DOMOutputSpec`

.changeset/heavy-ants-heal.md, packages/remirror__extension-events/src/events-extension.ts, packages/remirror__react-editors/__stories__/markdown-editor.stories.tsx
The `useHover` hooks sometimes returns `undefined` as a node. This PR fixes this issue.
I found this bug when developing the draggable header bug I didn't pay much attraction to it back then. Vojtech Rinik @vojto from the project Reflect also found this bug as well as provided a solution. 
Using the following code as a simple test case:
```ts
function useDebug() {
useHover(
React.useCallback((p) => {
console.log('props:', p.hovering, p.nodes);
for (const node of p.nodes) {
if (!node.node) {
console.error('error:', p.nodes);
}
}
}, []),
);
}
```
Before this fix:
https://user-images.githubusercontent.com/24715727/115096193-ae95f880-9f56-11eb-8f53-bca9b7a2c766.mov
After this fix:
https://user-images.githubusercontent.com/24715727/115096183-a8078100-9f56-11eb-92b1-f448bc0f7f93.mov
=> fix(extension-events): fix undefined nodes

.changeset/early-laws-report.md, packages/remirror__extension-react-tables/src/components/table-cell-menu.tsx, packages/remirror__extension-react-tables/src/components/table-insert-button.ts
- Fix the problem that the insert button fails when there are other nodes below the table.
- Fix the problem that the table menu is always displayed.
Before this fix:
https://user-images.githubusercontent.com/24715727/114903646-96848300-9e49-11eb-8d34-0cf9f26fe7c1.mov
After this ifx:
https://user-images.githubusercontent.com/24715727/114903746-ae5c0700-9e49-11eb-8c8c-9b05cbdde856.mov
=> fix(extension-react-tables): fix insert button and cell menu

.changeset/afraid-flowers-taste.md, packages/remirror__core/__tests__/commands-extension.spec.ts, packages/remirror__core/src/builtins/commands-extension.ts
Add `insertHtml` command for inserting html into an active editor.
=> feat(core): add `insertHtml` command

.changeset/quiet-kings-dream.md, packages/remirror__extension-events/src/events-utils.ts
=> fix(extension-events): use posAtDOM to get mouse event position

.changeset/strange-buses-play.md, .changeset/strong-emus-rule.md, packages/remirror__core-utils/src/prosemirror-rules.ts, packages/remirror__extension-list/__tests__/tsconfig.json, packages/remirror__extension-list/package.json, packages/remirror__extension-list/src/list-commands.ts, packages/remirror__extension-list/src/list-item-extension.ts, packages/remirror__extension-list/src/tsconfig.json, packages/remirror__react-editors/__stories__/markdown-editor.stories.tsx, packages/remirror__styles/all.css, packages/remirror__styles/extension-list.css, packages/remirror__styles/src/dom.tsx, packages/remirror__styles/src/emotion.tsx, packages/remirror__styles/src/styled-components.tsx, packages/remirror__theme/src/extension-list-theme.ts, packages/remirror__theme/src/index.ts, pnpm-lock.yaml, support/root/.size-limit.json
This PR updates the origin `ListItemExtension` with two new attributes: `hasCheckbox` and `checked`. If a list item node has `hasChekcbox: true`, then it will render a checkbox at the beginning. This should be the simplest way to implement a togglable list since we don't need to add any new extensions. 
This PR also re-implements some commands from `prosemirror-schema-list` for better support to the checkbox.
A list item with a checkbox can be created by following input rules:
- Input `[ ] ` to create an unchecked list item.
- Input `- [ ] ` to create a normal list item firstly and then transform it to an unchecked list item. This matches the markdown style of writing.
In the above input rules, you can also use add `x` inside `[ ]` to directly create a checked list item.
The code is based …
=> feat(extension-list): implement list item with checkbox

.changeset/mighty-hounds-pay.md, packages/remirror__core-utils/src/prosemirror-node-utils.ts, packages/remirror__react-core/src/hooks/index.ts, packages/remirror__react-core/src/index.ts
Exposes the existing `useMarkRange` hook
Fixes minor type in the docs
=> fix(react-core): expose `useMarkRange` hook

.changeset/blue-toys-act.md, .changeset/six-peas-burn.md, packages/prosemirror-resizable-view/package.json, packages/prosemirror-resizable-view/readme.md, packages/prosemirror-resizable-view/src/index.ts, packages/prosemirror-resizable-view/src/prosemirror-resizable-view.ts, packages/prosemirror-resizable-view/src/tsconfig.json, packages/remirror__extension-image/__stories__/image.stories.tsx, packages/remirror__extension-image/__stories__/tsconfig.json, packages/remirror__extension-image/__tests__/tsconfig.json, packages/remirror__extension-image/package.json, packages/remirror__extension-image/src/image-extension.ts, packages/remirror__extension-image/src/index.ts, packages/remirror__extension-image/src/resizable-image-view.ts, packages/remirror__extension-image/src/tsconfig.json, pnpm-lock.yaml, support/root/.size-limit.json, support/root/tsconfig.json, support/root/typedoc.json
Support resizable images. Pass `enableResizable: true` to `ImageExtension` to enable this feature. When the mouse is over a resizable image, a resize handler will show at the left-bottom corner. 
TODO: 
https://user-images.githubusercontent.com/24715727/115728787-61cb7b00-a3b7-11eb-95ba-0d2b236f2e30.mov
=> feat(extension-image): support resizable images

.changeset/giant-ligers-exist.md, packages/remirror__extension-blockquote/src/blockquote-extension.ts, packages/remirror__extension-callout/src/callout-extension.ts, packages/remirror__messages/src/extension-callout-messages.ts
Fixes the input rule for callouts (and prevent similar issue on blockquotes)
Fixes messages for the callout commands (copy and paste error from headings extension)
Prevents callout `parseDOM` creating callouts of invalid type
https://user-images.githubusercontent.com/2003804/115887933-4e1d2480-a44a-11eb-9a06-1020daf183ff.mov
https://user-images.githubusercontent.com/2003804/115887979-59705000-a44a-11eb-9313-eecf36fa1efa.mov
=> fix(extension-callout): prevent empty block containers

.changeset/angry-crews-shave.md, packages/remirror__extension-link/src/link-extension.ts
This happened because the RegEx used optional capturing groups.
The commit adds two improvements to capture the link text:
- All existing capturing RegEx groups are changed to be non-capturing. An additional capturing group covers now the complete URL.
- @whawker had pointed out that the RegEx to capture the link text wasn't linked to the RegEx to capture the link href (which can be changed by the user). This is solved by using the same, user-controlled, RegEx to capture the link href and text.
Fixes https://github.com/remirror/remirror/issues/933
=> fix: pasting links ignores everything after "www."

.changeset/yellow-turtles-tan.md, packages/remirror__styles/all.css, packages/remirror__styles/extension-blockquote.css, packages/remirror__styles/extension-node-formatting.css, packages/remirror__styles/src/dom.tsx, packages/remirror__styles/src/emotion.tsx, packages/remirror__styles/src/styled-components.tsx, packages/remirror__theme/src/extension-blockquote-theme.ts, packages/remirror__theme/src/extension-node-formatting-theme.ts
A quick fix for the blockquote extension, as styles weren't be applied because of incorrect case on the `.ProseMirror` classname
Also applied the same fix for the node-formatting extension, although this seems to be empty at present.
=> fix(theme): fix parent classname for blockquote, node-formatting styles

packages/remirror__extension-list/src/bullet-list-extension.ts, packages/remirror__extension-list/src/list-item-extension.ts, packages/remirror__react-editors/__stories__/markdown-editor.stories.tsx, packages/remirror__styles/all.css, packages/remirror__styles/extension-list.css, packages/remirror__styles/src/dom.tsx, packages/remirror__styles/src/emotion.tsx, packages/remirror__styles/src/styled-components.tsx, packages/remirror__theme/src/extension-list-theme.ts
This PR let list item collapsible. This includes two parts:
Part1: 
By using `ListItemExtension({enableCollapsible: true})`, we can create a small marker at the beginning of a bullet list item. This marker is clickable. It has three states:
1. Disabled. If a list item only has one child (which must be a paragraph based on the schema), then it is not collapsible. The marker will not be clickable.
1. Expand. Show its children. Will have a light gray background and will become purple when hoving.
1. Contract. Hide its children. Will have a dark gray background and will become purple when hoving.
Part2:
By using `BulletListExtension({ enableSpine: true })`, we can create a vertical clickable line at the left side of the list.
https://user-images.githubusercontent.com/24715727/116114883-5bf1d48 …
=> feat(extension-list): support collapsible list item

.changeset/serious-humans-hide.md, packages/remirror__core/src/commands.ts, packages/remirror__extension-list/src/list-item-extension.ts
Make the command `toggleCheckboxChecked` not only change the `checked` attribute, but also transform a normal list item into a checkbox list item when necessary.
=> feat(extension-list): allow using command to create a checkbox list item

.changeset/cool-toys-allow.md, packages/jest-prosemirror/src/jest-prosemirror-matchers.ts, packages/remirror__extension-callout/__stories__/callout.stories.tsx, packages/remirror__extension-callout/__stories__/tsconfig.json, packages/remirror__extension-callout/__tests__/callout-extension.spec.ts, packages/remirror__extension-callout/src/callout-extension.ts, support/root/tsconfig.json
Fixes the input rule for callouts, hitting enter after `:::info` (for example) would create an empty callout (with no paragraph), this is invalid according to the schema, so the callout node would not be added.
Also adds a `toBeValidNode` matcher to `jest-prosemirror` to assert that a created node is actually valid according to the schema.
https://user-images.githubusercontent.com/2003804/117545837-6cc11500-b01f-11eb-9dd4-3c1f9babc6a0.mov
https://user-images.githubusercontent.com/2003804/117545847-721e5f80-b01f-11eb-8c4b-74eced1c413a.mov
=> fix(extension-callout): create valid node with input rule and enter key

.changeset/odd-weeks-wash.md, packages/remirror__extension-node-formatting/src/node-formatting-extension.ts
Quick fix for a bug with decreasing node indent by clicking `Shift-Tab` in `NodeFormattingExtension`.
Reproducible example [codesandbox](https://codesandbox.io/s/remirror-pr-000-pr70626-forked-b1wsw?file=/src/App.tsx)
`NodeFormattingExtension` is not tested yet, so would appreciate some help with adding a test case for that change 🙇‍♀️
=> fix(node-formatting): decrease indent by clicking `Shift-Tab`

.changeset/dull-impalas-bathe.md, packages/remirror__extension-annotation/src/annotation-extension.ts, packages/remirror__extension-annotation/src/annotation-plugin.ts, packages/remirror__extension-annotation/src/annotation-types.ts, packages/remirror__extension-yjs/__tests__/tsconfig.json, packages/remirror__extension-yjs/package.json, packages/remirror__extension-yjs/src/tsconfig.json, packages/remirror__extension-yjs/src/yjs-extension.ts, pnpm-lock.yaml, support/root/.size-limit.json
If both the YJS and annotations extensions are present in the editor, use the provided YDoc to share annotations via a YMap.
=> feat(extension-yjs): add ability to collaborate on annonations

.changeset/gold-shirts-own.md, packages/remirror__extension-annotation/__tests__/annotation-extension.spec.ts, packages/remirror__extension-annotation/src/annotation-plugin.ts, packages/remirror__extension-annotation/src/annotation-types.ts, packages/remirror__extension-yjs/__tests__/yjs-extension.spec.ts, packages/remirror__extension-yjs/src/yjs-extension.ts
Fix types related to #956, the private helpers added in the YJS extension return/consume relative positions, not integers.
=> fix(annotation): types and add tests

.changeset/cold-parrots-sip.md, packages/prosemirror-paste-rules/__tests__/paste-rules-plugin.spec.ts, packages/prosemirror-paste-rules/src/paste-rules-plugin.ts
Update the API:
- For `type: "node"`: removed the `transformMatch` parameter and added a new optional `getContent` parameter, which is a function that transforms the match into content when creating the node. By using `getContent`, users can set content as not only a text node, but also `undefined` or something more complex.
=> feat(prosemirror-paste-rules): allow custom content for node

.changeset/swift-suns-push.md, packages/remirror__core/src/framework/framework.ts
Context
```tsx
const handleChange = useCallback(({ firstRender }) => {
if (firstRender) {
doSomethingOnLoad();
}
}, []);
return (
<Remirror
manager={manager}
onChange={handleChange}
autoRender
/>
);
```
Perhaps I'm mis-using the `firstRender` property of the `onChange` handler, but I expected `onChange` to be called with `firstRender` once?
I have found in practice this is not the case, due to the way private properties are transpiled, it actually creates a function `_classPrivateFieldSet(_this, _firstRender, false)` which I guess get pushed onto the stack and not immediately executed. This means onChange can be called multiple times with `firstRender = true`
This PR rearranges the code, so `onChange` with `firstRender = true` only happens once.
=> fix(core): fix onChange so `firstRender` only occurs once

.changeset/eighty-students-wink.md, packages/remirror__extension-link/__tests__/link-extension.spec.ts, packages/remirror__extension-link/src/link-extension.ts, packages/remirror__playground/src/tsconfig.json
Add `supportedTargets` option to `LinkExtension`.
```ts
new LinkExtension({ supportedTargets: ['_blank'] });
// Insert a link with a target attribute.
commands.insertHtml('<a target="_blank" href="//example.com">Awesome</a>');
```
Fixes #966
_This is a draft PR until #965 is merged._
=> feat(extension-link): custom `target` attribute

.changeset/curly-swans-talk.md, packages/remirror__react-components/src/components/emoji-popup-component.tsx
Show the `EmojiPopupComponent` immediately after typing `:`.
Fixes #968
=> fix(react-components): open emoji after `:`

.changeset/dry-countries-jog.md, packages/remirror__extension-yjs/src/yjs-extension.ts
Avoid generating additional transactions for things that have already been actioned.
=> fix(yjs): ignore unnecessary handling of own changes to Yjs doc

.changeset/yellow-cheetahs-kneel.md, packages/multishift/src/multishift-utils.ts, packages/remirror__react-components/src/components/emoji-popup-component.tsx
Fix the situation where passing an array with zero items to `multishift` caused the editor to crash.
Fixes #971
=> fix(multishift): items can be empty array

.changeset/modern-tables-chew.md, packages/remirror__styles/all.css, packages/remirror__styles/core.css, packages/remirror__styles/src/dom.tsx, packages/remirror__styles/src/emotion.tsx, packages/remirror__styles/src/styled-components.tsx, packages/remirror__theme/src/core-theme.ts
Fix the styles copied from `prosemirror-view` for hiding the `text-cursor` when the `GapCursor` selection is active.
Fixes #961
=> fix(styles): hide cursor when `GapCursor` is visible

.changeset/dry-turkeys-run.md, packages/remirror__react-core/__tests__/controlled.spec.tsx, packages/remirror__react-core/src/hooks/use-react-framework.tsx, packages/remirror__react-core/src/react-framework.tsx, packages/remirror__react/__stories__/controlled.stories.tsx, packages/remirror__react/__stories__/tsconfig.json, support/root/tsconfig.json
Fixes #913
Change `onUpdate` method signature in the `ReactFramework` class. This has been done to fix the update issues for controlled editors.
=> fix(react-core): update `editable` when controlled

.changeset/clean-moose-love.md, packages/prosemirror-paste-rules/src/paste-rules-plugin.ts, packages/remirror__extension-list/__stories__/list-extension.stories.tsx
Add support for replacing the selection of nested nodes. This fixes the issue when pasting a link on text within a list.
Fixes #977
=> fix(paste-rules-plugin): support nested nodes

.github/workflows/storybook.yml
Just found that the storybook deployment for the `beta` branch (https://remirror.vercel.app/) haven't been triggered since 2021-04-22. This PR fixed this workflow.
=> ci: fix the storybook workflow on the beta branch

.changeset/heavy-fishes-hammer.md, .github/workflows/storybook.yml, packages/remirror__extension-callout/__stories__/callout.stories.tsx, packages/remirror__extension-callout/__tests__/callout-extension.spec.ts, packages/remirror__extension-callout/package.json, packages/remirror__extension-callout/readme.md, packages/remirror__extension-callout/src/callout-extension.ts, packages/remirror__extension-callout/src/callout-types.ts, packages/remirror__extension-callout/src/callout-utils.ts, packages/remirror__styles/all.css, packages/remirror__styles/extension-callout.css, packages/remirror__styles/src/dom.tsx, packages/remirror__styles/src/emotion.tsx, packages/remirror__styles/src/styled-components.tsx, packages/remirror__theme/src/extension-callout-theme.ts, pnpm-lock.yaml, support/root/.size-limit.json
Added configurable emoji to callouts. 
Added a new type: `blank`, so users are able to use a neutral background when they use the emoji as a semantic marker.
Fixes #871
https://user-images.githubusercontent.com/16329365/123252988-7f37d500-d51f-11eb-9c7c-90eea5e607d2.mov
https://user-images.githubusercontent.com/24715727/123256602-bc05cb00-d523-11eb-8989-e11af894c3c4.mov
I truly appreciate @ocavue 's patient guidance, helping me dive right in the remirror project and have a better understanding of how it works.
=> feat(extension-callout): add configurable emoji

packages/remirror__extension-list/__stories__/list-extension.stories.tsx, packages/remirror__react-editors/__stories__/markdown-editor.stories.tsx
`HardBreakExtension` gives paragraphs the ability to add a `<br/>`  inside itself by pressing `Shift + Enter` or `Mod + Enter`.
resolves #896 
https://user-images.githubusercontent.com/16329365/123671696-25ae0e00-d871-11eb-9f1a-cb4d0363c8d9.mov
https://user-images.githubusercontent.com/16329365/123671657-19c24c00-d871-11eb-9bd1-04a9d2fee254.mov
=> fix: create a newline in the current paragraph

.changeset/brave-crews-sleep.md, packages/remirror__extension-react-tables/__stories__/react-tables-extension.stories.tsx, packages/remirror__extension-react-tables/package.json, packages/remirror__extension-react-tables/src/table-extensions.tsx, packages/remirror__extension-react-tables/src/utils/controller.ts, packages/remirror__extension-react-tables/src/views/table-view.tsx, packages/remirror__extension-tables/src/table-extensions.ts, packages/remirror__extension-tables/src/table-utils.ts, pnpm-lock.yaml
Fixes #994 
This PR combines the `injectControllers` behaviour with the `createTable` command, so both actions are performed in a single transaction. This prevents merge resolution behaviour being triggered in Yjs.
This PR also adds a Storybook story for React Tables + Yjs
=> fix(react-tables): add controller to table cells in create transaction

.changeset/old-bobcats-grab.md, packages/remirror__extension-react-tables/src/table-extensions.tsx, packages/remirror__extension-tables/src/index.ts
Fix to expose utils from Tables extension, required by React Tables extension
=> fix(tables): expose utils required by react tables extension

.changeset/early-pigs-pretend.md, packages/remirror__extension-list/__tests__/list-input-rules.spec.ts, packages/remirror__extension-list/src/list-commands.ts, packages/remirror__extension-list/src/list-item-extension.ts, packages/remirror__extension-list/src/task-list-item-extension.ts
- Add a new input rule to `TaskListItemExtension`. When a user types `[]`, `[ ]`, `[x]` or `[X]` at the beginning of a `listItem` node, the editor will turn this node into a `taskListItem` node and also do some necessary transforms.
- Add a new command `liftListItemOutOfList` to `ListItemExtension`, which can lift the content inside a list item out of list.
https://user-images.githubusercontent.com/24715727/124384528-3abcee00-dd04-11eb-9c1f-484745e86bac.mov
=> feat(extension-list): turn a list item into a task list item

.changeset/clever-baboons-brake.md, packages/remirror__extension-react-tables/src/components/table-delete-button.tsx, packages/remirror__extension-react-tables/src/components/table-insert-button.ts, packages/remirror__icons/src/all-icons.ts, packages/remirror__icons/src/core-icons.ts, packages/remirror__react-components/src/icons/all.ts, packages/remirror__react-components/src/icons/core.ts, packages/remirror__react/src/index.ts, support/root/jest.config.js, support/scripts/data/icons.json
Reduce bundle size by removing `@remirror/icons/all` and `@remirror/react-icons/all-icons` from the package `@remirror/react-tables-extension`.
Issue raised in [discord](https://discord.com/channels/726035064831344711/745695521305526302/867105486049902662
) .
=> fix(extension-react-tables): reduce bundle size

.changeset/eight-pans-report.md, packages/remirror__i18n/src/en/messages.po, packages/remirror__i18n/src/en/messages.ts, packages/remirror__messages/src/extension-emoji-messages.ts
Fix incorrect label in `remirror__i18n` package when using `ToolbarCommandButton`'s `toggleBold` command.
Fixes #1032
=> fix(i18n): fix the bold command label

docs/react/create-editor.md
This is likely one of the first places people will look to create an editor, if someone copies and pastes the code as is, it will appear slightly buggy. Adding the css import and the class should ensure that it will function as intended
this is in response to a question in the discord server. Essentially to help alleviate confusion, let's add the css import and className to this early example to help new people get up and running
- [] My code follows the code style of this project and `pnpm fix` completed successfully.
- I didn't check this as i  didn't pull down and install everything since this is just a readme update.
=> docs: add styles to the create an editor step

website/sidebar.js
The "more" menu option was presented twice in the docs:
=> fix(docs): remove duplicated menu option "more"

.changeset/wet-elephants-lick.md, packages/remirror__extension-list/__stories__/list-extension.stories.tsx, packages/remirror__extension-list/__tests__/list-keymap.spec.ts, packages/remirror__extension-list/src/list-commands.ts
See also: https://github.com/remirror/remirror/issues/1043
https://user-images.githubusercontent.com/24715727/128639612-d7e62026-e5ce-4ae9-b0b1-9cd93f513031.mp4
=> fix(extension-list): don't move the content when splitting a closed item

packages/remirror__extension-file/src/file-extension.tsx, packages/remirror__extension-file/src/file-upload.ts, packages/remirror__extension-file/src/file-uploader.ts, packages/remirror__extension-file/src/file-uploaders/bashupload-file-uploader.ts, packages/remirror__extension-file/src/file-uploaders/data-url-file-uploader.ts, packages/remirror__extension-file/src/file-uploaders/object-url-file-uploader.ts, packages/remirror__extension-file/src/file-uploaders/slow-file-uploader.ts
- move `uploadFile` to a separate file.
- add generic type so that we can support different types of node in the future.
=> refactor(extension-file): minor update

docs/extensions/annotation-extension.md, docs/extensions/callout-extension.md, docs/extensions/markdown-extension.md, docs/extensions/placeholder-extension.md, packages/remirror__extension-annotation/__stories__/annotation-extension.stories.tsx, packages/remirror__extension-callout/__stories__/callout.stories.tsx, packages/remirror__extension-code-block/__stories__/code-block.stories.tsx, packages/remirror__extension-codemirror5/__stories__/codemirror5.stories.tsx, packages/remirror__extension-embed/__stories__/iframe.stories.tsx, packages/remirror__extension-file/__stories__/file.stories.tsx, packages/remirror__extension-image/__stories__/image.stories.tsx, packages/remirror__extension-link/__stories__/link-extension.stories.tsx, packages/remirror__extension-list/__stories__/list-extension.stories.tsx, packages/remirror__extension-placeholder/__stories__/placeholder-extension.stories.tsx, packages/remirror__extension-positioner/__stories__/positioner-extension.stories.tsx, packages/remirror__extension-react-tables/__stories__/react-tables-extension.stories.tsx, packages/remirror__extension-tables/__stories__/table.stories.tsx
By now, there are quite a bit of stories in storybook. The extension-related ones are now grouped into a separate section to make it easier to find them back.
=> docs: organize extension stories in separate section

readme.md, website/docusaurus.config.js, website/src/pages/index.tsx
Today, storybook is the best way to see what remirror can do. This commit adds links to storybook on the homepage, so that users can find it.
=> docs: add links to storybook

packages/remirror__extension-embed/__stories__/iframe.stories.tsx
The story were called "iFrame" whereas the extension is called "Embed".
=> docs: match story title with extension name

.changeset/strong-planets-perform.md, packages/remirror__react-renderer/__tests__/callout.spec.tsx, packages/remirror__react-renderer/src/handlers/callout.tsx
Callouts now support emojis, the React renderer should support this.
=> fix(react-renderer): add support for emoji callouts

.changeset/rotten-guests-raise.md, packages/remirror__extension-doc/__tests__/doc-extension.spec.ts, packages/remirror__extension-doc/src/doc-extension.ts
Doc extension currently supports a `docAttributes` option, however is only allows an array of keys, defaulting the value to `null`.
This PR allows `docAttributes` to be passed as a record to set the default/initial value of the attribute.
=> feat(doc): allow docAttributes to have default values

packages/remirror__extension-node-formatting/__stories__/node-formatting.stories.tsx, packages/remirror__extension-node-formatting/__stories__/tsconfig.json, packages/remirror__extension-node-formatting/src/node-formatting-extension.ts, support/root/tsconfig.json
The SchemaAttributesObject didn't have access to the current style. This meant that only one of the formatting attributes was reflected in the style.
Solution provided by @whawker
Fixes https://github.com/remirror/remirror/issues/1063
=> fix(extension-node-formatting): formatting wasn't reflected in style

.changeset/chatty-buttons-rush.md
This adds the changelog entry that was missed in PR https://github.com/remirror/remirror/pull/1071
=> fix: add missing changelog for earlier node formatting PR

packages/remirror__react-hooks/__stories__/use-mention-atom.stories.tsx
Users will feel confused when they see `../src/use-mention-atom` in the storybook.
=> docs: import `useMentionAtom` from `@remirror/react`

.changeset/big-students-dream.md, .changeset/quiet-tips-ring.md, packages/remirror__react-debugger/readme.md, packages/remirror__react-native/README.md
=> chore: deprecate `@remirror/react-native` and `@remirror/react-debugger`

docs/extensions/markdown-extension.md
We had initially considered to use inline examples (powered by the playground). Yet, this never fully worked, and we decided to use storybook for now. Hence, this commit removes the non-functioning inline example to avoid confusing the reader.
=> docs: remove non-functioning inline example

.changeset/red-beds-wait.md, packages/remirror__extension-node-formatting/src/node-formatting-extension.ts, packages/remirror__extension-node-formatting/src/node-formatting-utils.ts
The fixes added in #1071 seem to have caused an issue on copy-and-paste of HTML. The entire style attribute was parsed, leading to unpredictable results.
=> fix(node-formatting): style attribute parse, invalid line-height

.changeset/sixty-rivers-sniff.md, packages/remirror__extension-react-native-bridge/readme.md
=> chore: deprecate `@remirror/extension-react-native-bridge`

.changeset/fifty-weeks-visit.md, packages/remirror__i18n/package.json
Right now with Webpack 5 i got error
```
Plurals for locale undefined aren't loaded. Use i18n.loadLocaleData method to load plurals for specific locale. Using other plural rule as a fallback.
```
It's happen because package @remirror/i18n run side effects in index.ts file and with sideEffects:true webpack 5 remove that code
=> fix(i18n): set `sideEffect` as true because of global initialization

packages/remirror__extension-font-size/src/font-size-extension.ts
The font-size extension through an exception when increasing/decreating the font size because it mixed up the representation of the size attribute. The reading code assumed it to be always string - whereas the writing code would set it to string or number.
=> fix: font-size failed to mixed string/number

packages/remirror__extension-text-case/src/text-case-extension.ts, packages/remirror__extension-text-case/src/text-case-utils.ts
The pre-defined font cases didn't match the ones defined by the CSS spec.
@see https://developer.mozilla.org/en-US/docs/Web/CSS/text-transform
@see https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant
=> fix: supported font cases

website/styles.css
On larger screens, the website header wouldn't stretch to the full page width.
https://user-images.githubusercontent.com/9339055/130568406-76e7399b-b547-4ba4-b43a-8a629ff217d6.mov
=> fix: website header too narrow on large screens

packages/storybook-react/preview.js, packages/storybook-react/stories/react-editors/markdown-editor.stories.tsx, packages/storybook-react/stories/react-editors/social-editor.stories.tsx, packages/storybook-react/stories/react-editors/wysiwyg-editor.stories.tsx, packages/storybook-react/stories/react-renderer/react-renderer.stories.tsx, packages/storybook-react/stories/react/controlled.stories.tsx
As there are now lots of stories for storybook, we need to categorize them in sections.
=> docs: organize stories in sections

packages/remirror__react-editors/src/social/social-editor.tsx, packages/storybook-react/stories/react-editors/social-editor.stories.tsx
The social editor is a pre-packaged editor with mentioning and tagging. It got lost from pre-v1 to v1.
=> fix: bring back the social editor

.changeset/shiny-trains-promise.md, packages/remirror__extension-list/__tests__/list-commands.spec.ts, packages/remirror__extension-list/src/task-list-item-extension.ts
When using shortcut to toggle a checkbox, I don't want the cursor to move. That's why I feel we should allow a non-NodeSelecton when firing`toggleCheckboxChecked`.
=> feat(extension-list): don't require a `NodeSelection` to fire `toggleCheckboxChecked`

.changeset/lazy-crews-speak.md, packages/remirror__styles/all.css, packages/remirror__styles/core.css, packages/remirror__styles/src/dom.tsx, packages/remirror__styles/src/emotion.tsx, packages/remirror__styles/src/styled-components.tsx, packages/remirror__theme/src/core-theme.ts
Migrate the patch from prosemirro-view https://github.com/ProseMirror/prosemirror-view/commit/aaa50d592074c8063fc2ef77907ab6d0373822fb
=> fix(theme): reset some CSS on IMG separator nodes

.changeset/eight-bears-relate.md, packages/remirror__preset-wysiwyg/src/wysiwyg-preset.ts
The wrong extension was added in the wysiwygPreset
=> fix: task list was not available in SocialEditor

.changeset/six-readers-hug.md, packages/remirror__extension-list/src/task-list-item-extension.ts
we don't need a node selection anymore after #1183
=> fix(extension-list): don't create a node selection within the `toggleCheckboxChecked` command

.github/funding.yml
Copy from GitHub Support:
> Our engineering team have established the cause of the issue you're experiencing - Apparently, there's a limit on how many links you can include per funding.yml file.
> 
> The limit is 1 sponsorable org and 4 sponsorable users.
> 
> We're not quite sure why this limit was imposed or whether it's something we're able to increase, but we're continuing to investigate on those points.
> 
> I'll get back in touch once I hear more - Thanks for your patience.
So let keep funding.yml fit GitHub's requirement.
=> chore: update funding.yml

.changeset/cool-wolves-camp.md, packages/prosemirror-resizable-view/src/prosemirror-resizable-view.ts
=> fix(prosemirror-resizable-view): don't discard node attributes when resizing

.changeset/calm-olives-repair.md, packages/remirror__preset-wysiwyg/__tests__/tsconfig.json, packages/remirror__preset-wysiwyg/package.json, packages/remirror__preset-wysiwyg/src/tsconfig.json, packages/remirror__preset-wysiwyg/src/wysiwyg-preset.ts, packages/remirror__react-editors/__e2e__/tsconfig.json, packages/remirror__react-editors/package.json, packages/remirror__react-editors/src/social/social-editor.tsx, packages/remirror__react-editors/src/tsconfig.json, packages/remirror__react-editors/src/wysiwyg/wysiwyg-editor.tsx, pnpm-lock.yaml, support/root/.size-limit.json
Commit https://github.com/remirror/remirror/commit/9b8f7662775fa8228b43c327d497ccbf30c0c730 had introduced a dependency from wysiwyg to the react-part of remirror. This removes this dependency again.
=> fix: remove react dependency from wysiwyg-preset

.changeset/twelve-hotels-matter.md, packages/remirror__core/__tests__/remirror-manager.spec.tsx, packages/remirror__core/src/builtins/commands-extension.ts, packages/remirror__react-core/__tests__/controlled.spec.tsx, packages/remirror__react-core/__tests__/core.spec.tsx, support/root/jest.config.js
Unchained commands should use a new transaction to prevent leaking of previous command steps
Fixes #1197
=> fix(core): unchained commands should use a new transaction

.github/workflows/ci.yml
=> chore: pin Node to 16.8 as a workaround to nodejs/node#40030

.changeset/thin-planes-remain.md, packages/prosemirror-resizable-view/src/corner-handle.ts, packages/prosemirror-resizable-view/src/resizable-view-handle.ts
Previous resize handles might be a bit hard to recognized with a dark background.
So, I changed the corner resize handles to SVG and did some changes to the other handles,gave the resize handles a better recognizable look :)
https://user-images.githubusercontent.com/16329365/132666913-5d8739dc-712f-4bf7-8028-4298fbf117eb.mov
=> feat(resizable-view):  make handle more recognizable

docs/react/static-html.md
Fixing broken link in the documentation I found.
Previously:
https://remirror.vercel.app/?path=/story/react-renderer-static-html--basic
Fixed:
https://remirror.vercel.app/?path=/story/editors-react-renderer-static-html--basic
=> docs: fix a 404 storybook link

docs/extensions/markdown-extension.mdx
Fixing a broken Storybook link in the documentation for the Markdown extension.
Was previously linking here:
https://remirror.vercel.app/?path=/story/markdown-editor--basic
Is corrected to link here:
https://remirror.vercel.app/?path=/story/editors-markdown--basic
=> docs: fix markdown 404 storybook link

packages/remirror__react-hooks/src/use-multi-positioner.ts
Fix typo in documentation code example
=> docs: fix typo in documentation code example

website/sidebar.js
This patch allows users to run the website locally without generated API markdown files.
=> docs: allow `docs/api` to not exist

docs/extensions/drop-cursor-extension.mdx, packages/remirror__extension-file/readme.md, packages/storybook-react/stories/extension-drop-cursor/basic.tsx, packages/storybook-react/stories/extension-drop-cursor/color.tsx, packages/storybook-react/stories/extension-drop-cursor/drop-cursor.stories.tsx, packages/storybook-react/stories/extension-file/basic.tsx, packages/storybook-react/stories/extension-file/with-bashupload.tsx, packages/storybook-react/stories/extension-file/with-object-url.tsx, packages/storybook-react/stories/extension-file/with-upload-file-button.tsx, packages/storybook-react/stories/extension-file/with-upload-progress.tsx, website/extension-examples/extension-drop-cursor/basic.tsx, website/extension-examples/extension-drop-cursor/color.tsx, website/extension-examples/react/editable.tsx, website/extension-examples/react/replace-content-preserve-history.tsx
Update docs/storybook to highlight that file extension should be used with drop cursor extension.
=> chore(file): highlight file extension should use drop cursors

packages/remirror__react-editors/src/markdown/markdown-editor.tsx, packages/storybook-react/stories/react-editors/markdown-editor.stories.tsx
Enable to pre-fill content of markdown editor
Triggered by https://discord.com/channels/726035064831344711/745695521305526302/892537726346358818
=> feat: allow to pre-fill markdown editor

.changeset/big-terms-clean.md, packages/remirror__extension-annotation/__tests__/annotation-extension.spec.ts, packages/remirror__extension-annotation/src/annotation-extension.ts
Add the ability to filter out edge matches from `getAnnotationsAt` helper.
I.e. if an annotation exists from position 4 to 9, `getAnnotationAt(4)` will match it, `getAnnotationAt(4, false)` will **not**
=> feat(extension-annotation): add flag to filter out getAnnotationsAt edge matches

.changeset/stale-dolls-lay.md, packages/remirror__core-helpers/src/core-errors.ts
This error will be raised in `useRemirrorContext` instead of `useRemirror`.
=> fix(core-helpers): correct the error message for `ErrorConstant.REACT_PROVIDER_CONTEXT`

.changeset/witty-shirts-hammer.md, packages/remirror__extension-list/src/list-commands.ts
Closes #1258
Before this patch:
https://user-images.githubusercontent.com/24715727/135931608-9edea0c3-4cb7-4c80-8f53-115e84a3cff4.mp4
After this patch:
https://user-images.githubusercontent.com/24715727/135931483-ef238b94-f16a-4e69-9709-bd64364faaad.mp4
=> fix(extension-list): don't let the browser handle the Tab key in a list

.changeset/twenty-jobs-love.md, packages/remirror__extension-list/src/list-commands.ts
Merge the upstream patch 
https://github.com/ProseMirror/prosemirror-schema-list/commit/38867345f6d97d6793655ed77c16f1a7b18f6846
Notice that the `tr` in `liftOutOfList` may not be a _clean_ transaction, so we need to remove all previous steps when calculate mapping.
=> fix(extension-list): merge patch from the upstream

.changeset/hot-shirts-lick.md, .changeset/silver-papayas-kneel.md, packages/remirror__extension-list/__tests__/list-input-rules.spec.ts, packages/remirror__extension-list/src/bullet-list-extension.ts, packages/remirror__extension-list/src/index.ts, packages/remirror__extension-list/src/list-commands.ts, packages/remirror__extension-list/src/list-item-extension.ts, packages/remirror__extension-list/src/list-item-shared-extension.ts, packages/remirror__extension-list/src/list-utils.ts, packages/remirror__extension-list/src/ordered-list-extension.ts, packages/remirror__extension-list/src/task-list-item-extension.ts
- Automagically join two lists with the same node type when there are siblings.
- Allow input rules to convert task list to bullet list or ordered list. 
Closes #1249
https://user-images.githubusercontent.com/24715727/136146036-49370428-813b-471a-98ae-4b58686705ed.mov
=> feat(extension-list): improve list input rules

.changeset/nice-planets-eat.md, packages/prosemirror-resizable-view/src/prosemirror-resizable-view.ts, packages/storybook-react/package.json, packages/storybook-react/src/storybook-react-main.ts, packages/storybook-react/stories/extension-image/basic.tsx, packages/storybook-react/stories/extension-image/image.stories.tsx, packages/storybook-react/stories/extension-image/resizable.tsx, pnpm-lock.yaml
https://user-images.githubusercontent.com/24715727/140254172-0f933aff-1a5a-45be-b796-49e5842f0fa5.mov
Safari (both mac and iOS) doesn't support `aspect-ratio` until the very latest version:
=> fix(resizable-view): fix resizable view height on a small viewpoint

.changeset/tasty-gifts-remember.md, packages/remirror__core-helpers/src/core-helpers.ts
https://user-images.githubusercontent.com/24715727/140272834-997056e3-03f3-4469-a5b5-a51a4cf2c1cf.mp4
=> fix(core-helpers): always reset regexp lastIndex before matching

.changeset/big-planets-cross.md, .changeset/quiet-swans-collect.md, packages/remirror__core/src/extension/base-class.ts, packages/remirror__extension-file/src/file-extension.tsx
The handler was only triggered when using the `deleteFile` command, this fix triggers the handler when the keyboard is used too.
=> fix(extension-file): deleting files via keyboard should trigger onDeleteFile handler

.changeset/orange-ravens-marry.md, packages/remirror__extension-link/__tests__/link-extension.spec.ts, packages/remirror__extension-link/src/index.ts, packages/remirror__extension-link/src/link-extension.ts, packages/storybook-react/stories/extension-link/link-extension.stories.tsx, packages/storybook-react/stories/extension-link/with-telephone-support.tsx, website/extension-examples/extension-link/with-telephone-support.tsx
Add a new option `extractHref` to `ExtensionLink`. Users can use this option to customize the `href` attribute, for example `file://` and `tel:`.
=> feat(extension-link): add a new extension option `extractHref`

.changeset/happy-pets-hang.md, .changeset/many-buttons-eat.md, docs/extensions/shortcuts-extension.mdx, packages/remirror/package.json, packages/remirror/src/extensions.ts, packages/remirror/src/tsconfig.json, packages/remirror__extension-shortcuts/CHANGELOG.md, packages/remirror__extension-shortcuts/__tests__/shortcuts-extension.spec.ts, packages/remirror__extension-shortcuts/__tests__/tsconfig.json, packages/remirror__extension-shortcuts/package.json, packages/remirror__extension-shortcuts/readme.md, packages/remirror__extension-shortcuts/src/index.ts, packages/remirror__extension-shortcuts/src/shortcuts-extension.ts, packages/remirror__extension-shortcuts/src/tsconfig.json, packages/remirror__preset-wysiwyg/__tests__/tsconfig.json, packages/remirror__preset-wysiwyg/package.json, packages/remirror__preset-wysiwyg/src/tsconfig.json, packages/remirror__preset-wysiwyg/src/wysiwyg-preset.ts, packages/storybook-react/stories/extension-shortcuts/basic.tsx, packages/storybook-react/stories/extension-shortcuts/shortcuts.stories.tsx, pnpm-lock.yaml, support/root/.size-limit.json, support/root/tsconfig.json, website/extension-examples/extension-shortcuts/basic.tsx
Keyboard shortcuts replaces e.g. characters `(c)` by `©`.
=> feat: add shortcuts support

packages/remirror__extension-shortcuts/package.json
This broke before the build: https://discord.com/channels/726035064831344711/745695557976195072/910219378744754277
=> fix: make extension-shortcuts package public

.changeset/thick-zebras-admire.md, packages/remirror__extension-font-size/__tests__/font-size-extension.spec.ts, packages/remirror__extension-font-size/src/font-size-extension.ts
Before, removeFontSize would remove always the complete mark.
Fixes https://discord.com/channels/726035064831344711/745695521305526302/908690345464836126
=> fix: removeFontSize respects user selection

.changeset/two-gifts-float.md, packages/remirror__extension-shortcuts/src/shortcuts-extension.ts
Remirror's input rules currently don't handle capture groups directly.
TODO: These rules could be brought back if we add logic to inject the provided matches into the replacement string.
=> fix: remove rules depending on capture groups

docs/getting-started/create-manager.md
Fix a typo in comment on create-manager code example
=> docs: fix create-manager doc typo

docs/extensions/font-size-extension.mdx
Docs example to avoid font size bug
tests failed on my machine with:
RangeError: /Users/steve/Documents/oss/remirror/packages/remirror__react-components/src/icons/all.ts: Maximum call stack size exceeded
but since this PR is a doc change only, I'm going to ignore that as it's probably due to my M1/node version etc.
=> docs: add example of font size extension initial content using JSON

.changeset/little-points-itch.md, packages/remirror__extension-react-component/src/react-node-view.tsx, packages/storybook-react/stories/extension-file/basic.tsx
This PR fixes an issue that causes Rect node view's drag-and-drop not to work. 
Close #1395 
https://user-images.githubusercontent.com/24715727/144795631-20cf3396-c3a9-44e8-812a-f4a2e0aeb9e1.mp4
=> fix(react): fix React node view's drag-and-drop 

package.json
The latest version of `y-prosemirror` seems to have some kind of ESM/CJS issues, which blocks #1396, so let me ignore it temporarily.
=> chore: let renvoate to ignore y-prosemirror temporarily

docs/extensions/image-extension.mdx, packages/storybook-react/stories/extension-image/basic.tsx, packages/storybook-react/stories/extension-image/image.stories.tsx, packages/storybook-react/stories/extension-image/with-figcaption.tsx, website/extension-examples/extension-image/with-figcaption.tsx
Add an example in the document to answer some questions from the community:
https://github.com/remirror/remirror/discussions/1415
https://github.com/remirror/remirror/discussions/1413
https://github.com/remirror/remirror/discussions/1401
=> docs: add an example using `<figcaption>` with `ImageExtension`

.changeset/stupid-windows-smoke.md, packages/remirror__extension-list/__tests__/list-keymap.spec.ts, packages/remirror__extension-list/src/list-commands.ts
Fix an issue that causes the content below a list item is being deleted when deleting this list item by pressing Enter.
https://user-images.githubusercontent.com/24715727/145380040-88d2e60f-6dda-4293-b04d-06d4827a146c.mp4
=> fix(extension-list): don't delete extra nodes when pressing enter

.changeset/sour-rockets-tan.md, packages/remirror__extension-shortcuts/src/shortcuts-extension.ts
The shortcut used the 'LEFT RIGHT BLACK ARROW' (U+2B0C) whereas the left arrow and the right arrow are not the BLACK variant. For visual consistency, this commit changes the left/right arrow to the non-BLACK version 'LEFT RIGHT ARROW' (U+2194).
Raised by https://github.com/remirror/remirror/pull/1423#issuecomment-990765788
=> feat: align left/right arrow style with other arrows

.changeset/pink-snails-behave.md, packages/remirror__extension-link/src/link-extension.ts
Drag and dropping text containing links would loss the text _after_ the link
https://user-images.githubusercontent.com/2003804/146214958-1c362b9a-42be-415c-a049-6f2a2f5f1f80.mov
https://user-images.githubusercontent.com/2003804/146215494-24dab1b2-2f62-4a3e-88fc-1b30ae416c27.mov
=> fix(link): prevent text loss when drag and dropping text containing links

.changeset/fuzzy-tomatoes-help.md, packages/remirror__extension-events/src/events-extension.ts
Copy and paste events are clipboard events, not scroll events.
=> fix(events): fix type of copy and paste event handlers

docs/getting-started/commands-and-helpers.md
Fixes a typo.
- ~[ ] My code follows the code style of this project and `pnpm fix` completed successfully.~ (doc typo)
=> docs: fix typo in "command and helpers" documentation

docs/contributing.md
Add a note to the "contributing" documentation that the PR names should follow "Conventional commits" style -- given that that seems to be actually checked by one of the actions :)
- ~[] My code follows the code style of this project and `pnpm fix` completed successfully.~ (no code change)
- ~[] New code is unit tested and all current tests pass when running `pnpm test`.~ (no code change)
=> docs: hint at the "conventional commits" convention for PR names

packages/remirror__core/src/manager/remirror-manager.ts
Accessing private members is ever so slightly slower, but more importantly when stepping
through this code it is very confusing to first see `firstUpdate` getting computed and then
completely ignored in the line below that.
=> fix: use the `firstUpdate` local variable

.changeset/clean-weeks-draw.md, .changeset/fifty-keys-cheat.md, .changeset/mean-lies-explode.md, packages/remirror__extension-code-block/src/code-block-extension.ts, packages/remirror__extension-code-block/src/code-block-types.ts, packages/remirror__extension-codemirror6/src/codemirror-extension.ts, packages/remirror__extension-codemirror6/src/codemirror-node-view.ts, packages/remirror__extension-codemirror6/src/codemirror-types.ts, packages/storybook-react/stories/extension-codemirror6/basic.tsx, packages/storybook-react/stories/extension-codemirror6/codemirror6.stories.tsx, packages/storybook-react/stories/extension-codemirror6/styles.css, packages/storybook-react/stories/extension-codemirror6/with-custom-extension.tsx
This PR mainly adds `Backspace` keybinding to `CodeMirrorExtension` as well as some other bug fixes. Check the changeset files for details.
https://user-images.githubusercontent.com/24715727/147765386-d6cde1bb-1e4d-438b-8bd4-dc06d3f4048a.mp4
=> feat(extension-codemirror6): add `Backspace` keybinding to CodeMirrorExtension

.changeset/wicked-trains-scream.md, packages/remirror__extension-list/__tests__/list-keymap.spec.ts, packages/remirror__extension-list/src/list-commands.ts
Fix a cursor bug when pressing backspace before a list item. Check the screenshots below for details. 
Before this patch:
https://user-images.githubusercontent.com/24715727/148402939-4b61a0c2-2892-4258-88fc-c9c38afa8631.mp4
After this patch: 
https://user-images.githubusercontent.com/24715727/148403024-14e33b63-a0d3-4a5e-953f-b4b76c7141df.mp4
=> fix(extension-list): fix the cursor position when pressing backspace

.changeset/rude-foxes-drop.md, packages/remirror__extension-react-tables/src/table-plugins.ts, packages/remirror__extension-text-color/src/text-color-utils.ts, packages/remirror__theme/src/components-theme.ts, packages/remirror__theme/src/core-theme.ts, packages/remirror__theme/src/extension-blockquote-theme.ts, packages/remirror__theme/src/extension-emoji-theme.ts, packages/remirror__theme/src/extension-list-theme.ts, packages/remirror__theme/src/extension-mention-atom-theme.ts, packages/remirror__theme/src/extension-tables-theme.ts, packages/remirror__theme/src/index.ts, packages/remirror__theme/src/theme.ts, packages/remirror__theme/src/utils.ts, packages/storybook-react/stories/react-editors/markdown-editor.stories.tsx
`Proxy` cannot be (completely) polyfilled - meaning Remirror cannot be used on IE11, even with polyfills applied.
Whilst Remirror does not support IE11, I think we should not be actively blocking its usage.
This PR deprecates `getTheme` and `getThemeProps` in favour of `getThemeVar` and `getThemeVarName` that avoid using a Proxy, whilst preserving Typescript hints.
=> feat(theme): avoid using Proxy to generate theme variables

.changeset/rude-foxes-drop.md
`storybook-react` should not be included in changeset.
=> chore: fix changeset, remove storybook-react

docs/extensions/yjs-extension.mdx, packages/storybook-react/stories/extension-yjs/basic.tsx
The `yjs` and `history` extensions conflict, for example by both providing a `undo` command: In a yjs-enabled remirror instance with the `history` extension not excluded from the core preset the `undo` command will actually be provided the `history` extension, which isn't aware of the specific Yjs transactions -- and for instance will allow to "undo" the initial content of the editor.
This is mentioned in the JS docs for the `excludeExtensions` setting: https://github.com/remirror/remirror/blob/64593d99c3d88efe2b46a990b873e0ef107d01dd/packages/remirror__preset-core/src/core-preset.ts#L25-L26
This PR brings that important tidbit into a place that a user might actually see: The Yjs extension documentation :)
While there: Drop some weird half-sentences in the same document. I don't know …
=> docs: include the note that the `history` extension conflicts with `yjs`

.changeset/slimy-dolphins-peel.md, packages/remirror__extension-font-size/src/font-size-extension.ts
Close #1455 
When the manager's phase is smaller than [ManagerPhase.EditorView](https://github.com/remirror/remirror/blob/862a0c8ec4e90c2108abe8c2f50cdcb562ffa713/packages/remirror__core-constants/src/core-constants.ts#L403), `this.store.view` is `undefined`.
=> fix(extension-font-size): fix a runtime error when getting font size

.changeset/cool-olives-know.md, packages/remirror__extension-horizontal-rule/src/horizontal-rule-extension.ts
The ShortcutExtension picks up "--" and replaces it with a dash. This means that the HorizontalRuleExtension never sees "---" because it was already replaced to "<dash>-".
To avoid this, the HorizontalRuleExtension replaces now also "<dash>-".
=> fix: make HorizontalRule compatible with Shortcuts

packages/storybook-react/stories/extension-yjs/basic.tsx
The yjs extension interacts with the annotations extension, and in fact was configured for the story -- but there were no controls exposed to show that.
=> docs: include controls for adding/removing annotations in the yjs extension story

.changeset/ninety-kids-shave.md, packages/remirror__extension-annotation/__tests__/annotation-extension.spec.ts, packages/remirror__extension-annotation/src/annotation-plugin.ts
Typing at the beginning of annotation extends the annotation, instead of entering the text in front of the annotation. This is unexpected for users because the annotation doesn't extend when entering text at the end of the annotation.
Fixes https://github.com/remirror/remirror/issues/1493
=> fix: don't extend annotation when the user types at the beginning

packages/remirror__extension-annotation/__tests__/annotation-extension.spec.ts, packages/remirror__extension-annotation/src/annotation-actions.ts, packages/remirror__extension-annotation/src/annotation-extension.ts, packages/remirror__extension-annotation/src/annotation-plugin.ts, packages/remirror__extension-annotation/src/annotation-store.ts, packages/remirror__extension-annotation/src/annotation-types.ts, packages/remirror__extension-annotation/src/index.ts, packages/remirror__extension-yjs/src/yjs-extension.ts
Annotations with the Yjs extension enabled are stored in a Y.Map, which is "almost but not quite" a Map. But, apart from that, the pattern in which is should be used is quite different, and changes that
conceptually belong together should be executed inside a single transaction.
This PR has two parts:
1. Refactor how the annotation extension stores the annotations, and instead of exposing a "map + transform" interface expose a more flexible "store" interface.
2. Use that interface and implement `setAnnotations` and `removeAnnotations` for the yjs extension with a `Y.transact` wrapper
Note that I would have loved to kill the `getMap` part, because there shouldn't be any other user of this (it feels like a "escape hatch" purely intended for the Yjs extension), but semver-wise that would be …
=> fix: update annotations in Yjs transaction

docs/getting-started/create-manager.md
Let's make it clear that `content` should accept a JSON object instead of a JSON string.
=> docs: improve the docs for initial JSON

.changeset/twenty-zebras-live.md, packages/remirror__core-utils/src/core-utils.ts, packages/remirror__extension-link/__tests__/link-extension.spec.ts, packages/remirror__extension-link/src/link-extension.ts
Currently auto linking is performed by a suggestor - however auto linking it not trigger by a specific character (like `@` for instance), this means when are abusing (and constrained) by the suggestor API making this area of the code particularly difficult to maintain.
This PR modifies how auto linking works, it uses changed ranges to determine auto link candidates to ensure good performance on larger documents.
https://user-images.githubusercontent.com/2003804/151844465-5848b99b-b78b-441a-8ede-6cd97209b8ad.mov
=> refactor(extension-link): refactor auto link to simplify and remove bugs

.changeset/dry-jars-relax.md, docs/extensions/yjs-extension.mdx, packages/remirror__extension-annotation/src/annotation-plugin.ts, packages/remirror__extension-yjs/__tests__/__snapshots__/yjs-extension.spec.ts.snap, packages/remirror__extension-yjs/__tests__/yjs-extension.spec.ts, packages/remirror__extension-yjs/src/yjs-extension.ts
The yjs extension provides a undo/redo implementation, which the docs suggest should be used instead of the default one provided in remirror (through the history extension). This suggestion is somewhat problematic, depending on the use case:
1. `yUndo` is using the Yjs `UndoManager`, which works on the level of the Yjs document, and as such actually collects also changes of other users. The manager is configured to watch transactions from the sync-plugin.
2. Even worse (IMHO) is that while the undo manager is able to track changes in a very fine-grained way ("character appeared over here"), the yjs extension applies any such changes by rendering the complete prosemirror document based on the Yjs document, and then simply replacing the document inside the editor with that. That makes the …
=> feat: allow to disable yjs undo/redo

.changeset/neat-rockets-boil.md, packages/remirror__styles/all.css, packages/remirror__styles/core.css, packages/remirror__styles/src/dom.tsx, packages/remirror__styles/src/emotion.tsx, packages/remirror__styles/src/styled-components.tsx, packages/remirror__theme/src/core-theme.ts
[Issue raised on Discord](https://discord.com/channels/726035064831344711/745695521305526302/940731226245984326) - On Windows, `Ctrl+Click` makes the text invisible.
=> fix(styles): use the inherited text color if the selection is hidden

.changeset/tough-dingos-clap.md, .changeset/yellow-wolves-change.md, packages/jest-prosemirror/src/jest-prosemirror-editor.ts, packages/prosemirror-paste-rules/__tests__/paste-rules-plugin.spec.ts, packages/prosemirror-paste-rules/src/paste-rules-plugin.ts
=> fix(prosemirror-paste-rules): fix the replace selection when selecting two characters

.changeset/mean-jars-dress.md, packages/remirror__extension-positioner/__tests__/positioner-extension.spec.ts, packages/remirror__extension-positioner/src/positioner-extension.ts, packages/remirror__extension-positioner/src/positioner-utils.ts
Add the ability to force update positioners with a new command `forceUpdatePositioners`.
This can be useful to update positioners when the view is updated in a way that doesn't trigger a ProseMirror state change. For instance when an image URL is loaded and the document is reflowed.
=> feat(extension-positioner): allow force update of positioners

.changeset/unlucky-waves-deliver.md, packages/jest-remirror/package.json, packages/remirror__cli/package.json, packages/storybook-react/package.json, support/scripts/src/generate-configs.ts
Make sure all conditional exports in `package.json` have a "default" field. 
> https://nodejs.org/docs/latest-v16.x/api/packages.html#conditional-exports
>
> When using environment branches, always include a "default" condition where possible.
=> fix(jest-remirror): add `default` filed in the `package.json`

.changeset/perfect-vans-roll.md, packages/remirror__core/src/framework/base-framework.ts, packages/remirror__core/src/framework/framework.ts, packages/remirror__react-core/src/react-framework.tsx
When transactions are appended via plugins (i.e. `appendTransaction`) these transactions are not visible to the `onChange` handler passed to the `<Remirror />` root component.
```jsx
const handleChange = useCallback(({
tr, // As before
transactions // Now available
}) => {
const steps = [];
transactions?.forEach((transaction) => {
steps.push(...transaction.steps);
});
if (steps.length > 0) {
myHandlerForSteps(steps);
}
}, [myHandlerForSteps]);
return (
<Remirror
manager={manager}
initialContent={state}
onChange={handleChange}
/>
);
```
=> feat(core): expose appended transactions in the onChange handler

.changeset/tasty-starfishes-remember.md, packages/jest-remirror/src/jsdom-polyfills.ts
We polyfill `document.createRange` however, we don't polyfill `getClientRects` / `getBoundingClientRects` which are need for `posAtCoords` etc.
=> fix(jest-remirror): add client rect to `createRange` polyfill

.changeset/bright-beans-kiss.md, packages/prosemirror-suggest/__tests__/suggest-plugin.spec.ts, packages/prosemirror-suggest/src/suggest-types.ts, packages/prosemirror-suggest/src/suggest-utils.ts
I needed to work with non-latin words for `MentionAtomExtension` (and `MentionExtension` too), so I dug deep enough to understand what is missing: support for Unicode RegExp (required to support Unicode character types: https://caniuse.com/?search=%5Cp). This PR adds that as an option to in `matchers` list.
If you need non-latin characters to be matched in your matchers add `supportedCharacters` definition along with `unicode: true` option, i.e.
```jsx
export const Editor = ({ initialValue }) => {
const extensions = () => [
new MentionAtomExtension({ matchers: [{ char: '@', name: 'at', supportedCharacters: /\p{Letter}+/u, unicode: true }] }),
};
const { manager, state } = useRemirror({ extensions, content: initialValue, stringHandler: 'html' });
return (
<Remirror initialContent={state} …
```
=> feat: unicode regex in suggestion matching

.changeset/poor-apples-fry.md, packages/remirror__extension-react-tables/src/table-plugins.ts
An abandoned `preselectclass` style was highlighting all borders.
link - https://remirror.vercel.app/?path=/story/extensions-react-table--basic
=> fix(extension-react-tables): deleted an incorrect preselectClass style on react-table-extension

.changeset/dull-eggs-walk.md, packages/prosemirror-paste-rules/package.json, packages/prosemirror-resizable-view/package.json, packages/prosemirror-suggest/package.json, packages/prosemirror-trailing-node/package.json, packages/remirror__pm/package.json, pnpm-lock.yaml
Fixes bug with callout extension
Deleting first node in NodeView with backspace deletes entire node view content - https://github.com/ProseMirror/prosemirror/issues/1257
https://user-images.githubusercontent.com/3799600/161326474-083920da-34fb-4e62-af93-3788ed3fa45f.mov
=> chore(deps):  bump prosemirror-view version

.changeset/cold-spies-ring.md, packages/prosemirror-resizable-view/src/prosemirror-resizable-view.ts
After pressing the resizable handle, if the node is updated and causes the node view to re-render, the `onmouseup` listener that was bound to `document` should be removed. 
https://user-images.githubusercontent.com/24715727/161974430-929b7225-9bd2-4eef-ac36-f2d1d8b2d0a9.mp4
=> fix(prosemirror-resizable-view): fix an error during resizing

.changeset/selfish-toys-draw.md, packages/remirror__extension-react-tables/src/table-extensions.tsx, packages/remirror__extension-tables/src/table-extensions.ts
Prevent highlighting cells while resizing columns.
Highlighted by [Pierre_ on Discord](https://discord.com/channels/726035064831344711/745695557976195072/964507362331340860)
=> fix(tables,react-tables): avoid highlighting cells while resizing

.changeset/moody-scissors-burn.md, .changeset/stale-seas-pull.md, packages/remirror__extension-italic/__tests__/italic-extension.spec.ts, packages/remirror__extension-italic/src/italic-extension.ts, packages/remirror__extension-mention-atom/src/mention-atom-extension.ts
Prevent marks in Mention atom, to prevent `@some_mention_text` rendering as
=> fix(mention-atom): mention atom should not allow marks

.changeset/blue-dodos-reply.md, packages/remirror__core/src/builtins/plugins-extension.ts, packages/remirror__extension-annotation/__tests__/annotation-extension.spec.ts
Fixes #1607
Adding `getPluginState` to the constructor prototype meant that state could be shared between editor instances.
=> fix(core): prevent shared state between editor plugin instances

.changeset/fuzzy-sloths-knock.md, packages/remirror__extension-embed/__tests__/iframe-extension.spec.ts, packages/remirror__extension-embed/src/iframe-extension.ts, packages/remirror__extension-embed/src/resizable-iframe-view.ts
This PR fixes #1615. The issue description already has an explanation of what's happening and this as a possible solution. As you can see, we weren't parsing the iframe dimensions as numbers but as strings.
- I don't think this is applicable, but please let me know if you'd prefer tests and what kind specifically.
https://www.loom.com/share/8f4c35dd23bc45c3a14960e9e55e2d5f
=> fix(extension-embed): correctly parse saved iframe dimensions

.changeset/mean-queens-deliver.md, .changeset/yellow-jobs-divide.md, packages/prosemirror-paste-rules/__tests__/paste-rules-plugin.spec.ts, packages/prosemirror-paste-rules/src/paste-rules-plugin.ts, packages/remirror__extension-heading/src/heading-extension.ts
Close #1238 
https://user-images.githubusercontent.com/24715727/166499392-8174e4e3-04ed-48e3-946b-97347394a30d.mp4
=> fix(prosemirror-paste-rules): paste multiple block nodes

.changeset/three-owls-admire.md, packages/prosemirror-paste-rules/__tests__/paste-rules-plugin.spec.ts, packages/prosemirror-paste-rules/src/paste-rules-plugin.ts
https://user-images.githubusercontent.com/24715727/168612431-c0064c97-7237-4901-adf9-351ea1c3560e.mp4
=> fix(prosemirror-paste-rules): set open depth more precisely

.changeset/stupid-stingrays-approve.md, packages/remirror__core-utils/__tests__/prosemirror-utils.spec.ts, packages/remirror__core-utils/src/index.ts, packages/remirror__core-utils/src/prosemirror-utils.ts, packages/remirror__extension-link/src/link-extension.ts, packages/remirror__extension-react-tables/src/table-extensions.tsx
Fixes behaviour when pasting a table using the React Tables extension.
Previously, editor state was updated, but the controllers were not injected, meaning nothing was displayed visually.
Copy and paste the table below [here](https://pr1644-remirror-ocavue.vercel.app/?path=/story/extensions-react-table--basic), to see the bug.
| Company                      | Contact          | Country |
|------------------------------|------------------|---------|
| Alfreds Futterkiste          | Maria Anders     | Germany |
| Centro comercial Moctezuma   | Francisco Chang  | Mexico  |
| Ernst Handel                 | Roland Mendel    | Austria |
| Island Trading               | Helen Bennett    | UK      |
| Laughing Bacchus Winecellars | Yoshi Tannamuri  | Canada  |
| Magazzini Alimentari Riuniti | …
=> fix(react-tables): inject controllers when pasting a table

docs/hooks/use-active.md, docs/hooks/use-chained-commands.md, docs/hooks/use-commands.md, docs/hooks/use-event.md, docs/hooks/use-helpers.md, docs/hooks/use-keymap.md, website/sidebar.js
Add initial docs for Remirror's hooks
=> docs(hooks): improve docs on Remirror's hooks

.changeset/famous-waves-join.md, .changeset/metal-dodos-listen.md, packages/remirror__extension-list/src/list-command-dedent.ts, packages/remirror__extension-list/src/list-command-indent.ts, packages/remirror__extension-node-formatting/__tests__/node-formatting-extension.spec.ts, packages/remirror__extension-node-formatting/src/node-formatting-extension.ts, packages/remirror__extension-node-formatting/src/node-formatting-utils.ts, packages/storybook-react/stories/extension-node-formatting/basic.tsx
Close #1489 
https://user-images.githubusercontent.com/24715727/169849485-1503dbee-8f89-4bbd-a5f5-a2ae84036e0c.mp4
=> fix: resolve the shortcut conflict between node formatting and list

docs/react/refs.md
Remove duplicated import `ReactFrameworkOutput` from here
``` tsx
import {
ReactExtensions,
ReactFrameworkOutput,
ReactFrameworkOutput,
Remirror,
useRemirror,
} from '@remirror/react';
```
=> docs: remove duplicated codes

.changeset/lovely-timers-guess.md, .changeset/yellow-ants-brush.md, packages/remirror__core-utils/__tests__/command-utils.spec.ts, packages/remirror__core-utils/src/command-utils.ts, packages/remirror__core/__tests__/commands-extension.spec.ts
This aligns with the behaviour of ProseMirror itself.
Fixes #1398
Add support for `removeMark` removing _all_ marks by passing 
```tsx
const { removeMark } = useCommands();
const handleClick = useCallback((e) => {
removeMark({ type: null });
}, [removeMark]); 
```
Also fixes the `removeMark` command, so that it removes marks across multiple mark ranges.
=> feat(core): add ability to remove all marks by passing `type: null`

.changeset/tough-boxes-battle.md, packages/remirror__extension-list/__tests__/task-list-extension.spec.ts, packages/remirror__extension-list/src/task-list-item-extension.ts
Fixes #1657
Checkboxes should not be clickable when the view is not editable.
This isn't an ideal solutions as the checkboxes are not visually disabled
=> fix(tasklist): prevent checkbox toggle when view is not editable

.github/workflows/version.yml
> Warning: The workflow file using `changesets/action` is currently using `@master` as the version. This branch has been frozen and deprecated. Please update your workflow to either use `@v1` or a specific commit SHA that is tagged.
=> chore: fix the changeset action tag

.github/workflows/docs.yml, .github/workflows/storybook.yml
**Temporarily** modify CI pipeline to only update docs (remirror.io) and storybook (remirror.vercel.app) on merge to the `v1-hotfix` branch.
Currently React Tables are broken on main (v2 beta). v2 beta is currently deployed to above URLs, making it appear that our "latest" release (**v1**) is broken, which is not true.
=> chore: publish docs and storybook from remirror v1

.github/workflows/docs.yml, .github/workflows/storybook.yml
**N.B.** This branch merges to `v1-hotfix` **_NOT_** `main`
Temporarily modify CI pipeline to only update docs (remirror.io) and storybook (remirror.vercel.app) on merge to the v1-hotfix branch.
Currently React Tables are broken on main (v2 beta). v2 beta is currently deployed to above URLs, making it appear that our "latest" release (v1) is broken, which is not true.
=> chore: deploy docs and storybook from v1-hotfix

.github/workflows/docs.yml, .github/workflows/storybook.yml
**Temporarily** modify CI pipeline to only update docs (remirror.io) and storybook (remirror.vercel.app) on merge to the `v1-hotfix` branch.
Currently React Tables are broken on main (v2 beta). v2 beta is currently deployed to above URLs, making it appear that our "latest" release (**v1**) is broken, which is not true.
=> chore: publish docs and storybook from remirror v1 (2)

docs/concepts/styling.md
In the Core concepts > Styling tab of the official document, if you apply the example of emotion and styled-component, styling will not be applied.
You need to change the order of `ThemeProvider` and `AllStyledComponent` for it to take effect. So I've edited this part of the documentation.
Also, in emotion and styled-component, `@remirror/styles` was raised to the top because the phrase that install is required is at the end of the document, so you may not be able to find it.
=> docs: fix rendering order of Styling docs

packages/remirror__extension-react-component/src/portals/react-portals.tsx
=> fix(extension-react-component): use Array.from for portals.entries()

.changeset/few-keys-float.md, .changeset/thin-starfishes-unite.md, packages/prosemirror-paste-rules/package.json, packages/prosemirror-resizable-view/package.json, packages/prosemirror-suggest/package.json, packages/prosemirror-trailing-node/package.json, packages/remirror__core-types/src/core-types.ts, packages/remirror__core/src/builtins/node-views-extension.ts, packages/remirror__extension-hard-break/__tests__/hard-break-extension.spec.ts, packages/remirror__extension-hard-break/src/hard-break-extension.ts, packages/remirror__pm/package.json, pnpm-lock.yaml, support/actions/pnpm/action.yml
`NodeSpec.leafText` is a new property in [prosemirror-model@1.18.0](https://github.com/ProseMirror/prosemirror-model/pull/66). This property allows a leaf node to customize its `textContent` when using `Node.textContent` or `Node.textBetween(...)`. 
This is especially useful for HardBreakExtension.
Before this PR, if a paragraph contains a `hardBreak` node, the length of its `textContent` is smaller than the size of this paragraph node, because a `hardBreak` node has size as 1, but output empty string in `node.textContent`. This difference between ProseMirror node size and `textContent` string length causes some errors when calculating position.
=> feat: support leafText 

packages/remirror__extension-annotation/__tests__/annotation-extension.spec.ts, packages/remirror__extension-annotation/src/annotation-plugin.ts
Fixes #1655.
The internal annotation store was not updated on non annotation actions.
=> fix(annotation): update the store after mapping annotation positions

packages/remirror__extension-entity-reference/CHANGELOG.md, packages/remirror__extension-entity-reference/package.json, packages/remirror__extension-entity-reference/readme.md, packages/remirror__extension-entity-reference/src/types.ts, packages/remirror__extension-entity-reference/src/utils/disjoined-entity-references.ts
`@remirror/extension-entity-reference` doesn't include the dependency `remirror` in its `package.json`, so it shouldn't import anything from `remirror`. 
Fix some typos too in this PR.
=> fix(extension-entity-reference): correct import and typo

.changeset/gorgeous-eyes-attack.md, .changeset/hip-hounds-think.md, packages/remirror__core-helpers/src/core-helpers.ts, packages/remirror__extension-collaboration/__tests__/collaboration-extension.spec.ts, packages/remirror__extension-collaboration/src/collaboration-extension.ts
The private `getSendableSteps` function was arrow bound, which meant that it did not get wrapped in a debounce properly when wrapped.
=> fix(collaboration): fix debouncing of `onSendableReceived` handler

packages/jest-prosemirror/src/jest-prosemirror-editor.ts, packages/jest-prosemirror/src/jest-prosemirror-nodes.ts, packages/remirror__core-utils/__tests__/command-utils.spec.ts, packages/remirror__core-utils/__tests__/prosemirror-utils.spec.ts, packages/remirror__core-utils/src/command-utils.ts, packages/remirror__core-utils/src/core-utils.ts, packages/remirror__core-utils/src/prosemirror-utils.ts, packages/remirror__core/src/builtins/commands-extension.ts, packages/remirror__extension-callout/src/callout-extension.ts, packages/remirror__extension-code-block/src/code-block-extension.ts, packages/remirror__extension-code-block/src/code-block-utils.ts, packages/remirror__extension-codemirror5/src/codemirror-node-view.ts, packages/remirror__extension-codemirror6/src/codemirror-extension.ts, packages/remirror__extension-codemirror6/src/codemirror-node-view.ts, packages/remirror__extension-font-size/src/font-size-extension.ts, packages/remirror__extension-horizontal-rule/src/horizontal-rule-extension.ts, packages/remirror__extension-link/src/link-extension.ts, packages/remirror__extension-list/src/list-command-indent.ts, packages/remirror__extension-list/src/list-commands.ts
This PR uses `TextSelection.between()` and `TextSelection.near()` to replace `TextSelection.create()` and `new TextSelection()`. This will add an extra step before creating a `TextSelection` to make sure that the endpoint positions are valid for a `TextSelection`. 
This PR fixes the following warning during unit tests:
```
console.warn
TextSelection endpoint not pointing into a node with inline content (doc)
```
=> fix: try to find valid endpoint for text selection

.changeset/wise-buses-eat.md, packages/remirror__extension-codemirror6/__tests__/codemirror-extension.spec.ts, packages/remirror__extension-codemirror6/__tests__/tsconfig.json, packages/remirror__extension-codemirror6/src/codemirror-extension.ts, packages/remirror__extension-codemirror6/src/codemirror-types.ts, packages/remirror__extension-codemirror6/src/index.ts, packages/storybook-react/stories/extension-codemirror6/basic.tsx, support/root/tsconfig.json, website/src/tsconfig.json
`@remirror/extension-codemirror6` now includes two new commands: `createCodeMirror` and `updateCodeMirror`, which allows you to create and update a CodeMirror block.
=> feat(extension-codemirror6): add two commands 

.changeset/bright-forks-perform.md, packages/remirror__extension-link/__tests__/link-extension.spec.ts, packages/remirror__extension-link/src/link-extension.ts
When href equals text content there is no reason why a link
should not be editable.
closes #1740
=> fix(link): treat links with same href and text content as auto link

.changeset/seven-timers-prove.md, packages/remirror__styles/all.css, packages/remirror__styles/core.css, packages/remirror__styles/src/dom.tsx, packages/remirror__styles/src/emotion.tsx, packages/remirror__styles/src/styled-components.tsx, packages/remirror__theme/src/core-theme.ts, website/extension-examples/extension-entity-reference/scroll-to-highlight.tsx
Don't set `white-space` as `pre-wrap`, because this will hang end-of-lines spaces, which make the content inside a `<p>` element have more width than the `<p>` element. 
At the top of `core-theme.ts`, we already have [`white-space: break-spaces;`](https://github.com/remirror/remirror/blob/remirror%402.0.0-beta.5/packages/remirror__theme/src/core-theme.ts#L11-L12
). So I just delete these override styles. I don't see the potential uses of these styles anyway. 
https://user-images.githubusercontent.com/24715727/177761259-f8d93125-67d8-4d81-9e93-f096f2f545a7.mp4
=> fix(theme): wrap end-of-lines spaces

.changeset/good-apples-report.md, packages/remirror__extension-entity-reference/__tests__/shortest-entity-reference.spec.ts, packages/remirror__extension-entity-reference/src/index.ts, packages/remirror__extension-entity-reference/src/utils/shortest-entity-reference.ts
This helper can be used when reacting to clicks on overlapping highlights. In that case, the app should show the shortest entity because longer entities typical have other click areas.
=> feat: add helper to get shortest entity reference

.changeset/nice-ties-raise.md, packages/prosemirror-paste-rules/__tests__/paste-rules-plugin.spec.ts, packages/prosemirror-paste-rules/src/paste-rules-plugin.ts, packages/storybook-react/stories/react-components/emoji-popup.stories.tsx
When pasting some text that should be transformed into multiple adjacent inline nodes, avoid creating an empty text node.
Let's say I want to add a node paste rule to `EmojiExtension`. 
```ts
export class EmojiExtension extends NodeExtension<EmojiOptions> {
... 
createPasteRules(): NodePasteRule {
return {
type: 'node',
nodeType: this.type,
regexp: /[🍎🥭🍉]/gu,
getAttributes: (match) => {
return { code: match[0] };
},
getContent: () => {},
};
}
}
```
If I paste two adjacent emojis, then `prosemirror-paste-rules` will try to create an empty text node, which lead to a RangeError. This PR fixes this issue. 
Before:
https://user-images.githubusercontent.com/24715727/179515748-f76eed6c-fb7a-4fb9-971a-3d31f0294144.mp4
After:
https://user-images.githubusercontent.com/24715727/179515900-d08a8a73-b86 …
=> fix(paste-rules): handle adjacent inline matches correctly

.changeset/three-scissors-deny.md, packages/remirror__extension-markdown/__tests__/__snapshots__/markdown-extension.spec.ts.snap, packages/remirror__extension-markdown/__tests__/markdown-extension.spec.ts, packages/remirror__extension-markdown/package.json, packages/remirror__extension-react-tables/src/components/table-components.tsx, packages/remirror__extension-react-tables/src/components/table-delete-row-column-button.tsx, packages/remirror__extension-react-tables/src/components/table-delete-table-button.tsx, packages/remirror__extension-react-tables/src/index.ts, packages/remirror__extension-react-tables/src/react-table-commands.ts, packages/remirror__extension-react-tables/src/table-extensions.tsx, packages/remirror__extension-react-tables/src/table-plugins.ts, packages/remirror__extension-react-tables/src/utils/controller.ts, packages/remirror__extension-react-tables/src/utils/dom.ts, packages/remirror__extension-react-tables/src/views/table-view.tsx, packages/remirror__extension-tables/src/index.ts, packages/remirror__extension-tables/src/table-extensions.ts, packages/remirror__extension-tables/src/table-utils.ts, packages/remirror__styles/all.css, packages/remirror__styles/extension-tables.css, packages/remirror__styles/src/dom.tsx, packages/remirror__styles/src/emotion.tsx, packages/remirror__styles/src/styled-components.tsx, packages/remirror__theme/src/extension-tables-theme.ts, packages/storybook-react/stories/extension-react-tables/basic.tsx, pnpm-lock.yaml
Initialising editor content from HTML or Markdown, that included a React Table, did not initialise the table properly (tables controllers were never injected)
Additionally, copy and pasting a React table didn't check to see if controlled cells were already present. Leading them to be duplicated. (cc @ronnyroeller)
=> fix(react-tables): fix initialisation on tables on view, and copy and paste bugs

.changeset/popular-donuts-yawn.md, packages/remirror__extension-entity-reference/__tests__/entity-reference-extension.spec.ts, packages/remirror__extension-entity-reference/package.json, packages/remirror__extension-entity-reference/src/entity-reference-extension.ts, packages/remirror__extension-entity-reference/src/types.ts, pnpm-lock.yaml
This helps to pass an optional callback to handle clicks on highlight marks
=> feat: add support for optional clickmark handler

package.json, pnpm-lock.yaml
I don't know why this package `aws-cdk` was added to the repo. It seems that we are not using it at all.
=> chore: remove aws-cdk

.changeset/tidy-tips-sit.md, packages/remirror__react-core/src/hooks/use-react-framework.tsx
Fixes https://github.com/remirror/remirror/issues/1814
Please check the Changeset file in this PR for details description.
=> fix(react-core): only re-create initialEditorState when re-mounting

packages/remirror__extension-horizontal-rule/src/horizontal-rule-extension.ts
When a command is created from the CreateCommands method it is not possible to obtain information from it with the getCommandOptions helper. InsertHorizontalRule has been migrated using the @command() decorator in order to get its options.
=> refactor: change insertHorizontalRule as decorated command

.changeset/witty-vans-roll.md, packages/remirror__core-utils/__tests__/core-utils.node.spec.ts, packages/remirror__core-utils/__tests__/core-utils.spec.ts, packages/remirror__core-utils/package.json, packages/remirror__core-utils/readme.md, packages/remirror__core-utils/src/core-utils.ts, pnpm-lock.yaml, support/root/.size-limit.json
Close https://github.com/remirror/remirror/issues/1816 
When I try to use `jsdom` instead of `domino` in `core-utils.spec.ts`, I got the following error:
```
ReferenceError: TextEncoder is not defined
```
I don't know why, but if I move these tests to a new file `core-utils.node.spec.ts`, in which I use comment `@jest-environment node` to specify the test environment to node (instead of jsdom), I no longer see this error.
=> fix(core-utils): remove domino from the codebase

.changeset/olive-kiwis-attack.md, packages/remirror__extension-link/__tests__/link-extension.spec.ts, packages/remirror__extension-link/package.json, packages/remirror__extension-link/src/link-extension.ts, pnpm-lock.yaml
Remove auto link if the link becomes invalid.
Before:
"window.confirm" results in "[window.co](//window.co)nfirm"
After:
"window.confirm" results in "window.confirm"
Add options `findAutoLinks` and `isValidUrl` that if provided,
are used instead of `autoLinkAllowedTLDs` and `autoLinkRegex`
to find and validate a link.
closes #1730 
closes #1732
=> feat(link): auto link adjacent character detection

.changeset/curly-stingrays-dress.md, packages/remirror__extension-emoji/src/emoji-extension.ts, packages/remirror__extension-emoji/src/emoji-utils.ts
when providing custom data words can be separated by "-" instead of "_"
example "flag-" "flag_"
=> feat(emoji-ext): add supported characters option

packages/remirror__cli/src/commands/watch.ts, packages/remirror__cli/src/utils/build-package.ts
=> chore: remirror-cli watch shouldn't override package.json files

.github/workflows/docs.yml, support/scripts/patch-mui-package-json.sh
This is needed for https://github.com/remirror/remirror/pull/1787
=> chore: add a temporary script to fix the api-extractor error

.changeset/famous-penguins-kiss.md, packages/remirror__extension-emoji/src/emoji-utils.ts
The packages uploaded to NPM don't include `src` folder, so TypeScript will complain about it:
```
error TS2345: Argument of type '{ plainText: true; data: FlatEmoji[]; }' is not assignable to parameter of type 'EmojiOptions'.
Property 'supportedCharacters' is missing in type '{ plainText: true; data: FlatEmoji[]; }' but required in type 'EmojiOptions'.
error Command failed with exit code 1.
```
=> fix(extension-emoji): correct a bad import

.changeset/hungry-eggs-beam.md, packages/jest-prosemirror/src/jest-prosemirror-nodes.ts
This PR fixes the [following error](https://github.com/ocavue/rino/runs/8308770778?check_suite_focus=true): 
```
Error: node_modules/.pnpm/jest-prosemirror@2.0.0-beta.18_jsdom@20.0.0/node_modules/jest-prosemirror/dist-types/jest-prosemirror-nodes.d.ts(56,50): error TS2536: Type 'Name' cannot be used to index type '{ doc: { nodeType: string; }; p: { nodeType: string; }; text: { nodeType: string; }; } & Types'.
 ELIFECYCLE  Command failed with exit code 2.
Error: Process completed with exit code 1.
```
=> fix(jest-prosemirror): clarify the TS return type for `pmBuild`

.changeset/shaggy-mugs-fly.md, packages/remirror__extension-events/__tests__/events-extension.spec.ts, packages/remirror__extension-events/src/events-extension.ts
Add new events for double and triple clicks. They uses the [handleDoubleClickOn](https://prosemirror.net/docs/ref/#view.EditorProps.handleDoubleClickOn) and [handleTripleClickOn](https://prosemirror.net/docs/ref/#view.EditorProps.handleTripleClickOn) from ProseMirror under the hood.
=> feat(extension-event): add events for double and triple clicks

.changeset/sharp-flowers-reflect.md, packages/remirror__extension-file/__tests__/tsconfig.json, packages/remirror__extension-file/package.json, packages/remirror__extension-file/src/file-component.tsx, packages/remirror__extension-file/src/file-extension.tsx, packages/remirror__extension-file/src/tsconfig.json, pnpm-lock.yaml, support/root/.size-limit.json, website/extension-examples/extension-link/linkify-js.tsx
Reduce dependency footprint by importing more underlaying packages. 
Before this PR, `@remirror/extension-file@1.0.0` has 210 dependencies (including MUI)
After this PR `@remirror/extension-file@0.0.0-pr1862.1` only has 60 dependencies
(image generated by https://npmgraph.js.org/?q=%40remirror%2Fextension-file%400.0.0-pr1862.1)
=> fix(extension-file): reduce dependency footprint

packages/storybook-react/stories/react-components/node-with-content.stories.tsx, packages/storybook-react/stories/react-components/style/card.css
Added a story "User card" that demonstrates how to create a NodeView with editable content using ReactComponent property.
This is documented [here](https://remirror.io/docs/api/extension-react-component/#class-reactcomponentextension), but there's no story for it.
=> feat(storybook): add nodeview with content story

.changeset/spicy-chefs-do.md, packages/prosemirror-paste-rules/package.json, packages/prosemirror-resizable-view/package.json, packages/prosemirror-suggest/package.json, packages/prosemirror-trailing-node/package.json, packages/remirror__core-utils/package.json, packages/remirror__pm/package.json, pnpm-lock.yaml
This PR fixes a bug that causes `getDocument` not able to create a DOM document using JSDOM. See this commit https://github.com/ocavue/get-dom-document/commit/811ba92ee25fb4ccd9d862cfddf13607913cdde5, which has been released as get-dom-document@0.1.1
=> chore(deps): update dependencies

.changeset/popular-squids-draw.md, packages/remirror__extension-markdown/src/html-to-markdown.ts
This fixes the `import_turndown.default is not a constructor` error in some set-ups.
=> fix: patch default import for turndown

.changeset/old-mugs-collect.md, packages/remirror__cli/src/utils/run-esbuild.ts, packages/remirror__extension-emoji/package.json, packages/remirror__extension-emoji/src/emoji-utils.ts, pnpm-lock.yaml, support/root/.size-limit.json
Add a new package `@ocauve/svgmoji-cjs`, which simply use CJS to require `svgmoji` and then re-export them. This makes sure that we are using the CJS version of svgmoji instead of the invalid ESM version of svgmoji. 
Why don't we just use `require('svgmoji')` in `@remirror/extension-emoji`?
Because in Node.JS ESM environment, `require` is not available by default. By adding another package, we make sure that Node.JS and bundlers can handler this ESM/CJS mix easier.
=> fix(extension-emoji): remove the ESM import from CJS build

docs/contributing.md, packages/remirror__cli/src/commands/build.ts, packages/remirror__cli/src/index.ts
This PR provides a way to build a single package (for faster debug iteration). Eventually, we want to add this feature to `pnpm build`. 
```
pnpm remirror-cli build @remirror/extension-bold @remirror/extension-italic
```
=> chore(cli): pass a package name to only build that package

.changeset/orange-buses-lie.md, packages/remirror__extension-emoji/src/emoji-utils.ts
Fixes https://github.com/remirror/remirror/issues/1884
=> fix(extension-emoji): use namespace import for svgmoji

.changeset/wicked-schools-smile.md, packages/remirror__core-helpers/src/default-import.ts, packages/remirror__extension-emoji/package.json, pnpm-lock.yaml
Fixes https://github.com/remirror/remirror-examples/issues/21
Create React App has poor support for `.cjs` file extension (see https://github.com/facebook/create-react-app/issues/11889#issuecomment-1114878121). 
As a workaround, I change the file extension from `index.cjs` => `index.js` in `@ocavue/svgmoji-cjs@0.1.1`.
=> fix(extension-emoji): don't use .cjs in the svgmoji wrapper

.changeset/sharp-rats-compete.md, packages/multishift/src/multishift-utils.ts, packages/remirror__core-utils/src/dom-utils.ts
Makes the `isDomNode` less strict by don't using `instanceof` in this function. 
This PR fixes an issue I saw on the Discord channel. `isDomNode` won't work if there are two DOM `document` objects and one is in the global environment but the passed node is created by another `document` object. 
> I'm trying out the htmlToProsemirrorNode function - all is good but it skips parsing a few elements (e.g. a  tags) on the server side. I see that it's caused by this line https://github.com/remirror/remirror/blob/77293727c85dcb73f9733f05dceb012d119bca0c/packages/remirror__extension-link/src/link-extension.ts#L330 - the 'isElementDomNode' function is using the global document instead so it keeps failing on the server. The codeblock and react-table extensions are also affected. Should this be fixed …
=> fix(core-utils): don't use `instanceof` in `isDomNode`

.changeset/red-kids-breathe.md, packages/remirror__core-utils/src/core-utils.ts, packages/remirror__core-utils/src/dom-utils.ts, packages/remirror__extension-code-block/__tests__/code-block-extension.node.spec.ts, packages/remirror__extension-code-block/package.json, pnpm-lock.yaml
Make `getStyle` and `getFontSize` robuster in server env. 
We shouldn't directly use the global variable `window` before checking the existing of it, otherwise, we could get the `ReferenceError: window is not defined` error in the server environment.
=> fix(core-utils): don't throw error if window doesn't exist

.changeset/sweet-radios-relax.md, packages/remirror__extension-events/src/events-utils.ts
`viewDes.posFromDom` [can return -1](https://github.com/ProseMirror/prosemirror-view/blob/master/src/viewdesc.ts#L248) which causes a RangeError to be thrown when we try to resolve the position.
=> fix(events): catch when `posFromDOM` returns -1

.changeset/honest-lobsters-stare.md, packages/remirror__extension-react-tables/src/table-extensions.tsx
Using the arrows keys you can navigate to a controller cell and add text in it
https://user-images.githubusercontent.com/2003804/195443030-838051cb-bd66-4748-85eb-30b475ff96cb.mov
I tried changing the `content` definition in the node spec, however that resulted in adding an additional table column on key press.
I also tried prevent the cell `selectable: false`, but that means you can no longer delete columns/rows.
Filter transaction seems to work reliably, so I have used that approach.
I'm open to alternative suggestions!
=> fix(react-table): prevent controller cell content with `filterTransaction`

.changeset/bright-ways-heal.md, packages/remirror__extension-react-tables/src/components/table-components.tsx, packages/remirror__extension-react-tables/src/components/table-controller-cell.ts, packages/remirror__extension-react-tables/src/table-extensions.tsx, packages/remirror__extension-tables/src/table-extensions.ts
Currently when `view.editable = false` tables can still be interacted with - columns can be resized and cells selected, in the case of React Tables, the add row/column buttons are displayed and the dropdowns are visible.
This PR hides all of these feature when the view is not editable.
=> feat(tables,react-tables): remove table plugins if view in not editable

support/scripts/src/generate-configs.ts, support/scripts/src/generate-icons.ts, support/scripts/src/generate-intl.ts, support/scripts/src/helpers.ts
Prevent command injection from `path` when calling `formatFiles`. (Although admittedly it is unlikely to happen currently.)
=> fix: prevent command injection when calling formatFiles 

packages/remirror__core/src/builtins/upload-extension/file-upload.ts, packages/storybook-react/stories/extension-image/basic.tsx, packages/storybook-react/stories/extension-image/image.stories.tsx, packages/storybook-react/stories/extension-image/resizable.tsx, support/root/jest-playwright.config.cjs
https://deelay.me/, which I used to test image layout shifting, returns 502 now. This PR removes deelay.me and fixes the broken storybook.
=> docs: fix the broken image story

.changeset/shaggy-suns-rhyme.md, packages/remirror__extension-image/src/image-extension.ts, packages/storybook-react/stories/extension-image/basic.tsx, packages/storybook-react/stories/extension-image/resizable.tsx
Close https://github.com/remirror/remirror/issues/1929
Before:
https://user-images.githubusercontent.com/24715727/199087602-1fea6f91-09fd-4dc9-b847-fdfd4b982836.mp4
After:
https://user-images.githubusercontent.com/24715727/199087609-f802d816-89dc-4374-9225-aa3f2bf195fd.mp4
=> fix(extension-image): insert image at the drop position

.changeset/little-parrots-destroy.md, packages/multishift/src/multishift-utils.ts
This PR fixes an error  `(0 , import_compute_scroll_into_view.default) is not a function` when using react-scripts. 
> The issue happens with the getMenuProps() function when i use keyboard arrow keys to select items.
> 
> This issue may also affect other areas where getMenuProps() is being used. Here is the error and the sandbox link
https://user-images.githubusercontent.com/24715727/201912478-b1900888-e2da-44dd-92d4-3dbf2e24d89c.mp4
=> fix: fix the default import for `compute-scroll-into-view`

.changeset/smooth-hats-compare.md, .changeset/soft-games-glow.md, packages/remirror__extension-list/src/bullet-list-extension.ts, packages/remirror__styles/all.css, packages/remirror__styles/extension-list.css, packages/remirror__styles/src/dom.tsx, packages/remirror__styles/src/emotion.tsx, packages/remirror__styles/src/styled-components.tsx, packages/remirror__theme/src/extension-list-theme.ts, packages/storybook-react/stories/extension-list/basic.tsx, packages/storybook-react/stories/extension-list/collapsible.tsx, packages/storybook-react/stories/extension-list/toggleable.tsx
Add CSS rule `user-select: none` to some no-selectable elements. This improves the selection behavior on touch screen. 
https://user-images.githubusercontent.com/24715727/203003298-69002526-9bdb-4828-bfc4-a3257f8f9458.MP4
Fix the DOM structure of bullet list with spine. `<ul>` should not contains `<div>`. I didn't see any weird bug related, but I think it's a good idea to make it right. 
- Before: `<ul><div><li>...</li></div></ul>`
- After: `<div><ul><li>...</li></ul></div>`
=> fix(extension-list): improve the selection of lists on touch screen

.changeset/happy-scissors-sit.md, .changeset/old-crews-count.md, packages/remirror__extension-entity-reference/__tests__/entity-reference-extension.spec.ts, packages/remirror__extension-entity-reference/src/entity-reference-extension.ts, packages/remirror__extension-entity-reference/src/index.ts, packages/remirror__extension-entity-reference/src/types.ts, packages/remirror__extension-tables/src/table-extensions.ts, packages/storybook-react/stories/extension-entity-reference/basic.tsx, packages/storybook-react/stories/extension-entity-reference/entity-reference.stories.tsx, packages/storybook-react/stories/extension-link/click-handler.tsx, website/extension-examples/extension-entity-reference/basic.tsx
Add an `onClick` handler, which can be used mutliple times without overwriting previous handlers.
This differs to the existing constructor option `onClickMark` which can only be used once.
=> feat(entity-reference): add an `onClick` handler

.changeset/flat-kids-deny.md, .changeset/gold-games-act.md, packages/remirror__core-utils/src/core-utils.ts, packages/remirror__core-utils/src/index.ts, packages/remirror__extension-doc/__tests__/doc-extension.spec.ts, packages/remirror__extension-doc/src/doc-extension.ts, packages/remirror__extension-tables/src/table-extensions.ts, packages/storybook-react/stories/extension-tables/not-editable.tsx, packages/storybook-react/stories/extension-tables/table.stories.tsx, website/extension-examples/extension-tables/not-editable.tsx
Fixes #1937
Also adds a helper to the doc extension for determining if the doc content has been changed from the default
=> fix(tables): apply table columns sizes when `editable=false`

.changeset/serious-pumas-destroy.md, .changeset/slow-pugs-argue.md, .changeset/strong-buses-vanish.md, packages/jest-prosemirror/src/jest-prosemirror-editor.ts, packages/jest-remirror/src/jest-remirror-editor.ts, packages/prosemirror-paste-rules/__tests__/paste-rules-plugin.spec.ts, packages/prosemirror-paste-rules/src/paste-rules-plugin.ts
This PR fixes the following crash. It took me so long to reproduce it : D 
https://user-images.githubusercontent.com/24715727/206516806-0b2510e1-c184-4e41-9e48-f53bf99de5ce.mp4
This PR also includes some improvement for the JSDOM unit test framework, as I need them to reproduce this bug with JSDOM. Check the changeset files for details.
=> fix(paste-rules): fix a crash when pasting nested content

.changeset/angry-lions-trade.md, .changeset/curly-monkeys-shave.md, packages/remirror__extension-entity-reference/__tests__/entity-reference-extension.spec.ts, packages/remirror__extension-entity-reference/src/entity-reference-extension.ts, packages/remirror__react-core/src/index.ts
Most of our helpers allow passing an editor state param (which defaults to the current state), this is useful for plugins when you want to execute helpers on `prevState`.
This PR aligns the entity reference helpers with this pattern.
The PR also exposes `useDocChanged` as requested on Discord.
=> feat(entity-reference): get references from arbitrary editor states

.changeset/silver-cats-tickle.md, packages/remirror__core/src/builtins/keymap-extension.ts
This PR is a performance optimization by NOT calling `this.store.updateExtensionPlugins` when updating keymaps. See the changeset file for more details.
=> refactor(core): don't reconfigure plugins when updating keymap

.changeset/lovely-carpets-jog.md, packages/jest-remirror/src/jsdom-polyfills.ts
This PR adds a polyfill for `element.scrollIntoView` in JSDOM environment. I see this issue outside the Remirror repo but I think it's not a bad idea to polyfill it on the Remirror side.
=> feat(jest-remirror): polyfill for `element.scrollIntoView`

.changeset/hot-drinks-knock.md, packages/remirror__core-helpers/src/core-errors.ts
This is a workaround for https://github.com/remirror/remirror/issues/1970, by removing the `__super = (...args) => ...` function in the compiled code. 
The compiled code before this PR:
```
// remirror/packages/remirror__core-helpers/dist/remirror-core-helpers.js
var RemirrorError = class extends BaseError2 {
constructor({ code, message, disableLogging = false } = {}) {
var __super = (...args) => {
super(...args);
__publicField(this, "errorCode");
__publicField(this, "url");
};
let errorCode;
if (isErrorConstant(code)) {
errorCode = code;
__super(createErrorMessage(errorCode, message));
} else {
errorCode = ErrorConstant.CUSTOM;
__super(createErrorMessage(errorCode, message));
}
```
After this PR:
```
// remirror/packages/remirror__core-helpers/dist/remirror-core-helpers.js
var …
```
=> fix(core): don't call `super()` conditional

docs/5-min-tutorial.md
This PR replaces create-react-app with Vite in the docs. Close https://github.com/remirror/remirror/issues/1970. 
I've see lots of building issues with create-react-app, which won't occur in other webpack-based tools (i.e. Next.js). CRA is not a good default anymore for a React project IMH. I would recommend Next.js and/or Vite today. Vite is more lightweight so I'd like to put it in our tutorial. 
--- 
Here is just a simple benchmark example. While `create-react-app` needs one minute, `create-vite` only needs two seconds. 🤦‍♂️
```bash
$ time npx --yes create-vite vite-remirror-3 --template react-ts
1.672 total
$ time npx --yes create-react-app cra-remirror-3 --template typescript 
1:28.38 total
```
=> docs: replace create-react-app with vite

.changeset/beige-jokes-juggle.md, packages/remirror__extension-events/__tests__/events-extension.spec.ts, packages/remirror__extension-events/src/events-extension.ts
This PR fixes the marks matching when use `useHover`. 
```
useHover((event, {marks}) => { console.log(marks) })
```
I wrote a test case to reproduce the origin bug.
=> fix(extension-events): fix marks matching for hover event

packages/remirror__react-editors/src/markdown/markdown-editor.tsx, packages/storybook-react/stories/react-editors/markdown-editor.tsx
looks like the link extension was accidentally added twice
=> docs(markdown-editor): remove-duplicate-ext

.changeset/popular-maps-fail.md, packages/prosemirror-paste-rules/src/paste-rules-plugin.ts
This PR allows users to write TS code like something below in TypeScript 4.9:
```ts
createPasteRules(): NodePasteRule[] {
return [
{
type: 'node',
nodeType: this.store.schema.nodes.tweet,
regexp: TWITTER_STATUS_REGEX,
getAttributes: (match: RegExpMatchArray) => {
const url = `https://twitter.com/${match.groups?.user_id}/status/${match.groups?.tweet_id}`
return {url, 'data-preview': '1'}
},
},
]
}
```
=> fix(paste-rules): update typescript type

.changeset/strong-bags-hunt.md, .size-limit.json, packages/remirror__react-components/src/buttons/command-button.tsx
Closes #1901
(Added bonus is now tooltips work on inactive buttons as well)
=> fix(react-components): add wrapper to buttons to eliminate MUI tooltip error

.changeset/ten-wolves-own.md, packages/remirror__react-editors/src/markdown/markdown-editor.tsx, packages/remirror__react-editors/src/social/social-editor.tsx, packages/remirror__react-editors/src/types.ts, packages/remirror__react-editors/src/wysiwyg/wysiwyg-editor.tsx
- Added  theme customization support for @remirror/react-editors
=> feat: add theme customization support for react-editors

.changeset/twenty-pumas-rhyme.md, packages/remirror__extension-react-tables/src/table-extensions.tsx
use this initial content 
[test-table-content.json.zip](https://github.com/remirror/remirror/files/11505751/test-table-content.json.zip)
and the second table will be nested in the first table
I think the problem is the pos of node doesn't be mapped after tr has been updated.
=> fix(react-tables): replace table with correct positions 

.changeset/hip-mugs-report.md, packages/remirror__extension-link/src/link-extension.ts
I set the prop `openLinkOnClick` which is one of the options for LinkExtension to true and set 'contenteditable' to false,then I click this link mark, there would be a new tab and the current tab has also been redirected.
So I think the click should be disabled when contenteditable is false and let default browser event happen.
=> fix(link): disable link click handler when contenteditable is false

.changeset/six-tips-learn.md, packages/remirror__extension-code-block/src/code-block-extension.ts
When the isolating attribute is set on the codeBlock, deleting the leading line of text causes the cursor to select the code block instead of staying with the line of code immediately following it. This behavior is confusing to me.
In `tiptap` and `prosemirror-schema-basic`, the isolating attribute is not set on codeBlock, and I think the behavior resulting from their settings is intuitive.
=> fix(code-block): remove  isolating  from codeBlock

.changeset/quick-mirrors-unite.md, packages/remirror__core/src/builtins/upload-extension/file-placeholder-plugin.ts, packages/remirror__extension-file/src/file-extension.tsx, packages/remirror__extension-file/src/file-uploaders/slow-file-uploader.ts
If the the file node is moved by cut-and-paste before the upload is finish, the uploaded information won't be update correctly. This PR fixes the issue by (1) add the uploading id to the DOM and paste this attribute, and (2) re-check the placeholder position when the upload is finished 
_Before:_ 
https://github.com/remirror/remirror/assets/24715727/fbc5a5ed-d0c9-4c34-825e-4ee8b3ead76e
_After:_
https://github.com/remirror/remirror/assets/24715727/2fc51682-3e6a-49f8-b5ea-960d48701089
=> fix(core): re-check upload placeholder position

docs/errors.md, docs/getting-started/create-manager.md
Hello! I've notice a minor error when going through the `Getting Started -> Create a Manager` page. The code snippet way down below of the page where it the JSON format won't actually work because it lacked the `HeadingExtension` for the type `heading`, so I've added just that. Or if you feel that we can just delete the content line that works out too.
Please do let me know if I'm doing PR wrong, it's my first time
=> docs: fix extension imports in example snippet

.changeset/unlucky-scissors-provide.md, packages/remirror__react-core/src/hooks/use-i18n.ts
Close https://github.com/remirror/remirror/issues/2108
Before: 
After:
=> fix: fix lingui runtime crash

.changeset/itchy-cows-tie.md, packages/remirror__core/__tests__/commands-extension.spec.ts, packages/remirror__core/src/builtins/commands-extension.ts, packages/remirror__core/src/extension/extension-types.ts, packages/remirror__react-core/src/hooks/use-chained-commands.ts
Makes `useChainedCommands()` return a different chain instance on each call.
Currently, when calling `useChainedCommands()` multiple times, each call returns the **same** chain instance, so commands from _all_ chains are run when calling `.run()` on any of them.
```ts
const chain1 = useChainedCommands();
const chain2 = useChainedCommands();
chain1.toggleBold().toggleItalic();
if (false) {
chain1.run();
}
// All three commands get run
chain2.toggleUnderline().run();
```
Reproduction: https://codesandbox.io/s/suspicious-cloud-ywpt45?file=/src/ChainedCommandsButton.tsx
This PR ensures that each call to `useChainedCommands()` returns a separate chain, so in the above example, only `toggleUnderline()` is run 
After: https://codesandbox.io/s/fervent-mayer-8jvcc2?file=/src/ChainedCommandsButton.t …
=> fix(react-core): `useChainedCommands` should not share chains

.changeset/lazy-students-add.md, .changeset/tiny-dryers-yawn.md, packages/remirror__extension-tables/__tests__/table-extensions.spec.ts, packages/remirror__extension-tables/src/table-extensions.ts
Exposes the ProseMirror tables command [`toggleHeader`](https://github.com/ProseMirror/prosemirror-tables/blob/master/src/commands.ts#L673C17-L673C29), via the Remirror command `toggleTableHeader`.
This differs from the existing toggle header commands in that it only toggles the **first** row or column.
```tsx
const { toggleTableHeader } = useCommands();
const handleClick = useCallback(() => {
toggleTableHeader(); // row by default
// Or
toggleTableHeader('column');
}, [toggleTableHeader]);
```
Also exposes a helper `tableHasHeader`, which returns a boolean stating if the first row or column is a header.
```tsx
const { tableHasHeader } = useHelpers(true);
console.log('first row is header', tableHasHeader());
console.log('first column is header', tableHasHeader('column'));
```
=> feat(tables): toggle header cells only on the first row or column

.changeset/eleven-students-think.md, packages/prosemirror-trailing-node/package.json, packages/remirror__core-constants/package.json, packages/remirror__core-helpers/package.json, pnpm-lock.yaml
Removed @babel/runtime dependency from following packages:
- prosemirror-trailing-node
- @remirror/core-constants
- @remirror/core-helpers
See https://github.com/remirror/remirror/discussions/2130 for more details
=> chore: remove babel runtime from some packages

.changeset/polite-kids-unite.md, packages/remirror__core-helpers/package.json, packages/remirror__core-helpers/src/core-helpers.ts, packages/remirror__core/src/builtins/attributes-extension.ts, packages/remirror__core/src/framework/base-framework.ts, packages/remirror__core/src/framework/framework.ts, packages/remirror__core/src/helpers.ts, packages/remirror__core/src/index.ts, pnpm-lock.yaml
I am using the tiptap editor which uses `prosemirror-trailing-node` and therefore `@remirror/core-helpers` package, but not `@remirror/core` package.
This PR moves one function which uses the `@linaria/core` package to the core package to reduce dependencies for core-helpers as this package is often used without remirror/core.
I searched all remirror packages where the `cx` function was used and it was always used from the `core` package, so this PR should not have much impact on other packages. Still, as the function was exported, this is possibly a breaking change.
=> refactor: move @linaria/core dependency from core-helpers to core

.changeset/grumpy-clocks-begin.md, packages/remirror__extension-events/src/events-extension.ts, packages/remirror__extension-react-tables/src/table-extensions.tsx, packages/remirror__extension-tables/package.json, packages/remirror__extension-tables/src/table-extensions.ts, packages/storybook-react/stories/extension-react-tables/basic.tsx, pnpm-lock.yaml
The table plugin can not be updated when the editable state changes.So I add an editable state change event and use it into tableExtension.
I also believe that more plugins may need to respond correctly to changes in the editable state.
=> fix: plugins of tableExtension can be updated when editable has been changed

.changeset/quick-ears-argue.md, .size-limit.json, package.json, packages/remirror/package.json, packages/remirror__core/__dts__/extension-types.dts.ts, packages/remirror__extension-code-block/__tests__/code-block-extension.spec.ts, packages/remirror__extension-code-block/package.json, packages/remirror__extension-code-block/src/formatter.ts, packages/remirror__extension-react-tables/src/views/table-controller-cell-view.tsx, packages/remirror__extension-tables/__tests__/tsconfig.json, packages/remirror__extension-tables/src/tsconfig.json, packages/remirror__styles/all.css, packages/remirror__styles/components.css, packages/remirror__styles/extension-emoji.css, packages/remirror__styles/extension-mention-atom.css, packages/remirror__styles/src/dom.tsx, packages/remirror__styles/src/emotion.tsx, packages/remirror__styles/src/styled-components.tsx, packages/remirror__theme/src/components-theme.ts, packages/remirror__theme/src/extension-emoji-theme.ts, packages/remirror__theme/src/extension-mention-atom-theme.ts, pnpm-lock.yaml, support/scripts/package.json, support/scripts/src/generate-icons.ts
* `prettier` 3.0.0 version was released last month ([Release note](https://prettier.io/blog/2023/07/05/3.0.0.html))
* `@types/prettier` has been deprecated ([more information](https://www.npmjs.com/package/@types/prettier))
It can be installed using the `--legacy-peer-defs` or `--force` option, but updating the dependency looks better
So I proceeded with the dependency update and tested it. Please consider this request because there is currently a conflict in installing the latest version of Prettier.
* All Test Passed
=> chore(deps): update dependency prettier to v 3.0.0

docs/concepts/extension.md
This is a simple docs change to fix a broken link on this page: https://remirror.io/docs/concepts/extension/
Clicking the link in Chrome on Macos leads to a 404. Refreshing that 404 then redirects to the same URL without the trailing `/index`. So I assume removing that part will fix the 404.
=> docs: correct link in extension.md

.changeset/tiny-points-sing.md, .size-limit.json, package.json, packages/remirror/package.json, packages/remirror__core/__dts__/extension-types.dts.ts, packages/remirror__extension-code-block/__tests__/code-block-extension.spec.ts, packages/remirror__extension-code-block/package.json, packages/remirror__extension-code-block/src/formatter.ts, packages/remirror__extension-react-tables/src/views/table-controller-cell-view.tsx, packages/remirror__extension-tables/__tests__/tsconfig.json, packages/remirror__extension-tables/src/tsconfig.json, packages/remirror__styles/all.css, packages/remirror__styles/components.css, packages/remirror__styles/extension-emoji.css, packages/remirror__styles/extension-mention-atom.css, packages/remirror__styles/src/dom.tsx, packages/remirror__styles/src/emotion.tsx, packages/remirror__styles/src/styled-components.tsx, packages/remirror__theme/src/components-theme.ts, packages/remirror__theme/src/extension-emoji-theme.ts, packages/remirror__theme/src/extension-mention-atom-theme.ts, pnpm-lock.yaml, support/scripts/package.json, support/scripts/src/generate-icons.ts
This reverts https://github.com/remirror/remirror/pull/2139
Prettier v3 has changed all APIs to be asynchronous. ProseMirror's APIs are mostly synchronous, so using Prettier v3's API would be challenging (although possible). @prettier/sync provides a synchronous Prettier v3 API, but this library can only be used in a Node.js environment, so we cannot use it either.
=> fix: revert prettier back to v2.8.8

.changeset/wild-days-tickle.md, packages/remirror__extension-events/__tests__/events-extension.spec.ts, packages/remirror__extension-events/src/events-extension.ts
reproduction video
https://github.com/remirror/remirror/assets/45024986/b33400a0-ec3d-455a-aa9c-9522492f54f8
=> fix(events-extension): click events cannot be obtained for individual string links

.changeset/clever-lions-breathe.md, packages/prosemirror-paste-rules/package.json, packages/prosemirror-resizable-view/package.json, packages/prosemirror-suggest/package.json, packages/prosemirror-trailing-node/package.json, packages/remirror__extension-doc/__tests__/doc-extension.spec.ts, packages/remirror__extension-doc/src/doc-extension.ts, packages/remirror__extension-yjs/package.json, packages/remirror__pm/package.json, pnpm-lock.yaml
Update ProseMirror packages to latest versions.
Use newly provided `Transform.setDocAttribute` to update doc node attributes, rather than custom step type.
=> feat(pm): prosemirror dependencies update

.changeset/smart-garlics-bow.md, docs/concepts/extension.md, docs/concepts/keymap.md, docs/concepts/priority.md, packages/remirror__core-types/src/annotation-types.ts, packages/remirror__core/__tests__/decorators.spec.ts, packages/remirror__core/src/extension/extension-decorator.ts
💥 BREAKING 💥: Remove deprecated decorator `extensionDecorator`. Please use `extension` instead
Make `extension` decorator backwards compatible when called directly as a function.
=> feat: make `extension` decorator backwards compatible when called as function

.changeset/weak-tigers-share.md, packages/remirror__extension-tables/__tests__/table-extensions.spec.ts, packages/remirror__extension-tables/src/table-extensions.ts
Add a `tabKeyboardShortcuts` option to `TableExtension` to enable `Tab` and `Shift-Tab` keyboard shortcuts for navigating between table cells. 
Defaults to `false`.
=> feat(tables): add opt-in `Tab` and `Shift-Tab` keyboard shortcuts

.changeset/tough-ladybugs-marry.md, packages/remirror__extension-tables/src/table-utils.ts
Calling `commands.setTableCellBackground` overrides the `style` attribute of the node. It updates the reference from `attrs.style` to `node.attrs.style` as we need to get the style from the node first and then override the `background` property.
N\A
=> fix(table-extension): apply correct attrs.style

.changeset/young-seahorses-listen.md, packages/prosemirror-trailing-node/__tests__/tsconfig.json, packages/prosemirror-trailing-node/package.json, packages/prosemirror-trailing-node/src/trailing-node-plugin.ts, packages/prosemirror-trailing-node/src/tsconfig.json, pnpm-lock.yaml
Replace use of `includes()` and `uniqueArray()` with equivalent code that relies on standard built-in objects, allowing us to avoid importing the rest of `@remirror/core-helpers`, which `prosemirror-trailing-node` does not need
`@remirror/core-helpers` imports `throttle-debounce`, which, while licensed under MIT, is a fork of `jquery-throttle-debounce`, which is _dual-licensed_ under MIT and GPL. There is significant legal ambiguity whether dependents are free to comply with just one of the licenses, or compliance with both licenses is needed, especially since the author of `jquery-throttle-debounce` did not explicitly state in no uncertain terms what is acceptable, and what is not.
Given that `prosemirror-trailing-node` does not actually need throttling or debouncing, and the helper …
=> refactor(trailing-node): remove `@remirror/core-helpers`

packages/jest-prosemirror/readme.md
There's an import from `jest-remirror` in the docs for `jest-prosemirror`, fairly sure this is a typo.
=> fix(docs): correct jest-remirror reference

.changeset/nasty-impalas-search.md, .vscode/settings.json, packages/remirror__extension-file/src/file-extension.tsx
Allow `fileSize` attribute to be string type so that it's compatible with existing data.
=> fix(extension-file): allow `fileSize` to be string

.changeset/dirty-penguins-help.md, packages/remirror__extension-bidi/src/bidi-extension.ts, packages/remirror__extension-callout/src/callout-extension.ts, packages/remirror__extension-code-block/src/code-block-extension.ts, packages/remirror__extension-codemirror5/src/codemirror-extension.ts, packages/remirror__extension-codemirror6/src/codemirror-extension.ts, packages/remirror__extension-columns/src/columns-extension.ts, packages/remirror__extension-doc/src/doc-extension.ts, packages/remirror__extension-embed/src/iframe-extension.ts, packages/remirror__extension-emoji/src/emoji-extension.ts, packages/remirror__extension-entity-reference/src/entity-reference-extension.ts, packages/remirror__extension-file/src/file-extension.tsx, packages/remirror__extension-font-family/src/font-family-extension.ts, packages/remirror__extension-font-size/src/font-size-extension.ts, packages/remirror__extension-heading/__tests__/heading-extension.spec.ts, packages/remirror__extension-heading/src/heading-extension.ts, packages/remirror__extension-image/src/image-extension.ts, packages/remirror__extension-link/__tests__/link-extension.spec.ts, packages/remirror__extension-link/src/link-extension.ts, packages/remirror__extension-list/src/list-item-extension.ts, packages/remirror__extension-list/src/ordered-list-extension.ts, packages/remirror__extension-list/src/task-list-item-extension.ts, packages/remirror__extension-mention-atom/src/mention-atom-extension.ts, packages/remirror__extension-mention/src/mention-extension.ts, packages/remirror__extension-node-formatting/src/node-formatting-extension.ts, packages/remirror__extension-react-tables/src/table-extensions.tsx, packages/remirror__extension-tables/src/table-utils.ts, packages/remirror__extension-text-case/src/text-case-extension.ts, packages/remirror__extension-text-color/src/text-color-extension.ts, packages/remirror__extension-text-highlight/src/text-highlight-extension.ts
Drop the explicit `validate` property, added to attributes in #2264
Some users have reported issues with legacy JSON data in JavaScript repos where attribute types have not been strictly checked (i.e. calling a command with a _string_ attribute value instead of a _number_).
[The XSS issue in ProseMirror](https://discuss.prosemirror.net/t/heads-up-xss-risk-in-domserializer/6572) has been largely resolved since the changes added in prosemirror-model 1.22.1, which actively guards against corrupted-attribute XSS attacks in `DOMSerializer`. This makes the additional protection of an explicit `validate` attribute largely redundant.
=> fix: remove explicit validate properties

.changeset/honest-socks-sip.md, .size-limit.json, packages/jest-prosemirror/src/jest-prosemirror-editor.ts
Some `ProseMirror` plugins rely on the editor's outer DOM structure. For instance, if a plugin's [`view`](https://prosemirror.net/docs/ref/#state.PluginSpec.view) method uses something like `view.dom.parentElement`, it can lead to errors during tests because `parentElement` is `null` when the editor is created with `createEditor`. Appending the element to the DOM ensures plugins that depend on the DOM structure can be tested without issues, improving the robustness and reliability of the createEditor utility function.
=> refactor(jest-prosemirror): append element to DOM before EditorView initialization in `createEditor`

packages/storybook-react/stories/extension-positioner/basic.tsx
This PR resolves the crash when you try to visit [https://remirror.io/docs/extensions/positioner-extension/](https://remirror.io/docs/extensions/positioner-extension/).
Storybook arguments are sometimes undefined when the positioner extension template renders. Especially the `positioner` argument does not tolerate `undefined`, causing the page to crash. This appears similar to issue https://github.com/storybookjs/storybook/issues/14732, but for React. Work around the issue by ensuring fallback arguments are available if storybook fails to provide them.
Fixes #2262
Before:
After:
=> fix(docs): fix crash in positioner extension storybook

docs/concepts/extension.md
Fix typo in extension.md
Small typo fix on the extension documentation page.
n/a
=> docs: fix typo in extension.md

support/scripts/src/helpers.ts
A `--loglevel` to `--log-level` CLI argument update was missed in PR #2255. Fix it.
=> fix: update prettier log level arg in helper script

.changeset/brave-suits-grab.md, docs/migration-v3.md, packages/remirror__core/src/builtins/builtin-decorators.ts, packages/remirror__react-ui/readme.md, website/sidebar.cjs
Expose the previous versions of Remirror's decorators with a _legacy_ prefix, so users who are unable to use Stage 3 decorators are not blocked updating to Remirror v3.
Update the migration guide.
=> fix: expose old version of decorators with legacy prefix

.changeset/calm-paws-divide.md, packages/remirror__core/src/builtins/builtin-decorators.ts
While legacy decorators have been exposed back in https://github.com/remirror/remirror/pull/2285, the typing for `@legacyCommand` is not correct, as it relates to the new decorators. 
This PR attempts to fix this issue.
=> fix: use the original typing for legacy command decorator
